import { useMutation } from '@tanstack/react-query';

import { notification } from "../../../service/notifications";
import { fetchClient, queryClient, QueryKeys } from "../../api";

export const useDeleteAllAutoAlbumsMutation = () => useMutation({
  mutationFn: async () => {
    await fetchClient.post('/albums/auto/delete_all/');
    notification.deleteAutogeneratedAlbums();
  },
  onSuccess: () => {
    queryClient.invalidateQueries({ queryKey: [QueryKeys.autoAlbums] });
    queryClient.invalidateQueries({ queryKey: [QueryKeys.autoAlbum] });
  }
}); 