/**
 * The success toast fired inside mutationFn, and a refused request (403, no
 * connection) showed nothing at all. A 401 and a 500 are reported by the fetch
 * client already and must not get a second toast.
 */
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import React, { act } from "react";
import { createRoot } from "react-dom/client";
import { beforeAll, beforeEach, describe, expect, it, vi } from "vitest";
import i18n from "../../../i18n";
import { ApiError } from "../../api";
import { useDeleteAllAutoAlbumsMutation } from "./useDeleteAllAutoAlbumsMutation";

const stubs = vi.hoisted(() => ({
  post: vi.fn(),
  invalidateQueries: vi.fn(),
  deleteAutogeneratedAlbums: vi.fn(),
  requestFailed: vi.fn(),
}));

vi.mock("../../api", async importOriginal => ({
  ...(await importOriginal<typeof import("../../api")>()),
  fetchClient: { post: (...args: unknown[]) => stubs.post(...args) },
  queryClient: { invalidateQueries: stubs.invalidateQueries },
}));
vi.mock("../../../service/notifications", () => ({
  notification: { deleteAutogeneratedAlbums: stubs.deleteAutogeneratedAlbums, requestFailed: stubs.requestFailed },
}));

let mutate: ReturnType<typeof useDeleteAllAutoAlbumsMutation>["mutateAsync"];

function Harness() {
  mutate = useDeleteAllAutoAlbumsMutation().mutateAsync;
  return null;
}

beforeAll(() => {
  (globalThis as { IS_REACT_ACT_ENVIRONMENT?: boolean }).IS_REACT_ACT_ENVIRONMENT = true;
});

beforeEach(async () => {
  vi.clearAllMocks();
  const root = createRoot(document.createElement("div"));
  await act(async () => {
    root.render(
      <QueryClientProvider client={new QueryClient({ defaultOptions: { mutations: { retry: false } } })}>
        <Harness />
      </QueryClientProvider>
    );
  });
});

async function deleteAll() {
  await act(async () => {
    await mutate().catch(() => {});
  });
}

describe("useDeleteAllAutoAlbumsMutation", () => {
  it("confirms and refetches the event albums once the server deleted them", async () => {
    stubs.post.mockResolvedValue({});

    await deleteAll();

    expect(stubs.post).toHaveBeenCalledWith("/albums/auto/delete_all/");
    expect(stubs.deleteAutogeneratedAlbums).toHaveBeenCalledTimes(1);
    expect(stubs.invalidateQueries).toHaveBeenCalledTimes(2);
    expect(stubs.requestFailed).not.toHaveBeenCalled();
  });

  it("says so when the server refuses, with its message", async () => {
    stubs.post.mockRejectedValue(new ApiError("Forbidden", 403, "Not allowed"));

    await deleteAll();

    expect(stubs.deleteAutogeneratedAlbums).not.toHaveBeenCalled();
    expect(stubs.requestFailed).toHaveBeenCalledWith(i18n.t("toasts.deleteallautoalbumsfailedtitle"), "Not allowed");
  });

  it("falls back to a generic message without a server answer", async () => {
    stubs.post.mockRejectedValue(new TypeError("Failed to fetch"));

    await deleteAll();

    expect(stubs.requestFailed).toHaveBeenCalledTimes(1);
    expect(stubs.requestFailed).toHaveBeenCalledWith(
      i18n.t("toasts.deleteallautoalbumsfailedtitle"),
      i18n.t("toasts.deleteallautoalbumsfailed")
    );
    // i18n.t answers a missing key with the key itself, which the call above
    // would accept: make sure both strings really exist.
    expect(i18n.exists("toasts.deleteallautoalbumsfailedtitle")).toBe(true);
    expect(i18n.exists("toasts.deleteallautoalbumsfailed")).toBe(true);
  });

  it.each([401, 500])("leaves a %i to the fetch client's own toast", async status => {
    stubs.post.mockRejectedValue(new ApiError("error", status));

    await deleteAll();

    expect(stubs.requestFailed).not.toHaveBeenCalled();
    expect(stubs.deleteAutogeneratedAlbums).not.toHaveBeenCalled();
  });
});
