import { useMutation } from "@tanstack/react-query";
import i18n from "../../../i18n";
import { notification } from "../../../service/notifications";
import { ApiError, fetchClient, queryClient } from "../../api";
import { AutoAlbumQueryKeys } from "./useFetchAutoAlbumQuery";
import { AutoAlbumsQueryKeys } from "./useFetchAutoAlbumsQuery";

export const useDeleteAllAutoAlbumsMutation = () =>
  useMutation({
    mutationFn: async () => {
      await fetchClient.post("/albums/auto/delete_all/");
    },
    onSuccess: () => {
      notification.deleteAutogeneratedAlbums();
      queryClient.invalidateQueries({ queryKey: [...AutoAlbumsQueryKeys] });
      queryClient.invalidateQueries({ queryKey: [...AutoAlbumQueryKeys] });
    },
    onError: error => {
      // The fetch client already reports a 401 and a 500; anything else (a 403,
      // no connection) used to fail without a word.
      if (error instanceof ApiError && (error.status === 401 || error.status === 500)) {
        return;
      }
      notification.requestFailed(
        i18n.t("toasts.deleteallautoalbumsfailedtitle"),
        (error instanceof ApiError && error.serverMessage) || i18n.t("toasts.deleteallautoalbumsfailed")
      );
    },
  });
