FROM node:22-slim

RUN mkdir -p /usr/src/app/apps/frontend
WORKDIR /usr/src/app/apps/frontend
RUN apt-get update && apt-get install git curl -y
EXPOSE 3000
COPY deploy/docker/frontend/entrypoint.sh /entrypoint.sh
CMD ["/entrypoint.sh"]
