# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('location_top', models.IntegerField()),
                ('location_bottom', models.IntegerField()),
                ('location_left', models.IntegerField()),
                ('location_right', models.IntegerField()),
                ('encoding', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('image_path', models.FilePathField()),
                ('thumbnail', models.ImageField(upload_to='thumbnails')),
                ('image_hash', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('exif_gps_lat', models.FloatField(blank=True, null=True)),
                ('exif_gps_lon', models.FloatField(blank=True, null=True)),
                ('exif_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='face',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.Person'),
        ),
        migrations.AddField(
            model_name='face',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='albums.Photo'),
        ),
    ]
