-- Baseline: the Django schema at api.0144 on SQLite (application tables only).
-- Generated by tests/fixture/sqlite_baseline.py from sqlite_master of a fresh
-- DB_BACKEND=sqlite `manage.py migrate` (build_fixture.sh, LP_FIXTURE_BACKEND=sqlite).
-- Excludes api_user_groups / api_user_user_permissions (FKs to Django auth tables).

CREATE TABLE "api_cluster" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "mean_face_encoding" text NOT NULL, "cluster_id" integer NULL, "name" text NULL, "person_id" integer NULL REFERENCES "api_person" ("id") DEFERRABLE INITIALLY DEFERRED, "owner_id" integer NULL REFERENCES "api_user" ("id") DEFERRABLE INITIALLY DEFERRED);

CREATE TABLE "api_file_embedded_media" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "from_file_id" varchar(64) NOT NULL REFERENCES "api_file" ("hash") DEFERRABLE INITIALLY DEFERRED, "to_file_id" varchar(64) NOT NULL REFERENCES "api_file" ("hash") DEFERRABLE INITIALLY DEFERRED);

CREATE TABLE "api_albumdate" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(512) NOT NULL, "date" date NULL, "favorited" bool NOT NULL, "location" text NULL CHECK ((JSON_VALID("location") OR "location" IS NULL)), "owner_id" integer NOT NULL REFERENCES "api_user" ("id") DEFERRABLE INITIALLY DEFERRED);

CREATE TABLE "api_albumdate_shared_to" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "albumdate_id" integer NOT NULL REFERENCES "api_albumdate" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "api_user" ("id") DEFERRABLE INITIALLY DEFERRED);

CREATE TABLE "api_albumthing_shared_to" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "albumthing_id" integer NOT NULL REFERENCES "api_albumthing" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "api_user" ("id") DEFERRABLE INITIALLY DEFERRED);

CREATE TABLE "api_albumauto_shared_to" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "albumauto_id" integer NOT NULL REFERENCES "api_albumauto" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "api_user" ("id") DEFERRABLE INITIALLY DEFERRED);

CREATE TABLE "api_albumplace_shared_to" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "albumplace_id" integer NOT NULL REFERENCES "api_albumplace" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "api_user" ("id") DEFERRABLE INITIALLY DEFERRED);

CREATE TABLE "api_albumuser_shared_to" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "albumuser_id" integer NOT NULL REFERENCES "api_albumuser" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "api_user" ("id") DEFERRABLE INITIALLY DEFERRED);

CREATE TABLE "api_albumusershare" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "enabled" bool NOT NULL, "slug" varchar(64) NULL UNIQUE, "expires_at" datetime NULL, "album_id" integer NOT NULL UNIQUE REFERENCES "api_albumuser" ("id") DEFERRABLE INITIALLY DEFERRED, "share_location" bool NULL, "share_camera_info" bool NULL, "share_timestamps" bool NULL, "share_captions" bool NULL, "share_faces" bool NULL);

CREATE TABLE "api_metadataedit" ("id" char(32) NOT NULL PRIMARY KEY, "field_name" varchar(100) NOT NULL, "old_value" text NULL CHECK ((JSON_VALID("old_value") OR "old_value" IS NULL)), "new_value" text NULL CHECK ((JSON_VALID("new_value") OR "new_value" IS NULL)), "synced_to_file" bool NOT NULL, "synced_at" datetime NULL, "created_at" datetime NOT NULL, "photo_id" char(32) NOT NULL REFERENCES "api_photo" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "api_user" ("id") DEFERRABLE INITIALLY DEFERRED);

CREATE TABLE "api_metadatafile" ("id" char(32) NOT NULL PRIMARY KEY, "file_type" varchar(10) NOT NULL, "source" varchar(20) NOT NULL, "priority" integer NOT NULL, "creator_software" varchar(100) NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "file_id" varchar(64) NOT NULL UNIQUE REFERENCES "api_file" ("hash") DEFERRABLE INITIALLY DEFERRED, "photo_id" char(32) NOT NULL REFERENCES "api_photo" ("id") DEFERRABLE INITIALLY DEFERRED);

CREATE TABLE "api_photometadata" ("id" char(32) NOT NULL PRIMARY KEY, "aperture" real NULL, "shutter_speed" varchar(20) NULL, "shutter_speed_seconds" real NULL, "iso" integer NULL, "focal_length" real NULL, "focal_length_35mm" integer NULL, "exposure_compensation" real NULL, "flash_fired" bool NULL, "metering_mode" varchar(50) NULL, "white_balance" varchar(50) NULL, "camera_make" varchar(100) NULL, "camera_model" varchar(100) NULL, "lens_make" varchar(100) NULL, "lens_model" varchar(100) NULL, "serial_number" varchar(100) NULL, "width" integer NULL, "height" integer NULL, "orientation" integer NULL, "color_space" varchar(50) NULL, "bit_depth" integer NULL, "date_taken" datetime NULL, "date_taken_subsec" varchar(10) NULL, "date_modified" datetime NULL, "timezone_offset" varchar(10) NULL, "gps_latitude" real NULL, "gps_longitude" real NULL, "gps_altitude" real NULL, "location_country" varchar(100) NULL, "location_state" varchar(100) NULL, "location_city" varchar(100) NULL, "location_address" text NULL, "title" varchar(500) NULL, "caption" text NULL, "keywords" text NULL CHECK ((JSON_VALID("keywords") OR "keywords" IS NULL)), "rating" integer NULL, "copyright" text NULL, "creator" varchar(200) NULL, "source" varchar(20) NOT NULL, "raw_exif" text NULL CHECK ((JSON_VALID("raw_exif") OR "raw_exif" IS NULL)), "raw_xmp" text NULL CHECK ((JSON_VALID("raw_xmp") OR "raw_xmp" IS NULL)), "raw_iptc" text NULL CHECK ((JSON_VALID("raw_iptc") OR "raw_iptc" IS NULL)), "version" integer NOT NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "photo_id" char(32) NOT NULL UNIQUE REFERENCES "api_photo" ("id") DEFERRABLE INITIALLY DEFERRED);

CREATE TABLE "api_photo_stacks" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "photo_id" char(32) NOT NULL REFERENCES "api_photo" ("id") DEFERRABLE INITIALLY DEFERRED, "photostack_id" char(32) NOT NULL REFERENCES "api_photostack" ("id") DEFERRABLE INITIALLY DEFERRED);

CREATE TABLE "api_duplicate" ("id" char(32) NOT NULL PRIMARY KEY, "duplicate_type" varchar(20) NOT NULL, "review_status" varchar(20) NOT NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "reviewed_at" datetime NULL, "similarity_score" real NULL, "potential_savings" bigint NOT NULL, "trashed_count" integer NOT NULL, "note" text NULL, "kept_photo_id" char(32) NULL REFERENCES "api_photo" ("id") DEFERRABLE INITIALLY DEFERRED, "owner_id" integer NOT NULL REFERENCES "api_user" ("id") DEFERRABLE INITIALLY DEFERRED);

CREATE TABLE "api_photo_duplicates" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "photo_id" char(32) NOT NULL REFERENCES "api_photo" ("id") DEFERRABLE INITIALLY DEFERRED, "duplicate_id" char(32) NOT NULL REFERENCES "api_duplicate" ("id") DEFERRABLE INITIALLY DEFERRED);

CREATE TABLE "api_photostack" ("id" char(32) NOT NULL PRIMARY KEY, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "sequence_start" datetime NULL, "sequence_end" datetime NULL, "owner_id" integer NOT NULL REFERENCES "api_user" ("id") DEFERRABLE INITIALLY DEFERRED, "primary_photo_id" char(32) NULL REFERENCES "api_photo" ("id") DEFERRABLE INITIALLY DEFERRED, "stack_type" varchar(20) NOT NULL);

CREATE TABLE "api_file" ("hash" varchar(64) NOT NULL PRIMARY KEY, "type" integer unsigned NOT NULL CHECK ("type" >= 0), "missing" bool NOT NULL, "path" text NOT NULL UNIQUE);

CREATE TABLE "api_longrunningjob" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "job_type" integer unsigned NOT NULL CHECK ("job_type" >= 0), "finished" bool NOT NULL, "failed" bool NOT NULL, "job_id" varchar(36) NOT NULL UNIQUE, "queued_at" datetime NOT NULL, "started_at" datetime NULL, "finished_at" datetime NULL, "started_by_id" integer NOT NULL REFERENCES "api_user" ("id") DEFERRABLE INITIALLY DEFERRED, "progress_current" integer unsigned NOT NULL CHECK ("progress_current" >= 0), "progress_target" integer unsigned NOT NULL CHECK ("progress_target" >= 0), "progress_step" varchar(100) NULL, "result" text NULL CHECK ((JSON_VALID("result") OR "result" IS NULL)), "cancelled" bool NOT NULL);

CREATE TABLE "api_emailconfig" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "provider" varchar(32) NOT NULL, "from_email" varchar(255) NOT NULL, "host" varchar(255) NOT NULL, "port" integer unsigned NOT NULL CHECK ("port" >= 0), "use_tls" bool NOT NULL, "use_ssl" bool NOT NULL, "username" varchar(255) NOT NULL, "secret" BLOB NOT NULL);

CREATE TABLE "api_tag_photos" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "tag_id" integer NOT NULL REFERENCES "api_tag" ("id") DEFERRABLE INITIALLY DEFERRED, "photo_id" char(32) NOT NULL REFERENCES "api_photo" ("id") DEFERRABLE INITIALLY DEFERRED);

CREATE TABLE "api_photo" ("image_hash" varchar(64) NOT NULL, "added_on" datetime NOT NULL, "exif_gps_lat" real NULL, "exif_gps_lon" real NULL, "exif_timestamp" datetime NULL, "exif_json" text NULL CHECK ((JSON_VALID("exif_json") OR "exif_json" IS NULL)), "geolocation_json" text NULL CHECK ((JSON_VALID("geolocation_json") OR "geolocation_json" IS NULL)), "hidden" bool NOT NULL, "public" bool NOT NULL, "owner_id" integer NOT NULL REFERENCES "api_user" ("id") DEFERRABLE INITIALLY DEFERRED, "video" bool NOT NULL, "clip_embeddings_magnitude" real NULL, "rating" integer NOT NULL, "video_length" text NULL, "timestamp" datetime NULL, "size" bigint NOT NULL, "main_file_id" varchar(64) NULL REFERENCES "api_file" ("hash") DEFERRABLE INITIALLY DEFERRED, "last_modified" datetime NOT NULL, "in_trashcan" bool NOT NULL, "removed" bool NOT NULL, "clip_embeddings" text NULL CHECK ((JSON_VALID("clip_embeddings") OR "clip_embeddings" IS NULL)), "perceptual_hash" varchar(64) NULL, "exif_timestamp_subsec" varchar(10) NULL, "image_sequence_number" integer NULL, "id" char(32) NOT NULL PRIMARY KEY, "local_orientation" integer NOT NULL, "is_screenshot" bool NOT NULL, "is_document" bool NOT NULL, "category_source" varchar(8) NOT NULL);

CREATE TABLE "api_photo_ocr" ("photo_id" char(32) NOT NULL PRIMARY KEY REFERENCES "api_photo" ("id") DEFERRABLE INITIALLY DEFERRED, "text" text NULL, "blocks" text NOT NULL CHECK ((JSON_VALID("blocks") OR "blocks" IS NULL)), "engine" varchar(64) NOT NULL, "mean_confidence" real NULL, "text_area_fraction" real NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "source_width" integer unsigned NULL CHECK ("source_width" >= 0), "source_height" integer unsigned NULL CHECK ("source_height" >= 0));

CREATE TABLE "api_stackreview" ("decision" varchar(20) NOT NULL, "trashed_count" integer NOT NULL, "created_at" datetime NOT NULL, "reviewed_at" datetime NULL, "note" text NULL, "kept_photo_id" char(32) NULL REFERENCES "api_photo" ("id") DEFERRABLE INITIALLY DEFERRED, "reviewer_id" integer NOT NULL REFERENCES "api_user" ("id") DEFERRABLE INITIALLY DEFERRED, "stack_id" char(32) NOT NULL UNIQUE REFERENCES "api_photostack" ("id") DEFERRABLE INITIALLY DEFERRED, "uuid" char(32) NOT NULL UNIQUE, "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT);

CREATE TABLE "api_photoshare" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "enabled" bool NOT NULL, "slug" varchar(64) NULL UNIQUE, "created_at" datetime NOT NULL, "photo_id" char(32) NOT NULL UNIQUE REFERENCES "api_photo" ("id") DEFERRABLE INITIALLY DEFERRED);

CREATE TABLE "api_albumauto" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(512) NOT NULL, "timestamp" datetime NOT NULL, "created_on" datetime NOT NULL, "gps_lat" real NULL, "gps_lon" real NULL, "favorited" bool NOT NULL, "owner_id" integer NOT NULL REFERENCES "api_user" ("id") DEFERRABLE INITIALLY DEFERRED, "last_modified" datetime NOT NULL);

CREATE TABLE "api_albumplace" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(512) NOT NULL, "geolocation_level" integer NULL, "favorited" bool NOT NULL, "owner_id" integer NOT NULL REFERENCES "api_user" ("id") DEFERRABLE INITIALLY DEFERRED, "last_modified" datetime NOT NULL);

CREATE TABLE "api_albumthing" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(512) NOT NULL, "thing_type" varchar(512) NULL, "favorited" bool NOT NULL, "owner_id" integer NOT NULL REFERENCES "api_user" ("id") DEFERRABLE INITIALLY DEFERRED, "photo_count" integer NOT NULL, "last_modified" datetime NOT NULL, CONSTRAINT "unique AlbumThing" UNIQUE ("title", "thing_type", "owner_id"));

CREATE TABLE "api_albumuser" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "title" varchar(512) NOT NULL, "created_on" datetime NOT NULL, "favorited" bool NOT NULL, "owner_id" integer NOT NULL REFERENCES "api_user" ("id") DEFERRABLE INITIALLY DEFERRED, "cover_photo_id" char(32) NULL REFERENCES "api_photo" ("id") DEFERRABLE INITIALLY DEFERRED, "last_modified" datetime NOT NULL);

CREATE TABLE "api_person" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(128) NOT NULL, "kind" varchar(10) NOT NULL, "cover_photo_id" char(32) NULL REFERENCES "api_photo" ("id") DEFERRABLE INITIALLY DEFERRED, "cluster_owner_id" integer NULL REFERENCES "api_user" ("id") DEFERRABLE INITIALLY DEFERRED, "face_count" integer NOT NULL, "cover_face_id" integer NULL REFERENCES "api_face" ("id") DEFERRABLE INITIALLY DEFERRED, "last_modified" datetime NOT NULL);

CREATE TABLE "api_tag" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(512) NOT NULL, "photo_count" integer NOT NULL, "owner_id" integer NOT NULL REFERENCES "api_user" ("id") DEFERRABLE INITIALLY DEFERRED, "last_modified" datetime NOT NULL, CONSTRAINT "unique Tag" UNIQUE ("name", "owner_id"));

CREATE TABLE "api_user" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "first_name" varchar(150) NOT NULL, "last_name" varchar(150) NOT NULL, "email" varchar(254) NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "date_joined" datetime NOT NULL, "scan_directory" varchar(512) NOT NULL, "avatar" varchar(100) NULL, "nextcloud_server_address" varchar(200) NOT NULL, "nextcloud_username" varchar(64) NOT NULL, "nextcloud_app_password" BLOB NOT NULL, "nextcloud_scan_directory" varchar(512) NOT NULL, "confidence" real NOT NULL, "semantic_search_topk" integer NOT NULL, "favorite_min_rating" integer NOT NULL, "image_scale" real NOT NULL, "save_metadata_to_disk" text NOT NULL, "transcode_videos" bool NOT NULL, "datetime_rules" text NOT NULL CHECK ((JSON_VALID("datetime_rules") OR "datetime_rules" IS NULL)), "default_timezone" text NOT NULL, "confidence_person" real NOT NULL, "public_sharing" bool NOT NULL, "confidence_unknown_face" real NOT NULL, "face_recognition_model" text NOT NULL, "min_cluster_size" integer NOT NULL, "cluster_selection_epsilon" real NOT NULL, "min_samples" integer NOT NULL, "llm_settings" text NOT NULL CHECK ((JSON_VALID("llm_settings") OR "llm_settings" IS NULL)), "text_alignment" text NOT NULL, "header_size" text NOT NULL, "skip_raw_files" bool NOT NULL, "slideshow_interval" integer NOT NULL, "duplicate_clear_existing" bool NOT NULL, "duplicate_sensitivity" text NOT NULL, "burst_detection_rules" text NOT NULL CHECK ((JSON_VALID("burst_detection_rules") OR "burst_detection_rules" IS NULL)), "stack_raw_jpeg" bool NOT NULL, "public_sharing_defaults" text NOT NULL CHECK ((JSON_VALID("public_sharing_defaults") OR "public_sharing_defaults" IS NULL)), "save_face_tags_to_disk" bool NOT NULL, "last_modified" datetime NOT NULL);

CREATE TABLE "api_deletionlog" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "entity" varchar(32) NOT NULL, "entity_id" varchar(64) NOT NULL, "deleted_at" datetime NOT NULL, "owner_id" integer NOT NULL REFERENCES "api_user" ("id") DEFERRABLE INITIALLY DEFERRED);

CREATE TABLE "api_photo_shared_to" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "photo_id" char(32) NOT NULL REFERENCES "api_photo" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" integer NOT NULL REFERENCES "api_user" ("id") DEFERRABLE INITIALLY DEFERRED);

CREATE TABLE "api_photo_files" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "photo_id" char(32) NOT NULL REFERENCES "api_photo" ("id") DEFERRABLE INITIALLY DEFERRED, "file_id" varchar(64) NOT NULL REFERENCES "api_file" ("hash") DEFERRABLE INITIALLY DEFERRED);

CREATE TABLE "api_face" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "image" varchar(100) NULL, "cluster_probability" real NOT NULL, "location_top" integer NOT NULL, "location_bottom" integer NOT NULL, "location_left" integer NOT NULL, "location_right" integer NOT NULL, "encoding" text NOT NULL, "person_id" integer NULL REFERENCES "api_person" ("id") DEFERRABLE INITIALLY DEFERRED, "photo_id" char(32) NULL REFERENCES "api_photo" ("id") DEFERRABLE INITIALLY DEFERRED, "cluster_id" integer NULL REFERENCES "api_cluster" ("id") DEFERRABLE INITIALLY DEFERRED, "classification_probability" real NOT NULL, "deleted" bool NOT NULL, "classification_person_id" integer NULL REFERENCES "api_person" ("id") DEFERRABLE INITIALLY DEFERRED, "cluster_person_id" integer NULL REFERENCES "api_person" ("id") DEFERRABLE INITIALLY DEFERRED);

CREATE TABLE "api_albumdate_photos" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "albumdate_id" integer NOT NULL REFERENCES "api_albumdate" ("id") DEFERRABLE INITIALLY DEFERRED, "photo_id" char(32) NOT NULL REFERENCES "api_photo" ("id") DEFERRABLE INITIALLY DEFERRED);

CREATE TABLE "api_thumbnail" ("photo_id" char(32) NOT NULL PRIMARY KEY REFERENCES "api_photo" ("id") DEFERRABLE INITIALLY DEFERRED, "thumbnail_big" varchar(100) NOT NULL, "square_thumbnail" varchar(100) NOT NULL, "square_thumbnail_small" varchar(100) NOT NULL, "aspect_ratio" real NULL, "dominant_color" text NULL);

CREATE TABLE "api_albumthing_photos" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "albumthing_id" integer NOT NULL REFERENCES "api_albumthing" ("id") DEFERRABLE INITIALLY DEFERRED, "photo_id" char(32) NOT NULL REFERENCES "api_photo" ("id") DEFERRABLE INITIALLY DEFERRED);

CREATE TABLE "api_albumthing_cover_photos" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "albumthing_id" integer NOT NULL REFERENCES "api_albumthing" ("id") DEFERRABLE INITIALLY DEFERRED, "photo_id" char(32) NOT NULL REFERENCES "api_photo" ("id") DEFERRABLE INITIALLY DEFERRED);

CREATE TABLE "api_albumauto_photos" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "albumauto_id" integer NOT NULL REFERENCES "api_albumauto" ("id") DEFERRABLE INITIALLY DEFERRED, "photo_id" char(32) NOT NULL REFERENCES "api_photo" ("id") DEFERRABLE INITIALLY DEFERRED);

CREATE TABLE "api_albumplace_photos" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "albumplace_id" integer NOT NULL REFERENCES "api_albumplace" ("id") DEFERRABLE INITIALLY DEFERRED, "photo_id" char(32) NOT NULL REFERENCES "api_photo" ("id") DEFERRABLE INITIALLY DEFERRED);

CREATE TABLE "api_photo_search" ("photo_id" char(32) NOT NULL PRIMARY KEY REFERENCES "api_photo" ("id") DEFERRABLE INITIALLY DEFERRED, "search_captions" text NULL, "search_location" text NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL);

CREATE TABLE "api_photo_caption" ("photo_id" char(32) NOT NULL PRIMARY KEY REFERENCES "api_photo" ("id") DEFERRABLE INITIALLY DEFERRED, "captions_json" text NULL CHECK ((JSON_VALID("captions_json") OR "captions_json" IS NULL)), "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL);

CREATE TABLE "api_albumuser_photos" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "albumuser_id" integer NOT NULL REFERENCES "api_albumuser" ("id") DEFERRABLE INITIALLY DEFERRED, "photo_id" char(32) NOT NULL REFERENCES "api_photo" ("id") DEFERRABLE INITIALLY DEFERRED);

CREATE TABLE "chunked_upload_chunkedupload" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "upload_id" varchar(32) NOT NULL UNIQUE, "file" varchar(255) NOT NULL, "filename" varchar(255) NOT NULL, "offset" bigint NOT NULL, "created_on" datetime NOT NULL, "status" smallint unsigned NOT NULL CHECK ("status" >= 0), "completed_on" datetime NULL, "user_id" integer NULL REFERENCES "api_user" ("id") DEFERRABLE INITIALLY DEFERRED);

CREATE INDEX "api_cluster_person_id_de1e4b3c" ON "api_cluster" ("person_id");

CREATE INDEX "api_cluster_owner_id_ddf57161" ON "api_cluster" ("owner_id");

CREATE UNIQUE INDEX "api_file_embedded_media_from_file_id_to_file_id_dda3a651_uniq" ON "api_file_embedded_media" ("from_file_id", "to_file_id");

CREATE INDEX "api_file_embedded_media_from_file_id_9cd74d0d" ON "api_file_embedded_media" ("from_file_id");

CREATE INDEX "api_file_embedded_media_to_file_id_69f18a1c" ON "api_file_embedded_media" ("to_file_id");

CREATE UNIQUE INDEX "api_albumdate_date_owner_id_5ba3d470_uniq" ON "api_albumdate" ("date", "owner_id");

CREATE INDEX "api_albumdate_title_c0a886cc" ON "api_albumdate" ("title");

CREATE INDEX "api_albumdate_date_b825aef0" ON "api_albumdate" ("date");

CREATE INDEX "api_albumdate_favorited_9f3d4007" ON "api_albumdate" ("favorited");

CREATE INDEX "api_albumdate_location_dbba885f" ON "api_albumdate" ("location");

CREATE INDEX "api_albumdate_owner_id_2745f84a" ON "api_albumdate" ("owner_id");

CREATE UNIQUE INDEX "api_albumdate_shared_to_albumdate_id_user_id_7eb2d2bf_uniq" ON "api_albumdate_shared_to" ("albumdate_id", "user_id");

CREATE INDEX "api_albumdate_shared_to_albumdate_id_6d32c8dc" ON "api_albumdate_shared_to" ("albumdate_id");

CREATE INDEX "api_albumdate_shared_to_user_id_9ccf440e" ON "api_albumdate_shared_to" ("user_id");

CREATE UNIQUE INDEX "api_albumthing_shared_to_albumthing_id_user_id_05b7dbd1_uniq" ON "api_albumthing_shared_to" ("albumthing_id", "user_id");

CREATE INDEX "api_albumthing_shared_to_albumthing_id_b81ac20a" ON "api_albumthing_shared_to" ("albumthing_id");

CREATE INDEX "api_albumthing_shared_to_user_id_40c200a0" ON "api_albumthing_shared_to" ("user_id");

CREATE UNIQUE INDEX "api_albumauto_shared_to_albumauto_id_user_id_332148f8_uniq" ON "api_albumauto_shared_to" ("albumauto_id", "user_id");

CREATE INDEX "api_albumauto_shared_to_albumauto_id_94c13ddb" ON "api_albumauto_shared_to" ("albumauto_id");

CREATE INDEX "api_albumauto_shared_to_user_id_cf09f962" ON "api_albumauto_shared_to" ("user_id");

CREATE UNIQUE INDEX "api_albumplace_shared_to_albumplace_id_user_id_878b44ef_uniq" ON "api_albumplace_shared_to" ("albumplace_id", "user_id");

CREATE INDEX "api_albumplace_shared_to_albumplace_id_1c57a597" ON "api_albumplace_shared_to" ("albumplace_id");

CREATE INDEX "api_albumplace_shared_to_user_id_82c38c75" ON "api_albumplace_shared_to" ("user_id");

CREATE UNIQUE INDEX "api_albumuser_shared_to_albumuser_id_user_id_3c6a4938_uniq" ON "api_albumuser_shared_to" ("albumuser_id", "user_id");

CREATE INDEX "api_albumuser_shared_to_albumuser_id_037fbb43" ON "api_albumuser_shared_to" ("albumuser_id");

CREATE INDEX "api_albumuser_shared_to_user_id_60ab3643" ON "api_albumuser_shared_to" ("user_id");

CREATE INDEX "api_albumusershare_enabled_a7f334cf" ON "api_albumusershare" ("enabled");

CREATE INDEX "api_albumusershare_expires_at_2a6e99b3" ON "api_albumusershare" ("expires_at");

CREATE INDEX "api_metadataedit_photo_id_38524cb3" ON "api_metadataedit" ("photo_id");

CREATE INDEX "api_metadataedit_user_id_83a820d9" ON "api_metadataedit" ("user_id");

CREATE INDEX "api_metadatafile_photo_id_76028904" ON "api_metadatafile" ("photo_id");

CREATE INDEX "api_photometadata_aperture_dc8a65b2" ON "api_photometadata" ("aperture");

CREATE INDEX "api_photometadata_iso_aa268c5e" ON "api_photometadata" ("iso");

CREATE INDEX "api_photometadata_camera_make_c682ef26" ON "api_photometadata" ("camera_make");

CREATE INDEX "api_photometadata_camera_model_f21bb3a4" ON "api_photometadata" ("camera_model");

CREATE INDEX "api_photometadata_lens_model_42c78a22" ON "api_photometadata" ("lens_model");

CREATE INDEX "api_photometadata_date_taken_01f75f9f" ON "api_photometadata" ("date_taken");

CREATE INDEX "api_photometadata_gps_latitude_208b23c0" ON "api_photometadata" ("gps_latitude");

CREATE INDEX "api_photometadata_gps_longitude_58c79d9d" ON "api_photometadata" ("gps_longitude");

CREATE INDEX "api_photometadata_location_country_e2b954aa" ON "api_photometadata" ("location_country");

CREATE INDEX "api_photometadata_location_city_ef02387c" ON "api_photometadata" ("location_city");

CREATE INDEX "api_photometadata_rating_4bc76fc1" ON "api_photometadata" ("rating");

CREATE INDEX "api_metadat_photo_i_21e478_idx" ON "api_metadataedit" ("photo_id", "created_at" DESC);

CREATE INDEX "api_photome_camera__361eac_idx" ON "api_photometadata" ("camera_make", "camera_model");

CREATE INDEX "api_photome_date_ta_35e59b_idx" ON "api_photometadata" ("date_taken");

CREATE INDEX "api_photome_locatio_1ca8bb_idx" ON "api_photometadata" ("location_country", "location_city");

CREATE UNIQUE INDEX "api_photo_stacks_photo_id_photostack_id_237b9c5b_uniq" ON "api_photo_stacks" ("photo_id", "photostack_id");

CREATE INDEX "api_photo_stacks_photo_id_db985d09" ON "api_photo_stacks" ("photo_id");

CREATE INDEX "api_photo_stacks_photostack_id_dd4eef21" ON "api_photo_stacks" ("photostack_id");

CREATE INDEX "api_duplica_owner_i_78a3a4_idx" ON "api_duplicate" ("owner_id", "duplicate_type");

CREATE INDEX "api_duplica_owner_i_039fa3_idx" ON "api_duplicate" ("owner_id", "review_status");

CREATE INDEX "api_duplicate_duplicate_type_155b26e2" ON "api_duplicate" ("duplicate_type");

CREATE INDEX "api_duplicate_review_status_85cc6bfd" ON "api_duplicate" ("review_status");

CREATE INDEX "api_duplicate_kept_photo_id_e0c33ed4" ON "api_duplicate" ("kept_photo_id");

CREATE INDEX "api_duplicate_owner_id_3d0c7327" ON "api_duplicate" ("owner_id");

CREATE UNIQUE INDEX "api_photo_duplicates_photo_id_duplicate_id_9dd9906e_uniq" ON "api_photo_duplicates" ("photo_id", "duplicate_id");

CREATE INDEX "api_photo_duplicates_photo_id_e89217df" ON "api_photo_duplicates" ("photo_id");

CREATE INDEX "api_photo_duplicates_duplicate_id_f06a9493" ON "api_photo_duplicates" ("duplicate_id");

CREATE INDEX "api_photostack_owner_id_56d8148c" ON "api_photostack" ("owner_id");

CREATE INDEX "api_photostack_primary_photo_id_a2e9fc96" ON "api_photostack" ("primary_photo_id");

CREATE INDEX "api_photostack_stack_type_979b3dfd" ON "api_photostack" ("stack_type");

CREATE INDEX "api_photost_owner_i_40a369_idx" ON "api_photostack" ("owner_id", "stack_type");

CREATE INDEX "api_longrunningjob_started_by_id_acef418a" ON "api_longrunningjob" ("started_by_id");

CREATE UNIQUE INDEX "api_tag_photos_tag_id_photo_id_cf87bcf0_uniq" ON "api_tag_photos" ("tag_id", "photo_id");

CREATE INDEX "api_tag_photos_tag_id_bca93ec5" ON "api_tag_photos" ("tag_id");

CREATE INDEX "api_tag_photos_photo_id_1a9bb7a5" ON "api_tag_photos" ("photo_id");

CREATE INDEX "api_photo_image_hash_6b828f4d" ON "api_photo" ("image_hash");

CREATE INDEX "api_photo_added_on_ababa57d" ON "api_photo" ("added_on");

CREATE INDEX "api_photo_exif_timestamp_3c113e34" ON "api_photo" ("exif_timestamp");

CREATE INDEX "api_photo_geolocation_json_dc1b353e" ON "api_photo" ("geolocation_json");

CREATE INDEX "api_photo_hidden_59a5d521" ON "api_photo" ("hidden");

CREATE INDEX "api_photo_public_d9bcd839" ON "api_photo" ("public");

CREATE INDEX "api_photo_owner_id_234b5551" ON "api_photo" ("owner_id");

CREATE INDEX "api_photo_rating_53606e2c" ON "api_photo" ("rating");

CREATE INDEX "api_photo_timestamp_92a676d4" ON "api_photo" ("timestamp");

CREATE INDEX "api_photo_main_file_id_453ba4cc" ON "api_photo" ("main_file_id");

CREATE INDEX "api_photo_in_trashcan_516d54a0" ON "api_photo" ("in_trashcan");

CREATE INDEX "api_photo_removed_50380583" ON "api_photo" ("removed");

CREATE INDEX "api_photo_perceptual_hash_1076b9f8" ON "api_photo" ("perceptual_hash");

CREATE INDEX "api_photo_is_screenshot_80bd33f2" ON "api_photo" ("is_screenshot");

CREATE INDEX "api_photo_is_document_89ef7db6" ON "api_photo" ("is_document");

CREATE INDEX "api_stackreview_decision_58df030b" ON "api_stackreview" ("decision");

CREATE INDEX "api_stackreview_kept_photo_id_06685c2e" ON "api_stackreview" ("kept_photo_id");

CREATE INDEX "api_stackreview_reviewer_id_9a64c2f8" ON "api_stackreview" ("reviewer_id");

CREATE INDEX "api_stackre_reviewe_48380f_idx" ON "api_stackreview" ("reviewer_id", "decision");

CREATE INDEX "api_photoshare_enabled_20ebda70" ON "api_photoshare" ("enabled");

CREATE UNIQUE INDEX "api_albumauto_timestamp_owner_id_314a1d7f_uniq" ON "api_albumauto" ("timestamp", "owner_id");

CREATE INDEX "api_albumauto_timestamp_584f1589" ON "api_albumauto" ("timestamp");

CREATE INDEX "api_albumauto_created_on_0c5c92b6" ON "api_albumauto" ("created_on");

CREATE INDEX "api_albumauto_favorited_68743c7f" ON "api_albumauto" ("favorited");

CREATE INDEX "api_albumauto_owner_id_e83d8f88" ON "api_albumauto" ("owner_id");

CREATE INDEX "api_albumauto_last_modified_97dd0117" ON "api_albumauto" ("last_modified");

CREATE UNIQUE INDEX "api_albumplace_title_owner_id_851514f9_uniq" ON "api_albumplace" ("title", "owner_id");

CREATE INDEX "api_albumplace_title_6cafeb2d" ON "api_albumplace" ("title");

CREATE INDEX "api_albumplace_geolocation_level_35fbd31f" ON "api_albumplace" ("geolocation_level");

CREATE INDEX "api_albumplace_favorited_ddb4a4c3" ON "api_albumplace" ("favorited");

CREATE INDEX "api_albumplace_owner_id_6bd352e3" ON "api_albumplace" ("owner_id");

CREATE INDEX "api_albumplace_last_modified_09b846bd" ON "api_albumplace" ("last_modified");

CREATE INDEX "api_albumthing_title_e9b82e55" ON "api_albumthing" ("title");

CREATE INDEX "api_albumthing_thing_type_924227a6" ON "api_albumthing" ("thing_type");

CREATE INDEX "api_albumthing_favorited_70dc6840" ON "api_albumthing" ("favorited");

CREATE INDEX "api_albumthing_owner_id_b61d1b00" ON "api_albumthing" ("owner_id");

CREATE INDEX "api_albumthing_last_modified_6aab255b" ON "api_albumthing" ("last_modified");

CREATE UNIQUE INDEX "api_albumuser_title_owner_id_ef2e4db4_uniq" ON "api_albumuser" ("title", "owner_id");

CREATE INDEX "api_albumuser_created_on_0807bc0f" ON "api_albumuser" ("created_on");

CREATE INDEX "api_albumuser_favorited_15de9e16" ON "api_albumuser" ("favorited");

CREATE INDEX "api_albumuser_owner_id_df3b5510" ON "api_albumuser" ("owner_id");

CREATE INDEX "api_albumuser_cover_photo_id_69b304ac" ON "api_albumuser" ("cover_photo_id");

CREATE INDEX "api_albumuser_last_modified_fa65eb43" ON "api_albumuser" ("last_modified");

CREATE INDEX "api_person_name_8e1ce669" ON "api_person" ("name");

CREATE INDEX "api_person_cover_photo_id_e0d8a6ab" ON "api_person" ("cover_photo_id");

CREATE INDEX "api_person_cluster_owner_id_90df41de" ON "api_person" ("cluster_owner_id");

CREATE INDEX "api_person_cover_face_id_bdd48874" ON "api_person" ("cover_face_id");

CREATE INDEX "api_person_last_modified_c4a91103" ON "api_person" ("last_modified");

CREATE INDEX "api_tag_name_e0f7a95d" ON "api_tag" ("name");

CREATE INDEX "api_tag_owner_id_18caa483" ON "api_tag" ("owner_id");

CREATE INDEX "api_tag_last_modified_6d2b89ff" ON "api_tag" ("last_modified");

CREATE INDEX "api_user_scan_directory_ad54b748" ON "api_user" ("scan_directory");

CREATE INDEX "api_user_nextcloud_scan_directory_a85dc569" ON "api_user" ("nextcloud_scan_directory");

CREATE INDEX "api_user_confidence_4ccde6b4" ON "api_user" ("confidence");

CREATE INDEX "api_user_favorite_min_rating_3cb1cf14" ON "api_user" ("favorite_min_rating");

CREATE INDEX "api_user_last_modified_e2efd2d6" ON "api_user" ("last_modified");

CREATE INDEX "photo_sync_keyset_idx" ON "api_photo" ("last_modified", "id");

CREATE INDEX "api_deletionlog_entity_0bdb6728" ON "api_deletionlog" ("entity");

CREATE INDEX "api_deletionlog_deleted_at_0d4cb74b" ON "api_deletionlog" ("deleted_at");

CREATE INDEX "api_deletionlog_owner_id_fe3fb028" ON "api_deletionlog" ("owner_id");

CREATE INDEX "deletionlog_scope_idx" ON "api_deletionlog" ("owner_id", "entity", "deleted_at");

CREATE UNIQUE INDEX "api_photo_shared_to_photo_id_user_id_d9c7c4a1_uniq" ON "api_photo_shared_to" ("photo_id", "user_id");

CREATE INDEX "api_photo_shared_to_photo_id_852923c7" ON "api_photo_shared_to" ("photo_id");

CREATE INDEX "api_photo_shared_to_user_id_0407baf2" ON "api_photo_shared_to" ("user_id");

CREATE UNIQUE INDEX "api_photo_files_photo_id_file_id_0cd01909_uniq" ON "api_photo_files" ("photo_id", "file_id");

CREATE INDEX "api_photo_files_photo_id_f4365127" ON "api_photo_files" ("photo_id");

CREATE INDEX "api_photo_files_file_id_b6d5e335" ON "api_photo_files" ("file_id");

CREATE INDEX "api_face_cluster_probability_89b3b2e2" ON "api_face" ("cluster_probability");

CREATE INDEX "api_face_person_id_6a0347bd" ON "api_face" ("person_id");

CREATE INDEX "api_face_photo_id_6f997226" ON "api_face" ("photo_id");

CREATE INDEX "api_face_cluster_id_7cc7025a" ON "api_face" ("cluster_id");

CREATE INDEX "api_face_classification_probability_688e8040" ON "api_face" ("classification_probability");

CREATE INDEX "api_face_classification_person_id_98d44049" ON "api_face" ("classification_person_id");

CREATE INDEX "api_face_cluster_person_id_0a0b4811" ON "api_face" ("cluster_person_id");

CREATE UNIQUE INDEX "api_albumdate_photos_albumdate_id_photo_id_5c0ca0f9_uniq" ON "api_albumdate_photos" ("albumdate_id", "photo_id");

CREATE INDEX "api_albumdate_photos_albumdate_id_cd458c5d" ON "api_albumdate_photos" ("albumdate_id");

CREATE INDEX "api_albumdate_photos_photo_id_26095959" ON "api_albumdate_photos" ("photo_id");

CREATE UNIQUE INDEX "api_albumthing_photos_albumthing_id_photo_id_1cc34324_uniq" ON "api_albumthing_photos" ("albumthing_id", "photo_id");

CREATE INDEX "api_albumthing_photos_albumthing_id_00fcb0f3" ON "api_albumthing_photos" ("albumthing_id");

CREATE INDEX "api_albumthing_photos_photo_id_d0832fc3" ON "api_albumthing_photos" ("photo_id");

CREATE UNIQUE INDEX "api_albumthing_cover_photos_albumthing_id_photo_id_86f2debc_uniq" ON "api_albumthing_cover_photos" ("albumthing_id", "photo_id");

CREATE INDEX "api_albumthing_cover_photos_albumthing_id_aa548eb5" ON "api_albumthing_cover_photos" ("albumthing_id");

CREATE INDEX "api_albumthing_cover_photos_photo_id_ae113997" ON "api_albumthing_cover_photos" ("photo_id");

CREATE UNIQUE INDEX "api_albumauto_photos_albumauto_id_photo_id_a8d355b1_uniq" ON "api_albumauto_photos" ("albumauto_id", "photo_id");

CREATE INDEX "api_albumauto_photos_albumauto_id_86a09378" ON "api_albumauto_photos" ("albumauto_id");

CREATE INDEX "api_albumauto_photos_photo_id_3320c2f0" ON "api_albumauto_photos" ("photo_id");

CREATE UNIQUE INDEX "api_albumplace_photos_albumplace_id_photo_id_8340aa63_uniq" ON "api_albumplace_photos" ("albumplace_id", "photo_id");

CREATE INDEX "api_albumplace_photos_albumplace_id_e0d81074" ON "api_albumplace_photos" ("albumplace_id");

CREATE INDEX "api_albumplace_photos_photo_id_8fd88190" ON "api_albumplace_photos" ("photo_id");

CREATE INDEX "api_photo_search_search_captions_929fb6aa" ON "api_photo_search" ("search_captions");

CREATE INDEX "api_photo_search_search_location_b864ad60" ON "api_photo_search" ("search_location");

CREATE INDEX "api_photo_caption_captions_json_70c46fb8" ON "api_photo_caption" ("captions_json");

CREATE UNIQUE INDEX "api_albumuser_photos_albumuser_id_photo_id_00091848_uniq" ON "api_albumuser_photos" ("albumuser_id", "photo_id");

CREATE INDEX "api_albumuser_photos_albumuser_id_80614a80" ON "api_albumuser_photos" ("albumuser_id");

CREATE INDEX "api_albumuser_photos_photo_id_b9df1b14" ON "api_albumuser_photos" ("photo_id");

CREATE INDEX "chunked_upload_chunkedupload_user_id_70ff6dbf" ON "chunked_upload_chunkedupload" ("user_id");
