"""
PhotoMetadata and MetadataFile models for structured metadata handling.

This module provides proper models for:
1. PhotoMetadata - Structured EXIF/metadata extracted from photos
2. MetadataFile - XMP sidecars and other metadata files

Benefits over current approach:
- Typed fields instead of JSON blob (exif_json)
- Proper foreign key relationships
- Versioning for metadata changes
- Support for multiple metadata sources (embedded, sidecar, user-edited)
- Clear separation between camera metadata and derived metadata
"""

import numbers
import uuid
from fractions import Fraction

from django.db import models

from api import util
from api.metadata.reader import get_metadata
from api.metadata.tags import Tags
from api.models.tag import link_tags_from_keywords
from api.models.user import User, get_deleted_user

# The value names below line up positionally with EXIF_TAGS: get_metadata returns
# one value per requested tag, in the order the tags were asked for.
EXIF_VALUE_NAMES = (
    "size",
    "fstop",
    "focal_length",
    "iso",
    "shutter_speed",
    "camera",
    "lens",
    "width",
    "height",
    "focal_length_35mm",
    "subject_distance",
    "digital_zoom_ratio",
    "video_length",
    "rating",
    "subsec_time_original",
    "image_number",
    "xmp_subject",
    "iptc_keywords",
    "xmp_description",
    "xmp_description_any_language",
)

EXIF_TAGS = [
    Tags.FILE_SIZE,
    Tags.FSTOP,
    Tags.FOCAL_LENGTH,
    Tags.ISO,
    Tags.EXPOSURE_TIME,
    Tags.CAMERA,
    Tags.LENS,
    Tags.IMAGE_WIDTH,
    Tags.IMAGE_HEIGHT,
    Tags.FOCAL_LENGTH_35MM,
    Tags.SUBJECT_DISTANCE,
    Tags.DIGITAL_ZOOM_RATIO,
    Tags.QUICKTIME_DURATION,
    Tags.RATING,
    Tags.SUBSEC_TIME_ORIGINAL,
    Tags.IMAGE_NUMBER,
    Tags.SUBJECT,
    Tags.IPTC_KEYWORDS,
    Tags.DESCRIPTION,
    Tags.DESCRIPTION_ANY_LANGUAGE,
]

# Key in PhotoCaption.captions_json remembering the description last imported
# from the file, so a rescan can tell "already imported" (and possibly edited
# or cleared by the user since) from "the file has a new description".
IMPORTED_DESCRIPTION_KEY = "imported_description"


def _assign_nonzero_number(target, field, value):
    if value and isinstance(value, numbers.Number):
        setattr(target, field, value)


def _assign_number(target, field, value):
    if value is not None and isinstance(value, numbers.Number):
        setattr(target, field, value)


def _assign_string(target, field, value):
    if value and isinstance(value, str):
        setattr(target, field, value)


def _text_value(value):
    """A free-text tag value as a stripped string, or None when empty.

    ExifTool's JSON output turns a text value that looks like a number into a
    number (a description of "2024" comes back as the int 2024), so numbers are
    turned back into text rather than dropped. Anything else is ignored.
    """
    if isinstance(value, bool):
        return None
    if isinstance(value, numbers.Number):
        value = str(value)
    if not isinstance(value, str):
        return None
    return value.strip() or None


def _description(values):
    """The file's description: x-default first, else any language entry."""
    return _text_value(values.get("xmp_description")) or _text_value(
        values.get("xmp_description_any_language")
    )


def _merge_keywords(*values):
    """Merge XMP:Subject / IPTC:Keywords entries, deduplicated and sorted."""
    merged = set()
    for value in values:
        if isinstance(value, list):
            merged.update(value)
        elif isinstance(value, str) and value:
            merged.add(value)
    return sorted(merged)


class MetadataFile(models.Model):
    """
    Represents a metadata sidecar file (XMP, JSON, etc.) associated with a photo.

    A photo can have multiple metadata files:
    - XMP sidecar from camera/software
    - Adobe Lightroom .xmp
    - Darktable .xmp
    - User-created metadata file
    """

    class FileType(models.TextChoices):
        XMP = "xmp", "XMP Sidecar"
        JSON = "json", "JSON Metadata"
        EXIF = "exif", "EXIF Extract"
        OTHER = "other", "Other"

    class Source(models.TextChoices):
        # Sidecar that came with the photo (same directory)
        ORIGINAL = "original", "Original Sidecar"
        # Generated by photo editing software
        SOFTWARE = "software", "Software Generated"
        # Created by LibrePhotos
        LIBREPHOTOS = "librephotos", "LibrePhotos Generated"
        # User manually created/uploaded
        USER = "user", "User Created"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    # Link to the File model for actual file storage
    file = models.OneToOneField(
        "File",
        on_delete=models.CASCADE,
        related_name="metadata_info",
    )

    # The photo this metadata belongs to
    photo = models.ForeignKey(
        "Photo",
        on_delete=models.CASCADE,
        related_name="metadata_files",
    )

    file_type = models.CharField(
        max_length=10,
        choices=FileType.choices,
        default=FileType.XMP,
    )

    source = models.CharField(
        max_length=20,
        choices=Source.choices,
        default=Source.ORIGINAL,
    )

    # Priority for metadata resolution (higher = more authoritative)
    # User edits > Software sidecars > Original sidecars > Embedded
    priority = models.IntegerField(default=0)

    # Software that created this file (if known)
    creator_software = models.CharField(max_length=100, blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-priority", "-updated_at"]
        verbose_name = "Metadata File"
        verbose_name_plural = "Metadata Files"

    def __str__(self):
        return f"{self.file_type} sidecar for {self.photo_id}"


class PhotoMetadata(models.Model):
    """
    Structured metadata for a photo.

    This model stores extracted and computed metadata in typed fields,
    making it queryable and more maintainable than a JSON blob.

    Metadata Sources (in priority order):
    1. User edits (highest priority)
    2. XMP sidecar files
    3. Embedded EXIF/IPTC/XMP
    4. Computed/derived values (lowest priority)
    """

    class Source(models.TextChoices):
        # Embedded in the file (EXIF, IPTC, embedded XMP)
        EMBEDDED = "embedded", "Embedded in File"
        # From XMP sidecar file
        SIDECAR = "sidecar", "XMP Sidecar"
        # User manually edited
        USER_EDIT = "user_edit", "User Edit"
        # Computed by LibrePhotos (AI, geocoding, etc.)
        COMPUTED = "computed", "Computed"

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    photo = models.OneToOneField(
        "Photo",
        on_delete=models.CASCADE,
        related_name="metadata",
    )

    # ==================== Camera Settings ====================
    # Aperture (f-stop), e.g., 2.8
    aperture = models.FloatField(null=True, blank=True, db_index=True)

    # Shutter speed as a string fraction, e.g., "1/250"
    shutter_speed = models.CharField(max_length=20, null=True, blank=True)

    # Shutter speed in seconds (for queries), e.g., 0.004
    shutter_speed_seconds = models.FloatField(null=True, blank=True)

    # ISO sensitivity
    iso = models.IntegerField(null=True, blank=True, db_index=True)

    # Focal length in mm
    focal_length = models.FloatField(null=True, blank=True)

    # 35mm equivalent focal length
    focal_length_35mm = models.IntegerField(null=True, blank=True)

    # Exposure compensation in EV
    exposure_compensation = models.FloatField(null=True, blank=True)

    # Flash fired
    flash_fired = models.BooleanField(null=True, blank=True)

    # Metering mode
    metering_mode = models.CharField(max_length=50, null=True, blank=True)

    # White balance
    white_balance = models.CharField(max_length=50, null=True, blank=True)

    # ==================== Camera/Lens Info ====================
    camera_make = models.CharField(max_length=100, null=True, blank=True, db_index=True)
    camera_model = models.CharField(
        max_length=100, null=True, blank=True, db_index=True
    )
    lens_make = models.CharField(max_length=100, null=True, blank=True)
    lens_model = models.CharField(max_length=100, null=True, blank=True, db_index=True)
    serial_number = models.CharField(max_length=100, null=True, blank=True)

    # ==================== Image Properties ====================
    width = models.IntegerField(null=True, blank=True)
    height = models.IntegerField(null=True, blank=True)
    orientation = models.IntegerField(null=True, blank=True)
    color_space = models.CharField(max_length=50, null=True, blank=True)
    bit_depth = models.IntegerField(null=True, blank=True)

    # ==================== Timestamps ====================
    # Original capture time from EXIF
    date_taken = models.DateTimeField(null=True, blank=True, db_index=True)

    # Sub-second precision (from EXIF:SubSecTimeOriginal)
    date_taken_subsec = models.CharField(max_length=10, null=True, blank=True)

    # When the file was last modified
    date_modified = models.DateTimeField(null=True, blank=True)

    # Timezone offset if available
    timezone_offset = models.CharField(max_length=10, null=True, blank=True)

    # ==================== Location ====================
    gps_latitude = models.FloatField(null=True, blank=True, db_index=True)
    gps_longitude = models.FloatField(null=True, blank=True, db_index=True)
    gps_altitude = models.FloatField(null=True, blank=True)

    # Location from reverse geocoding
    location_country = models.CharField(
        max_length=100, null=True, blank=True, db_index=True
    )
    location_state = models.CharField(max_length=100, null=True, blank=True)
    location_city = models.CharField(
        max_length=100, null=True, blank=True, db_index=True
    )
    location_address = models.TextField(null=True, blank=True)

    # ==================== Content Description ====================
    title = models.CharField(max_length=500, null=True, blank=True)
    caption = models.TextField(null=True, blank=True)
    keywords = models.JSONField(null=True, blank=True)  # List of strings

    # Rating (0-5 stars)
    rating = models.IntegerField(null=True, blank=True, db_index=True)

    # Copyright info
    copyright = models.TextField(null=True, blank=True)
    creator = models.CharField(max_length=200, null=True, blank=True)

    # ==================== Tracking ====================
    # Which source this metadata came from
    source = models.CharField(
        max_length=20,
        choices=Source.choices,
        default=Source.EMBEDDED,
    )

    # Raw EXIF/XMP data for fields we don't have explicit columns for
    raw_exif = models.JSONField(null=True, blank=True)
    raw_xmp = models.JSONField(null=True, blank=True)
    raw_iptc = models.JSONField(null=True, blank=True)

    # Version tracking
    version = models.IntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Photo Metadata"
        verbose_name_plural = "Photo Metadata"
        indexes = [
            models.Index(fields=["camera_make", "camera_model"]),
            models.Index(fields=["date_taken"]),
            models.Index(fields=["location_country", "location_city"]),
        ]

    def __str__(self):
        return f"Metadata for {self.photo_id}"

    @property
    def resolution(self):
        """Returns resolution as 'WxH' string."""
        if self.width and self.height:
            return f"{self.width}x{self.height}"
        return None

    @property
    def megapixels(self):
        """Returns megapixel count."""
        if self.width and self.height:
            return round((self.width * self.height) / 1_000_000, 1)
        return None

    @property
    def has_location(self):
        """Check if GPS coordinates are available."""
        return self.gps_latitude is not None and self.gps_longitude is not None

    @property
    def camera_display(self):
        """Returns a human-readable camera name."""
        if self.camera_make and self.camera_model:
            # Avoid duplicating make in model
            if self.camera_model.startswith(self.camera_make):
                return self.camera_model
            return f"{self.camera_make} {self.camera_model}"
        return self.camera_model or self.camera_make

    @property
    def lens_display(self):
        """Returns a human-readable lens name."""
        if self.lens_make and self.lens_model:
            if self.lens_model.startswith(self.lens_make):
                return self.lens_model
            return f"{self.lens_make} {self.lens_model}"
        return self.lens_model or self.lens_make

    @classmethod
    def extract_exif_data(cls, photo, commit=True):
        """
        Extract EXIF data from a photo's main file and update PhotoMetadata.

        This method extracts metadata from the photo's main file and:
        1. Updates Photo fields (size, video_length, rating, exif_timestamp_subsec, image_sequence_number)
        2. Gets or creates PhotoMetadata and populates it with extracted data

        Args:
            photo: Photo instance to extract metadata from
            commit: Whether to save Photo and PhotoMetadata after extraction

        Returns:
            PhotoMetadata instance
        """
        if not photo.main_file:
            return None

        # Every name gets a key even if get_metadata comes back short, so the
        # appliers below can index values[...] without a KeyError.
        values = dict.fromkeys(EXIF_VALUE_NAMES)
        values.update(
            zip(
                EXIF_VALUE_NAMES,
                get_metadata(photo.main_file.path, tags=EXIF_TAGS, try_sidecar=True),
            )
        )

        cls._apply_to_photo(photo, values)
        if commit:
            photo.save()

        metadata, created = cls.objects.get_or_create(
            photo=photo, defaults={"source": cls.Source.EMBEDDED}
        )
        cls._apply_to_metadata(metadata, values)

        if commit:
            metadata.save()
            # "Import tags from EXIF": the keywords read above also become Tag rows.
            link_tags_from_keywords(photo, metadata.keywords)
            cls._import_description_to_caption(photo, _description(values))

        return metadata

    @staticmethod
    def _apply_to_photo(photo, values):
        """Update the Photo fields that are still stored outside PhotoMetadata."""
        _assign_nonzero_number(photo, "size", values["size"])
        _assign_nonzero_number(photo, "video_length", values["video_length"])
        _assign_number(photo, "rating", values["rating"])

        # Burst/sequence detection fields
        subsec_time_original = values["subsec_time_original"]
        if subsec_time_original:
            # SubSecTimeOriginal is typically a string like "123" representing milliseconds
            photo.exif_timestamp_subsec = str(subsec_time_original)[:10]

        image_number = values["image_number"]
        if image_number is not None and isinstance(image_number, numbers.Number):
            photo.image_sequence_number = int(image_number)

    @staticmethod
    def _apply_to_metadata(metadata, values):
        """Populate the PhotoMetadata columns from the extracted EXIF values."""
        for field, name in (
            ("aperture", "fstop"),
            ("focal_length", "focal_length"),
            ("iso", "iso"),
            ("width", "width"),
            ("height", "height"),
            ("focal_length_35mm", "focal_length_35mm"),
        ):
            _assign_nonzero_number(metadata, field, values[name])

        _assign_string(metadata, "camera_model", values["camera"])
        _assign_string(metadata, "lens_model", values["lens"])
        _assign_number(metadata, "rating", values["rating"])

        shutter_speed = values["shutter_speed"]
        if shutter_speed and isinstance(shutter_speed, numbers.Number):
            metadata.shutter_speed = str(
                Fraction(shutter_speed).limit_denominator(1000)
            )

        subsec_time_original = values["subsec_time_original"]
        if subsec_time_original:
            metadata.date_taken_subsec = str(subsec_time_original)[:10]

        keywords = _merge_keywords(values["xmp_subject"], values["iptc_keywords"])
        if keywords:
            metadata.keywords = keywords

        description = _description(values)
        if description and not _user_edited(metadata, "caption"):
            metadata.caption = description

    @staticmethod
    def _import_description_to_caption(photo, description):
        """Carry a newly found file description over to the lightbox caption.

        ``PhotoMetadata.caption`` is the structured field; the caption a user
        sees and edits in the lightbox is ``captions_json["user_caption"]``.
        Metadata is re-extracted on every scan, so the description last
        imported is remembered under ``IMPORTED_DESCRIPTION_KEY`` and the
        lightbox caption is only touched when the file's description differs
        from it, i.e. on first import or after the file was edited. Even then
        it is only written when the lightbox caption is empty or still exactly
        the previously imported text: a caption the user typed over it is
        kept. A caption the user cleared stays cleared, because the unchanged
        description on the next scan matches the remembered one.

        It goes through ``PhotoCaption.apply_user_caption``, the same path as a
        typed caption, so it is indexed for search and its #hashtags become
        hashtag albums.
        """
        if not description:
            return

        from api.models.photo_caption import PhotoCaption

        caption_instance, _ = PhotoCaption.objects.get_or_create(photo=photo)
        captions = caption_instance.captions_json or {}
        previously_imported = captions.get(IMPORTED_DESCRIPTION_KEY)
        if description == previously_imported:
            return

        current = captions.get("user_caption") or ""
        caption_instance.captions_json = {
            **captions,
            IMPORTED_DESCRIPTION_KEY: description,
        }
        if current.strip() and current != previously_imported:
            caption_instance.save(update_fields=["captions_json"])
            return

        try:
            caption_instance.apply_user_caption(description, commit=True)
        except Exception:
            util.logger.exception(
                f"could not import the description of photo {photo.image_hash} "
                "as its caption"
            )


def _user_edited(metadata, field_name):
    """Whether the user changed *field_name* through the metadata API.

    Such an edit sets ``source`` to USER_EDIT and leaves a MetadataEdit row;
    "revert all" leaves a ``_all`` row, and only edits after the latest one
    count, so a revert lets the file's value back in.
    """
    if metadata.source != PhotoMetadata.Source.USER_EDIT:
        return False
    edits = MetadataEdit.objects.filter(photo_id=metadata.photo_id)
    field_edits = edits.filter(field_name=field_name)
    last_revert = (
        edits.filter(field_name="_all")
        .order_by("-created_at")
        .values_list("created_at", flat=True)
        .first()
    )
    if last_revert is not None:
        field_edits = field_edits.filter(created_at__gt=last_revert)
    return field_edits.exists()


class MetadataEdit(models.Model):
    """
    Tracks user edits to photo metadata for history/undo functionality.

    Each edit records what field was changed, old value, new value,
    and who made the change.
    """

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    photo = models.ForeignKey(
        "Photo",
        on_delete=models.CASCADE,
        related_name="metadata_edits",
    )

    user = models.ForeignKey(
        User,
        on_delete=models.SET(get_deleted_user),
        related_name="metadata_edits",
    )

    # Which field was edited
    field_name = models.CharField(max_length=100)

    # JSON-serialized old and new values
    old_value = models.JSONField(null=True, blank=True)
    new_value = models.JSONField(null=True, blank=True)

    # Whether this edit has been written back to the file
    synced_to_file = models.BooleanField(default=False)
    synced_at = models.DateTimeField(null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        # -id is a tiebreaker, not a second sort key: edits saved in the same
        # clock tick share a created_at, and without it the database is free to
        # return them in a different order per query, which lets a row repeat on
        # one page of the history endpoint and vanish from the next. id is a
        # random uuid4, so the order within a tick is arbitrary but stable.
        ordering = ["-created_at", "-id"]
        verbose_name = "Metadata Edit"
        verbose_name_plural = "Metadata Edits"
        indexes = [
            models.Index(fields=["photo", "-created_at"]),
        ]

    def __str__(self):
        return f"Edit {self.field_name} on {self.photo_id}"
