//! Django password hashers: verify `argon2$...`, `pbkdf2_sha256$...` and
//! `pbkdf2_sha1$...`; hash new passwords as Django-format Argon2id with
//! Django's parameters (t=2, m=102400, p=8, 32-byte hash).
//!
//! Argon2 at these parameters is ~100 MB and noticeable CPU: call from
//! `AppState::blocking` / `spawn_blocking`, never directly on the runtime.

use argon2::password_hash::{PasswordHash, PasswordHasher, PasswordVerifier, SaltString};
use argon2::{Algorithm, Argon2, Params, Version};
use base64::Engine;
use base64::engine::general_purpose::STANDARD;
use rand::Rng;
use subtle::ConstantTimeEq;

const SALT_CHARS: &[u8] = b"abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";

/// Check `password` against a Django-encoded hash. Unusable (`!...`) or
/// unknown formats never verify.
pub fn verify(password: &str, encoded: &str) -> bool {
    if let Some(phc) = encoded.strip_prefix("argon2") {
        return verify_argon2(password, phc);
    }
    if let Some(rest) = encoded.strip_prefix("pbkdf2_sha256$") {
        return verify_pbkdf2(password, rest, Pbkdf2Digest::Sha256);
    }
    if let Some(rest) = encoded.strip_prefix("pbkdf2_sha1$") {
        return verify_pbkdf2(password, rest, Pbkdf2Digest::Sha1);
    }
    false
}

fn verify_argon2(password: &str, phc: &str) -> bool {
    let Ok(hash) = PasswordHash::new(phc) else {
        return false;
    };
    Argon2::default()
        .verify_password(password.as_bytes(), &hash)
        .is_ok()
}

#[derive(Clone, Copy)]
enum Pbkdf2Digest {
    Sha256,
    Sha1,
}

fn verify_pbkdf2(password: &str, rest: &str, digest: Pbkdf2Digest) -> bool {
    let mut parts = rest.splitn(3, '$');
    let (Some(iter), Some(salt), Some(expected)) = (parts.next(), parts.next(), parts.next())
    else {
        return false;
    };
    let Ok(iterations) = iter.parse::<u32>() else {
        return false;
    };
    let out = match digest {
        Pbkdf2Digest::Sha256 => {
            let mut out = vec![0u8; 32];
            pbkdf2::pbkdf2_hmac::<sha2::Sha256>(
                password.as_bytes(),
                salt.as_bytes(),
                iterations,
                &mut out,
            );
            out
        }
        Pbkdf2Digest::Sha1 => {
            let mut out = vec![0u8; 20];
            pbkdf2::pbkdf2_hmac::<sha1::Sha1>(
                password.as_bytes(),
                salt.as_bytes(),
                iterations,
                &mut out,
            );
            out
        }
    };
    let computed = STANDARD.encode(&out);
    computed.as_bytes().ct_eq(expected.as_bytes()).into()
}

/// New hash in Django's Argon2PasswordHasher format.
pub fn hash(password: &str) -> String {
    let mut rng = rand::thread_rng();
    let salt: String = (0..22)
        .map(|_| SALT_CHARS[rng.gen_range(0..SALT_CHARS.len())] as char)
        .collect();
    let salt = SaltString::encode_b64(salt.as_bytes()).expect("22-byte salt is valid");
    let params = Params::new(102_400, 2, 8, Some(32)).expect("valid argon2 params");
    let argon = Argon2::new(Algorithm::Argon2id, Version::V0x13, params);
    let phc = argon
        .hash_password(password.as_bytes(), &salt)
        .expect("argon2 hashing cannot fail with valid params")
        .to_string();
    format!("argon2{phc}")
}

#[cfg(test)]
mod tests {
    use super::*;

    // Generated by Django 5.2 (make_password("pw", hasher=...)).
    const DJ_ARGON2: &str = "argon2$argon2id$v=19$m=102400,t=2,p=8$bFRNNnJsUWsyYTd5eHJ5RlFEVGNMZA$Nzhdc/bzy5i3E+/cQJTqGENseLILmU+J4gJkRh9yuk8";
    const DJ_SHA256: &str =
        "pbkdf2_sha256$1000000$Cdk0QO8Ner5DeSMb3902j2$do062zwXPqiswVAGxeqbmy4y1g2qIS6o9lnEhlrgAck=";
    const DJ_SHA1: &str = "pbkdf2_sha1$1000000$FYTE5cFW8TNF4xkmqIwFk7$wd0I+7cSH2CstjyyD+4n5WEhxHU=";

    #[test]
    fn verifies_django_hashes() {
        assert!(verify("pw", DJ_ARGON2));
        assert!(!verify("pW", DJ_ARGON2));
        assert!(verify("pw", DJ_SHA256));
        assert!(!verify("px", DJ_SHA256));
        assert!(verify("pw", DJ_SHA1));
        assert!(!verify("pw", "!unusable"));
        assert!(!verify("pw", ""));
    }

    #[test]
    fn hashes_in_django_format() {
        let h = hash("secret");
        assert!(
            h.starts_with("argon2$argon2id$v=19$m=102400,t=2,p=8$"),
            "{h}"
        );
        assert!(verify("secret", &h));
        assert!(!verify("Secret", &h));
    }
}
