export const userDefaults = {
  confidence: "0.1",
  confidence_person: 0.9,
  transcode_videos: false,
  semantic_search_topk: 0,
  favorite_min_rating: 4,
  save_metadata_to_disk: "OFF",
  datetime_rules:
    '[{"id": 14, "name": "Timestamp set by user", "rule_type": "user_defined", "is_default": true}, {"id": 15, "name": "Local time from EXIF:DateTime exif tag", "rule_type": "exif", "exif_tag": "EXIF:DateTime", "is_default": true}, {"id": 1, "name": "Local time from EXIF:DateTimeOriginal exif tag", "rule_type": "exif", "exif_tag": "EXIF:DateTimeOriginal", "is_default": true}, {"id": 2, "name": "Get Video creation tag in UTC + figure out timezone using GPS coordinates", "rule_type": "exif", "exif_tag": "QuickTime:CreateDate", "transform_tz": 1, "source_tz": "utc", "report_tz": "gps_timezonefinder", "is_default": true}, {"id": 11, "name": "Use Composite:GPSDateTime tag + figure out timezone using GPS coordinates", "rule_type": "exif", "exif_tag": "Composite:GPSDateTime", "transform_tz": 1, "source_tz": "utc", "report_tz": "gps_timezonefinder", "is_default": true}, {"id": 3, "name": "Using filename assuming time is local (most of filenames auto generated by smartphones etc)", "rule_type": "path", "is_default": true}, {"id": 4, "name": "Video creation datetime in user default timezone (can\'t find out actual timezone)", "rule_type": "exif", "exif_tag": "QuickTime:CreateDate", "transform_tz": 1, "source_tz": "utc", "report_tz": "user_default", "is_default": true}, {"id": 5, "name": "Extract date using WhatsApp file name", "rule_type": "path", "predefined_regexp": "whatsapp", "is_default": true}]',
  default_timezone: "UTC",
};
