# Generated by Django 3.1.8 on 2021-08-06 11:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_b_migrate_favorited_to_rating"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="favorited",
        ),
    ]
