# Generated by Django 3.1.8 on 2021-08-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_c_remove_favorited"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="favorite_min_rating",
            field=models.IntegerField(db_index=True, default=4),
        ),
    ]
