# Generated by Django 3.1.14 on 2022-02-01 22:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0020_add_default_timezone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="image",
        ),
    ]
