# Generated by Django 3.1.14 on 2022-02-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0022_photo_video_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
