# Generated by Django 3.1.14 on 2022-07-17 19:07
from django.db import migrations
import api.models.person

def migrate_unknown(apps, schema_editor):
    Person = apps.get_model('api', 'Person')
    try:
        person: Person = Person.objects.get(name="unknown")
        person.name = "Unknown - Other"
        person.kind = api.models.person.Person.KIND_UNKNOWN
        person.save()
    except Person.DoesNotExist:
        pass

def unmigrate_unknown(apps, schema_editor):
    Person = apps.get_model('api', 'Person')
    try:
        person: Person = Person.objects.get(name="Unknown - Other")
        person.name = "unknown"
        person.kind = ""
        person.save()
    except Person.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_add_cluster_info'),
    ]

    operations = [
        migrations.RunPython(migrate_unknown, unmigrate_unknown)
    ]
