# Generated by Django 3.1.14 on 2022-09-02 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0033_add_post_delete_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="cover_photo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="person",
                to="api.photo",
            ),
        ),
    ]
