# Generated by Django 4.2rc1 on 2023-04-04 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0041_apply_user_enum_for_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="albumuser",
            name="cover_photo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="album_user",
                to="api.photo",
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="main_file",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="main_photo",
                to="api.file",
            ),
        ),
    ]
