# Generated by Django 4.2rc1 on 2023-04-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0046_add_embedded_media"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="embedded_media",
            field=models.ManyToManyField(to="api.file"),
        ),
    ]
