# Generated by Django 4.2.1 on 2023-06-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_fix_metadata_files_as_main_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='localOrientation',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='photo',
            name='orientation',
            field=models.IntegerField(default=1),
        ),
    ]
