# Generated by Django 4.2.1 on 2023-07-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0052_alter_person_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="confidence_unknown_face",
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name="user",
            name="face_recognition_model",
            field=models.TextField(
                choices=[("HOG", "Hog"), ("CNN", "Cnn")], default="HOG"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="min_cluster_size",
            field=models.IntegerField(default=0),
        ),
    ]
