# Generated by Django 4.2.8 on 2024-01-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0056_user_llm_settings_alter_longrunningjob_job_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="face",
            name="image_path",
        ),
        migrations.AlterField(
            model_name="face",
            name="person_label_is_inferred",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
