# Generated by Django 4.2.11 on 2024-03-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0061_alter_person_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="albumthing",
            name="cover_photos",
            field=models.ManyToManyField(
                related_name="album_thing_cover_photos", to="api.photo"
            ),
        ),
    ]
