# Generated by Django 4.2.11 on 2024-04-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0065_apply_default_photo_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="moved_to_trash_on",
            field=models.DateTimeField(db_index=True, default=None),
            preserve_default=False,
        ),
    ]
