# Generated by Django 4.2.14 on 2024-08-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0069_rename_to_in_trashcan"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="removed",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
