# Generated by Django 4.2.16 on 2024-09-20 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0070_photo_removed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="face",
            old_name="person_label_probability",
            new_name="cluster_probability",
        ),
        migrations.RemoveField(
            model_name="face",
            name="person_label_is_inferred",
        ),
        migrations.AddField(
            model_name="face",
            name="classification_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="classification_faces",
                to="api.person",
            ),
        ),
        migrations.AddField(
            model_name="face",
            name="classification_probability",
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name="face",
            name="cluster_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cluster_classification_faces",
                to="api.person",
            ),
        ),
        migrations.AddField(
            model_name="face",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
