# Generated by Django 4.2.16 on 2024-09-20 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0074_migrate_cluster_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="face",
            name="cluster_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cluster_faces",
                to="api.person",
            ),
        ),
    ]
