/**
 * The predefined date-time and burst rules are parsed against their schemas
 * (they used to be cast). A rule the schema rejected would break the settings
 * page, and a key it does not know would be stripped from the rules users save
 * (the rule schemas are loose, so it is kept).
 * These are the backend's answers, from PREDEFINED_RULES_JSON in
 * api/date_time_extractor.py and api/burst_detection_rules.py.
 *
 * The hooks parse the list rule by rule, so a rule a newer backend added (a rule
 * type or option this frontend does not know) is skipped and reported, and the
 * Add dialog and "Reset to defaults" still get every other rule.
 */
import { afterEach, describe, expect, it, vi } from "vitest";
import { BurstDetectionRule, PredefinedBurstRules } from "../../components/settings/burst-detection.zod";
import { DateTimeRule } from "../../components/settings/date-time.zod";
import { parseListWithNotification } from "../../util/zodUtils";
import { PredefinedRules } from "./types";

const stubs = vi.hoisted(() => ({ parseError: vi.fn<(message: string) => void>() }));
vi.mock("../../service/notifications", () => ({ notification: { parseError: stubs.parseError } }));

afterEach(() => {
  stubs.parseError.mockReset();
});

const PREDEFINED_DATE_TIME_RULES: unknown = JSON.parse(
  '[{"id": 14, "name": "Timestamp set by user", "rule_type": "user_defined", "is_default": true}, {"id": 16, "name": "Local time from XMP:DateCreated tag (set by LibrePhotos or other photo managers)", "rule_type": "exif", "exif_tag": "XMP:DateCreated", "is_default": true}, {"id": 1, "name": "Local time from EXIF:DateTimeOriginal exif tag", "rule_type": "exif", "exif_tag": "EXIF:DateTimeOriginal", "is_default": true}, {"id": 15, "name": "Local time from EXIF:ModifyDate exif tag", "rule_type": "exif", "exif_tag": "EXIF:ModifyDate", "is_default": true}, {"id": 2, "name": "Get Video creation tag in UTC + figure out timezone using GPS coordinates", "rule_type": "exif", "exif_tag": "QuickTime:CreateDate", "transform_tz": 1, "source_tz": "utc", "report_tz": "gps_timezonefinder", "is_default": true}, {"id": 11, "name": "Use Composite:GPSDateTime tag + figure out timezone using GPS coordinates", "rule_type": "exif", "exif_tag": "Composite:GPSDateTime", "transform_tz": 1, "source_tz": "utc", "report_tz": "gps_timezonefinder", "is_default": true}, {"id": 3, "name": "Using filename assuming time is local (most of filenames auto generated by smartphones etc)", "rule_type": "path", "is_default": true}, {"id": 4, "name": "Video creation datetime in user default timezone (can\'t find out actual timezone)", "rule_type": "exif", "exif_tag": "QuickTime:CreateDate", "transform_tz": 1, "source_tz": "utc", "report_tz": "user_default", "is_default": true}, {"id": 5, "name": "Extract date using WhatsApp file name", "rule_type": "path", "predefined_regexp": "whatsapp", "is_default": true}, {"id": 6, "name": "Video creation datetime in UTC timezone (can\'t find out actual timezone)", "rule_type": "exif", "exif_tag": "QuickTime:CreateDate", "is_default": false}, {"id": 7, "name": "File modified time in user default timezone", "rule_type": "filesystem", "file_property": "mtime", "transform_tz": 1, "source_tz": "utc", "report_tz": "user_default", "is_default": false}, {"id": 8, "name": "File modified time in UTC timezone", "rule_type": "filesystem", "file_property": "mtime", "is_default": false}, {"id": 9, "name": "File created time in user default timezone", "rule_type": "filesystem", "file_property": "ctime", "transform_tz": 1, "source_tz": "utc", "report_tz": "user_default", "is_default": false}, {"id": 10, "name": "File created time in UTC timezone", "rule_type": "filesystem", "file_property": "ctime", "is_default": false}, {"id": 12, "name": "Use Composite:GPSDateTime tag in user default timezone (can\'t find out actual timezone)", "rule_type": "exif", "exif_tag": "Composite:GPSDateTime", "transform_tz": 1, "source_tz": "utc", "report_tz": "user_default", "is_default": false}, {"id": 13, "name": "Use Composite:GPSDateTime tag in UTC timezone (can\'t find out actual timezone)", "rule_type": "exif", "exif_tag": "Composite:GPSDateTime", "is_default": false}]'
);

const PREDEFINED_BURST_RULES: unknown = JSON.parse(
  '[{"id": 1, "name": "EXIF Burst Mode Tag", "rule_type": "exif_burst_mode", "category": "hard", "enabled": true, "is_default": true, "description": "Detects photos where camera was in burst mode (using MakerNotes:BurstMode or MakerNotes:ContinuousDrive EXIF tags)"}, {"id": 2, "name": "EXIF Sequence Number", "rule_type": "exif_sequence_number", "category": "hard", "enabled": true, "is_default": true, "description": "Groups photos by EXIF sequence number (MakerNotes:SequenceNumber) taken at the same time"}, {"id": 3, "name": "Filename Burst Pattern", "rule_type": "filename_pattern", "category": "hard", "enabled": true, "is_default": true, "pattern_type": "all", "description": "Detects burst sequences from filename patterns (e.g., IMG_001_BURST001, photo (1), photo (2))"}, {"id": 101, "name": "Timestamp Proximity", "rule_type": "timestamp_proximity", "category": "soft", "enabled": false, "is_default": true, "interval_ms": 2000, "require_same_camera": true, "description": "Groups photos taken within a short time interval (configurable, default 2 seconds)"}, {"id": 102, "name": "Visual Similarity", "rule_type": "visual_similarity", "category": "soft", "enabled": false, "is_default": true, "similarity_threshold": 15, "description": "Groups visually similar consecutive photos using perceptual hash comparison"}, {"id": 4, "name": "Filename Burst Suffix Only", "rule_type": "filename_pattern", "category": "hard", "enabled": false, "is_default": false, "pattern_type": "burst_suffix", "description": "Only detect files with explicit _BURST suffix in filename"}, {"id": 5, "name": "Custom Filename Pattern", "rule_type": "filename_pattern", "category": "hard", "enabled": false, "is_default": false, "pattern_type": "custom", "custom_pattern": "", "description": "Use a custom regex pattern to match burst filenames"}, {"id": 103, "name": "Timestamp Proximity (Loose)", "rule_type": "timestamp_proximity", "category": "soft", "enabled": false, "is_default": false, "interval_ms": 5000, "require_same_camera": false, "description": "Groups photos taken within 5 seconds, regardless of camera"}]'
);

describe("predefined rules from the backend", () => {
  it("parse as date-time rules without losing a key", () => {
    expect(PredefinedRules.parse(PREDEFINED_DATE_TIME_RULES)).toStrictEqual(PREDEFINED_DATE_TIME_RULES);
  });

  it("parse as burst rules without losing a key", () => {
    expect(PredefinedBurstRules.parse(PREDEFINED_BURST_RULES)).toStrictEqual(PREDEFINED_BURST_RULES);
  });

  it("keep a key the schemas do not know, such as a param added on the backend later", () => {
    const dateTimeRule = { id: 3, name: "Filename", rule_type: "path", is_default: true, new_param: { x: 1 } };
    const burstRule = {
      id: 1,
      name: "EXIF Burst Mode Tag",
      rule_type: "exif_burst_mode",
      category: "hard",
      enabled: true,
      is_default: true,
      new_param: [1, 2],
    };

    expect(PredefinedRules.parse([dateTimeRule])).toStrictEqual([dateTimeRule]);
    expect(PredefinedBurstRules.parse([burstRule])).toStrictEqual([burstRule]);
  });
});

describe("parsing the predefined rules rule by rule", () => {
  const userDefined = { id: 14, name: "Timestamp set by user", rule_type: "user_defined", is_default: true };
  const filename = { id: 3, name: "Filename", rule_type: "path", is_default: true };

  it("skips a date-time rule of a type this frontend does not know, keeps the rest and reports it", () => {
    const fromTheFuture = { id: 17, name: "From a newer backend", rule_type: "sidecar_file", is_default: true };

    const rules = parseListWithNotification(
      DateTimeRule,
      [userDefined, fromTheFuture, filename],
      "Predefined date-time rules"
    );

    expect(rules).toStrictEqual([userDefined, filename]);
    expect(stubs.parseError).toHaveBeenCalledTimes(1);
    expect(stubs.parseError).toHaveBeenCalledWith(
      expect.stringContaining("Predefined date-time rules: skipped 1 of 3")
    );
    expect(stubs.parseError).toHaveBeenCalledWith(expect.stringContaining("entry 1:"));
  });

  it("skips a burst rule with an option value this frontend does not know, and keeps the rest", () => {
    const burstMode = {
      id: 1,
      name: "EXIF Burst Mode Tag",
      rule_type: "exif_burst_mode",
      category: "hard",
      enabled: true,
      is_default: true,
    };
    const newPattern = { ...burstMode, id: 6, rule_type: "filename_pattern", pattern_type: "pixel_burst" };

    const rules = parseListWithNotification(BurstDetectionRule, [newPattern, burstMode], "Predefined burst rules");

    expect(rules).toStrictEqual([burstMode]);
    expect(stubs.parseError).toHaveBeenCalledWith(expect.stringContaining("skipped 1 of 2"));
  });

  it("reports nothing when every rule parses", () => {
    expect(parseListWithNotification(DateTimeRule, PREDEFINED_DATE_TIME_RULES)).toStrictEqual(
      PREDEFINED_DATE_TIME_RULES
    );
    expect(parseListWithNotification(BurstDetectionRule, PREDEFINED_BURST_RULES)).toStrictEqual(PREDEFINED_BURST_RULES);
    expect(stubs.parseError).not.toHaveBeenCalled();
  });

  it("still fails, and reports, when the answer is not a list at all", () => {
    expect(() =>
      parseListWithNotification(DateTimeRule, { detail: "Not found." }, "Predefined date-time rules")
    ).toThrow();
    expect(stubs.parseError).toHaveBeenCalledTimes(1);
  });
});
