/**
 * Migration runner (doc 02 §6). Applies the committed drizzle migrations at app
 * start before any query. If a migration is impossible, falls back to
 * WIPE-AND-RESEED: the mirror is disposable, so only outbox + upload_queue must
 * survive (auth lives in secure-store, outside the DB). Those are read out,
 * every table is dropped and rebuilt from the migration SQL, then the preserved
 * rows are restored. The caller re-triggers a full seed afterward.
 */
import { sql } from "drizzle-orm";
import { migrate } from "drizzle-orm/expo-sqlite/migrator";
import type { SQLiteDatabase } from "expo-sqlite";
import type { AppDatabase } from "./types";
import { MIGRATION_STATEMENTS } from "./migrations-sql";
// The expo migrator bundle (SQL + journal) generated by drizzle-kit.
import migrations from "./migrations/migrations";

export type MigrationResult = { ok: true; wiped: boolean };

export async function runMigrations(db: AppDatabase, sqlite: SQLiteDatabase): Promise<MigrationResult> {
  try {
    await migrate(db, migrations);
    return { ok: true, wiped: false };
  } catch (err) {
    console.warn("[db] migration failed, wiping and reseeding mirror", err);
    wipeAndRebuild(sqlite);
    return { ok: true, wiped: true };
  }
}

/** Drop every table and rebuild from the migration SQL, preserving durable rows. */
export function wipeAndRebuild(sqlite: SQLiteDatabase): void {
  const preservedOutbox = sqlite.getAllSync("SELECT * FROM outbox") as Record<string, unknown>[];
  const preservedUploads = sqlite.getAllSync("SELECT * FROM upload_queue") as Record<string, unknown>[];

  const tables = sqlite.getAllSync(
    "SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%'"
  ) as { name: string }[];
  sqlite.execSync("PRAGMA foreign_keys = OFF;");
  for (const { name } of tables) sqlite.execSync(`DROP TABLE IF EXISTS \`${name}\`;`);
  // The drizzle journal table too, so the migrator re-applies from scratch.
  sqlite.execSync("DROP TABLE IF EXISTS `__drizzle_migrations`;");
  for (const stmt of MIGRATION_STATEMENTS) sqlite.execSync(stmt);

  restoreRows(sqlite, "outbox", preservedOutbox);
  restoreRows(sqlite, "upload_queue", preservedUploads);
}

function restoreRows(sqlite: SQLiteDatabase, table: string, rows: Record<string, unknown>[]): void {
  for (const row of rows) {
    const cols = Object.keys(row);
    if (cols.length === 0) continue;
    const placeholders = cols.map(() => "?").join(", ");
    const stmt = sqlite.prepareSync(
      `INSERT INTO \`${table}\` (${cols.map((c) => `\`${c}\``).join(", ")}) VALUES (${placeholders})`
    );
    try {
      stmt.executeSync(cols.map((c) => row[c] as never));
    } finally {
      stmt.finalizeSync();
    }
  }
}

/** Clear only the mirror tables (used when favorite_min_rating changes → re-seed). */
export function clearMirror(db: AppDatabase): void {
  for (const table of [
    "remote_photo",
    "remote_photo_detail",
    "person",
    "user_album",
    "user_album_photo",
    "auto_album",
    "auto_album_photo",
    "thing_album",
    "place_album",
    "tag_album",
    "shared_from_me",
    "shared_user",
  ]) {
    db.run(sql.raw(`DELETE FROM ${table}`));
  }
  db.run(sql`DELETE FROM sync_state`);
}
