"""Cut migrations/sqlite/0000_baseline.sql from a Django-migrated SQLite file.

    python sqlite_baseline.py <django.sqlite3> [-o OUT] [--check FILE]

The SQLite twin of migrations/0000_baseline.sql (pg_dump -s of the
application tables): the sqlite_master DDL of the api_* tables (models and
M2M through tables) and chunked_upload_*, then their indexes, in creation
order. Like the Postgres baseline it leaves out api_user_groups and
api_user_user_permissions (foreign keys to Django's auth tables) and every
Django framework table. build_fixture.sh (LP_FIXTURE_BACKEND=sqlite) runs it
with --check against the committed file to catch pin drift.
"""

import argparse
import sqlite3
import sys

EXCLUDE = {"api_user_groups", "api_user_user_permissions"}


def application_table(name):
    return (name.startswith(("api_", "chunked_upload_"))) and name not in EXCLUDE


def django_api_migration(conn):
    row = conn.execute(
        "SELECT name FROM django_migrations WHERE app = 'api' ORDER BY name DESC LIMIT 1"
    ).fetchone()
    return row[0] if row else "?"


def cut(path):
    # Read-write, so a leftover WAL is replayed and removed on close.
    conn = sqlite3.connect(path)
    rows = conn.execute(
        "SELECT type, name, tbl_name, sql FROM sqlite_master "
        "WHERE sql IS NOT NULL AND type IN ('table', 'index', 'trigger') ORDER BY rowid"
    ).fetchall()
    migration = django_api_migration(conn)
    conn.close()
    tables = [r for r in rows if r[0] == "table" and application_table(r[1])]
    others = [r for r in rows if r[0] != "table" and application_table(r[2])]
    out = [
        f"-- Baseline: the Django schema at api.{migration.split('_')[0]} on SQLite (application tables only).",
        "-- Generated by tests/fixture/sqlite_baseline.py from sqlite_master of a fresh",
        "-- DB_BACKEND=sqlite `manage.py migrate` (build_fixture.sh, LP_FIXTURE_BACKEND=sqlite).",
        "-- Excludes api_user_groups / api_user_user_permissions (FKs to Django auth tables).",
        "",
    ]
    for _type, _name, _tbl, sql in tables + others:
        out.append(sql.strip() + ";")
        out.append("")
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("db")
    ap.add_argument("-o", "--output")
    ap.add_argument(
        "--check", help="compare with this file instead; exit 1 when it differs"
    )
    args = ap.parse_args()
    text = cut(args.db)
    if args.check:
        with open(args.check, encoding="utf-8") as fh:
            if fh.read() != text:
                sys.stderr.write(
                    f"{args.check} differs from the schema of {args.db}; "
                    "re-cut it with sqlite_baseline.py -o\n"
                )
                sys.exit(1)
        return
    if args.output:
        with open(args.output, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(text)
    else:
        sys.stdout.write(text)


if __name__ == "__main__":
    main()
