-- Baseline: the Django schema at api.0142 (application tables only).
-- Generated with pg_dump -s from a fresh Django-migrated database; see CLAUDE.md.
-- Excludes api_user_groups / api_user_user_permissions (FKs to Django auth tables).


CREATE TABLE public.api_albumauto (
    id integer NOT NULL,
    title character varying(512) NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    created_on timestamp with time zone NOT NULL,
    gps_lat double precision,
    gps_lon double precision,
    favorited boolean NOT NULL,
    owner_id integer NOT NULL,
    last_modified timestamp with time zone NOT NULL
);

ALTER TABLE public.api_albumauto ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_albumauto_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.api_albumauto_photos (
    id integer NOT NULL,
    albumauto_id integer NOT NULL,
    photo_id uuid
);

ALTER TABLE public.api_albumauto_photos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_albumauto_photos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.api_albumauto_shared_to (
    id integer NOT NULL,
    albumauto_id integer NOT NULL,
    user_id integer NOT NULL
);

ALTER TABLE public.api_albumauto_shared_to ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_albumauto_shared_to_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.api_albumdate (
    id integer NOT NULL,
    title character varying(512) NOT NULL,
    date date,
    favorited boolean NOT NULL,
    location jsonb,
    owner_id integer NOT NULL
);

ALTER TABLE public.api_albumdate ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_albumdate_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.api_albumdate_photos (
    id integer NOT NULL,
    albumdate_id integer NOT NULL,
    photo_id uuid
);

ALTER TABLE public.api_albumdate_photos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_albumdate_photos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.api_albumdate_shared_to (
    id integer NOT NULL,
    albumdate_id integer NOT NULL,
    user_id integer NOT NULL
);

ALTER TABLE public.api_albumdate_shared_to ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_albumdate_shared_to_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.api_albumplace (
    id integer NOT NULL,
    title character varying(512) NOT NULL,
    geolocation_level integer,
    favorited boolean NOT NULL,
    owner_id integer NOT NULL,
    last_modified timestamp with time zone NOT NULL
);

ALTER TABLE public.api_albumplace ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_albumplace_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.api_albumplace_photos (
    id integer NOT NULL,
    albumplace_id integer NOT NULL,
    photo_id uuid
);

ALTER TABLE public.api_albumplace_photos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_albumplace_photos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.api_albumplace_shared_to (
    id integer NOT NULL,
    albumplace_id integer NOT NULL,
    user_id integer NOT NULL
);

ALTER TABLE public.api_albumplace_shared_to ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_albumplace_shared_to_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.api_albumthing (
    id integer NOT NULL,
    title character varying(512) NOT NULL,
    thing_type character varying(512),
    favorited boolean NOT NULL,
    owner_id integer NOT NULL,
    photo_count integer NOT NULL,
    last_modified timestamp with time zone NOT NULL
);

CREATE TABLE public.api_albumthing_cover_photos (
    id integer NOT NULL,
    albumthing_id integer NOT NULL,
    photo_id uuid
);

ALTER TABLE public.api_albumthing_cover_photos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_albumthing_cover_photos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.api_albumthing ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_albumthing_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.api_albumthing_photos (
    id integer NOT NULL,
    albumthing_id integer NOT NULL,
    photo_id uuid
);

ALTER TABLE public.api_albumthing_photos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_albumthing_photos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.api_albumthing_shared_to (
    id integer NOT NULL,
    albumthing_id integer NOT NULL,
    user_id integer NOT NULL
);

ALTER TABLE public.api_albumthing_shared_to ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_albumthing_shared_to_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.api_albumuser (
    id integer NOT NULL,
    title character varying(512) NOT NULL,
    created_on timestamp with time zone NOT NULL,
    favorited boolean NOT NULL,
    owner_id integer NOT NULL,
    cover_photo_id uuid,
    last_modified timestamp with time zone NOT NULL
);

ALTER TABLE public.api_albumuser ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_albumuser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.api_albumuser_photos (
    id integer NOT NULL,
    albumuser_id integer NOT NULL,
    photo_id uuid
);

ALTER TABLE public.api_albumuser_photos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_albumuser_photos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.api_albumuser_shared_to (
    id integer NOT NULL,
    albumuser_id integer NOT NULL,
    user_id integer NOT NULL
);

ALTER TABLE public.api_albumuser_shared_to ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_albumuser_shared_to_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.api_albumusershare (
    id integer NOT NULL,
    enabled boolean NOT NULL,
    slug character varying(64),
    expires_at timestamp with time zone,
    album_id integer NOT NULL,
    share_location boolean,
    share_camera_info boolean,
    share_timestamps boolean,
    share_captions boolean,
    share_faces boolean
);

ALTER TABLE public.api_albumusershare ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_albumusershare_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.api_cluster (
    id integer NOT NULL,
    mean_face_encoding text NOT NULL,
    cluster_id integer,
    name text,
    person_id integer,
    owner_id integer
);

ALTER TABLE public.api_cluster ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_cluster_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.api_deletionlog (
    id integer NOT NULL,
    entity character varying(32) NOT NULL,
    entity_id character varying(64) NOT NULL,
    deleted_at timestamp with time zone NOT NULL,
    owner_id integer NOT NULL
);

ALTER TABLE public.api_deletionlog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_deletionlog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.api_duplicate (
    id uuid NOT NULL,
    duplicate_type character varying(20) NOT NULL,
    review_status character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    reviewed_at timestamp with time zone,
    similarity_score double precision,
    potential_savings bigint NOT NULL,
    trashed_count integer NOT NULL,
    note text,
    kept_photo_id uuid,
    owner_id integer NOT NULL
);

CREATE TABLE public.api_emailconfig (
    id integer NOT NULL,
    provider character varying(32) NOT NULL,
    from_email character varying(255) NOT NULL,
    host character varying(255) NOT NULL,
    port integer NOT NULL,
    use_tls boolean NOT NULL,
    use_ssl boolean NOT NULL,
    username character varying(255) NOT NULL,
    secret bytea NOT NULL,
    CONSTRAINT api_emailconfig_port_check CHECK ((port >= 0))
);

ALTER TABLE public.api_emailconfig ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_emailconfig_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.api_face (
    id integer NOT NULL,
    image character varying(100),
    cluster_probability double precision NOT NULL,
    location_top integer NOT NULL,
    location_bottom integer NOT NULL,
    location_left integer NOT NULL,
    location_right integer NOT NULL,
    encoding text NOT NULL,
    person_id integer,
    cluster_id integer,
    classification_probability double precision NOT NULL,
    deleted boolean NOT NULL,
    classification_person_id integer,
    cluster_person_id integer,
    photo_id uuid
);

ALTER TABLE public.api_face ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_face_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.api_file (
    hash character varying(64) NOT NULL,
    path text NOT NULL,
    type integer NOT NULL,
    missing boolean NOT NULL,
    CONSTRAINT api_file_type_check CHECK ((type >= 0))
);

CREATE TABLE public.api_file_embedded_media (
    id integer NOT NULL,
    from_file_id character varying(64) NOT NULL,
    to_file_id character varying(64) NOT NULL
);

ALTER TABLE public.api_file_embedded_media ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_file_embedded_media_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.api_longrunningjob (
    id integer NOT NULL,
    job_type integer NOT NULL,
    finished boolean NOT NULL,
    failed boolean NOT NULL,
    job_id character varying(36) NOT NULL,
    queued_at timestamp with time zone NOT NULL,
    started_at timestamp with time zone,
    finished_at timestamp with time zone,
    started_by_id integer NOT NULL,
    progress_current integer NOT NULL,
    progress_target integer NOT NULL,
    progress_step character varying(100),
    result jsonb,
    cancelled boolean NOT NULL,
    CONSTRAINT api_longrunningjob_job_type_check CHECK ((job_type >= 0)),
    CONSTRAINT api_longrunningjob_progress_current_check CHECK ((progress_current >= 0)),
    CONSTRAINT api_longrunningjob_progress_target_check CHECK ((progress_target >= 0))
);

ALTER TABLE public.api_longrunningjob ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_longrunningjob_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.api_metadataedit (
    id uuid NOT NULL,
    field_name character varying(100) NOT NULL,
    old_value jsonb,
    new_value jsonb,
    synced_to_file boolean NOT NULL,
    synced_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    photo_id uuid NOT NULL,
    user_id integer NOT NULL
);

CREATE TABLE public.api_metadatafile (
    id uuid NOT NULL,
    file_type character varying(10) NOT NULL,
    source character varying(20) NOT NULL,
    priority integer NOT NULL,
    creator_software character varying(100),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    file_id character varying(64) NOT NULL,
    photo_id uuid NOT NULL
);

CREATE TABLE public.api_person (
    id integer NOT NULL,
    name character varying(128) NOT NULL,
    kind character varying(10) NOT NULL,
    cluster_owner_id integer,
    face_count integer NOT NULL,
    cover_face_id integer,
    cover_photo_id uuid,
    last_modified timestamp with time zone NOT NULL
);

ALTER TABLE public.api_person ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_person_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.api_photo (
    image_hash character varying(64) NOT NULL,
    added_on timestamp with time zone NOT NULL,
    exif_gps_lat double precision,
    exif_gps_lon double precision,
    exif_timestamp timestamp with time zone,
    exif_json jsonb,
    geolocation_json jsonb,
    hidden boolean NOT NULL,
    public boolean NOT NULL,
    owner_id integer NOT NULL,
    video boolean NOT NULL,
    clip_embeddings_magnitude double precision,
    rating integer NOT NULL,
    video_length text,
    in_trashcan boolean NOT NULL,
    "timestamp" timestamp with time zone,
    size bigint NOT NULL,
    main_file_id character varying(64),
    last_modified timestamp with time zone NOT NULL,
    removed boolean NOT NULL,
    clip_embeddings jsonb,
    perceptual_hash character varying(64),
    exif_timestamp_subsec character varying(10),
    image_sequence_number integer,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    local_orientation integer NOT NULL,
    is_screenshot boolean NOT NULL,
    is_document boolean NOT NULL,
    category_source character varying(8) NOT NULL
);

CREATE TABLE public.api_photo_caption (
    captions_json jsonb,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    photo_id uuid NOT NULL
);

CREATE TABLE public.api_photo_duplicates (
    id integer NOT NULL,
    photo_id uuid NOT NULL,
    duplicate_id uuid NOT NULL
);

ALTER TABLE public.api_photo_duplicates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_photo_duplicates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.api_photo_files (
    id integer NOT NULL,
    file_id character varying(64) NOT NULL,
    photo_id uuid
);

ALTER TABLE public.api_photo_files ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_photo_files_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.api_photo_ocr (
    photo_id uuid NOT NULL,
    text text,
    blocks jsonb NOT NULL,
    engine character varying(64) NOT NULL,
    mean_confidence double precision,
    text_area_fraction double precision,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    source_width integer,
    source_height integer,
    CONSTRAINT api_photo_ocr_source_height_check CHECK ((source_height >= 0)),
    CONSTRAINT api_photo_ocr_source_width_check CHECK ((source_width >= 0))
);

CREATE TABLE public.api_photo_search (
    search_captions text,
    search_location text,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    photo_id uuid NOT NULL
);

CREATE TABLE public.api_photo_shared_to (
    id integer NOT NULL,
    user_id integer NOT NULL,
    photo_id uuid
);

ALTER TABLE public.api_photo_shared_to ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_photo_shared_to_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.api_photo_stacks (
    id integer NOT NULL,
    photo_id uuid NOT NULL,
    photostack_id uuid NOT NULL
);

ALTER TABLE public.api_photo_stacks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_photo_stacks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.api_photometadata (
    id uuid NOT NULL,
    aperture double precision,
    shutter_speed character varying(20),
    shutter_speed_seconds double precision,
    iso integer,
    focal_length double precision,
    focal_length_35mm integer,
    exposure_compensation double precision,
    flash_fired boolean,
    metering_mode character varying(50),
    white_balance character varying(50),
    camera_make character varying(100),
    camera_model character varying(100),
    lens_make character varying(100),
    lens_model character varying(100),
    serial_number character varying(100),
    width integer,
    height integer,
    orientation integer,
    color_space character varying(50),
    bit_depth integer,
    date_taken timestamp with time zone,
    date_taken_subsec character varying(10),
    date_modified timestamp with time zone,
    timezone_offset character varying(10),
    gps_latitude double precision,
    gps_longitude double precision,
    gps_altitude double precision,
    location_country character varying(100),
    location_state character varying(100),
    location_city character varying(100),
    location_address text,
    title character varying(500),
    caption text,
    keywords jsonb,
    rating integer,
    copyright text,
    creator character varying(200),
    source character varying(20) NOT NULL,
    raw_exif jsonb,
    raw_xmp jsonb,
    raw_iptc jsonb,
    version integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    photo_id uuid NOT NULL
);

CREATE TABLE public.api_photoshare (
    id integer NOT NULL,
    enabled boolean NOT NULL,
    slug character varying(64),
    created_at timestamp with time zone NOT NULL,
    photo_id uuid NOT NULL
);

ALTER TABLE public.api_photoshare ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_photoshare_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.api_photostack (
    id uuid NOT NULL,
    stack_type character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    sequence_start timestamp with time zone,
    sequence_end timestamp with time zone,
    owner_id integer NOT NULL,
    primary_photo_id uuid
);

CREATE TABLE public.api_stackreview (
    decision character varying(20) NOT NULL,
    trashed_count integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    reviewed_at timestamp with time zone,
    note text,
    kept_photo_id uuid,
    reviewer_id integer NOT NULL,
    stack_id uuid NOT NULL,
    uuid uuid NOT NULL,
    id bigint NOT NULL
);

ALTER TABLE public.api_stackreview ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_stackreview_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.api_tag (
    id integer NOT NULL,
    name character varying(512) NOT NULL,
    photo_count integer NOT NULL,
    owner_id integer NOT NULL,
    last_modified timestamp with time zone NOT NULL
);

ALTER TABLE public.api_tag ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.api_tag_photos (
    id integer NOT NULL,
    tag_id integer NOT NULL,
    photo_id uuid NOT NULL
);

ALTER TABLE public.api_tag_photos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_tag_photos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.api_thumbnail (
    thumbnail_big character varying(100) NOT NULL,
    square_thumbnail character varying(100) NOT NULL,
    square_thumbnail_small character varying(100) NOT NULL,
    aspect_ratio double precision,
    dominant_color text,
    photo_id uuid NOT NULL
);

CREATE TABLE public.api_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    scan_directory character varying(512) NOT NULL,
    avatar character varying(100),
    nextcloud_server_address character varying(200) NOT NULL,
    nextcloud_username character varying(64) NOT NULL,
    nextcloud_app_password bytea NOT NULL,
    nextcloud_scan_directory character varying(512) NOT NULL,
    confidence double precision NOT NULL,
    semantic_search_topk integer NOT NULL,
    favorite_min_rating integer NOT NULL,
    image_scale double precision NOT NULL,
    save_metadata_to_disk text NOT NULL,
    transcode_videos boolean NOT NULL,
    datetime_rules jsonb NOT NULL,
    default_timezone text NOT NULL,
    confidence_person double precision NOT NULL,
    public_sharing boolean NOT NULL,
    confidence_unknown_face double precision NOT NULL,
    face_recognition_model text NOT NULL,
    min_cluster_size integer NOT NULL,
    cluster_selection_epsilon double precision NOT NULL,
    min_samples integer NOT NULL,
    llm_settings jsonb NOT NULL,
    text_alignment text NOT NULL,
    header_size text NOT NULL,
    skip_raw_files boolean NOT NULL,
    slideshow_interval integer NOT NULL,
    duplicate_clear_existing boolean NOT NULL,
    duplicate_sensitivity text NOT NULL,
    burst_detection_rules jsonb NOT NULL,
    stack_raw_jpeg boolean NOT NULL,
    public_sharing_defaults jsonb NOT NULL,
    save_face_tags_to_disk boolean NOT NULL,
    last_modified timestamp with time zone NOT NULL
);

ALTER TABLE public.api_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.chunked_upload_chunkedupload (
    id integer NOT NULL,
    upload_id character varying(32) NOT NULL,
    file character varying(255) NOT NULL,
    filename character varying(255) NOT NULL,
    "offset" bigint NOT NULL,
    created_on timestamp with time zone NOT NULL,
    status smallint NOT NULL,
    completed_on timestamp with time zone,
    user_id integer,
    CONSTRAINT chunked_upload_chunkedupload_status_check CHECK ((status >= 0))
);

ALTER TABLE public.chunked_upload_chunkedupload ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chunked_upload_chunkedupload_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.api_albumauto_photos
    ADD CONSTRAINT api_albumauto_photos_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.api_albumauto
    ADD CONSTRAINT api_albumauto_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.api_albumauto_shared_to
    ADD CONSTRAINT api_albumauto_shared_to_albumauto_id_user_id_332148f8_uniq UNIQUE (albumauto_id, user_id);

ALTER TABLE ONLY public.api_albumauto_shared_to
    ADD CONSTRAINT api_albumauto_shared_to_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.api_albumauto
    ADD CONSTRAINT api_albumauto_timestamp_owner_id_314a1d7f_uniq UNIQUE ("timestamp", owner_id);

ALTER TABLE ONLY public.api_albumdate
    ADD CONSTRAINT api_albumdate_date_owner_id_5ba3d470_uniq UNIQUE (date, owner_id);

ALTER TABLE ONLY public.api_albumdate_photos
    ADD CONSTRAINT api_albumdate_photos_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.api_albumdate
    ADD CONSTRAINT api_albumdate_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.api_albumdate_shared_to
    ADD CONSTRAINT api_albumdate_shared_to_albumdate_id_user_id_7eb2d2bf_uniq UNIQUE (albumdate_id, user_id);

ALTER TABLE ONLY public.api_albumdate_shared_to
    ADD CONSTRAINT api_albumdate_shared_to_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.api_albumplace_photos
    ADD CONSTRAINT api_albumplace_photos_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.api_albumplace
    ADD CONSTRAINT api_albumplace_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.api_albumplace_shared_to
    ADD CONSTRAINT api_albumplace_shared_to_albumplace_id_user_id_878b44ef_uniq UNIQUE (albumplace_id, user_id);

ALTER TABLE ONLY public.api_albumplace_shared_to
    ADD CONSTRAINT api_albumplace_shared_to_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.api_albumplace
    ADD CONSTRAINT api_albumplace_title_owner_id_851514f9_uniq UNIQUE (title, owner_id);

ALTER TABLE ONLY public.api_albumthing_cover_photos
    ADD CONSTRAINT api_albumthing_cover_photos_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.api_albumthing_photos
    ADD CONSTRAINT api_albumthing_photos_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.api_albumthing
    ADD CONSTRAINT api_albumthing_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.api_albumthing_shared_to
    ADD CONSTRAINT api_albumthing_shared_to_albumthing_id_user_id_05b7dbd1_uniq UNIQUE (albumthing_id, user_id);

ALTER TABLE ONLY public.api_albumthing_shared_to
    ADD CONSTRAINT api_albumthing_shared_to_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.api_albumuser_photos
    ADD CONSTRAINT api_albumuser_photos_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.api_albumuser
    ADD CONSTRAINT api_albumuser_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.api_albumuser_shared_to
    ADD CONSTRAINT api_albumuser_shared_to_albumuser_id_user_id_3c6a4938_uniq UNIQUE (albumuser_id, user_id);

ALTER TABLE ONLY public.api_albumuser_shared_to
    ADD CONSTRAINT api_albumuser_shared_to_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.api_albumuser
    ADD CONSTRAINT api_albumuser_title_owner_id_ef2e4db4_uniq UNIQUE (title, owner_id);

ALTER TABLE ONLY public.api_albumusershare
    ADD CONSTRAINT api_albumusershare_album_id_key UNIQUE (album_id);

ALTER TABLE ONLY public.api_albumusershare
    ADD CONSTRAINT api_albumusershare_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.api_albumusershare
    ADD CONSTRAINT api_albumusershare_slug_key UNIQUE (slug);

ALTER TABLE ONLY public.api_cluster
    ADD CONSTRAINT api_cluster_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.api_deletionlog
    ADD CONSTRAINT api_deletionlog_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.api_duplicate
    ADD CONSTRAINT api_duplicate_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.api_emailconfig
    ADD CONSTRAINT api_emailconfig_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.api_face
    ADD CONSTRAINT api_face_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.api_file_embedded_media
    ADD CONSTRAINT api_file_embedded_media_from_file_id_to_file_id_dda3a651_uniq UNIQUE (from_file_id, to_file_id);

ALTER TABLE ONLY public.api_file_embedded_media
    ADD CONSTRAINT api_file_embedded_media_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.api_file
    ADD CONSTRAINT api_file_path_5dee9904_uniq UNIQUE (path);

ALTER TABLE ONLY public.api_file
    ADD CONSTRAINT api_file_pkey PRIMARY KEY (hash);

ALTER TABLE ONLY public.api_longrunningjob
    ADD CONSTRAINT api_longrunningjob_job_id_key UNIQUE (job_id);

ALTER TABLE ONLY public.api_longrunningjob
    ADD CONSTRAINT api_longrunningjob_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.api_metadataedit
    ADD CONSTRAINT api_metadataedit_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.api_metadatafile
    ADD CONSTRAINT api_metadatafile_file_id_key UNIQUE (file_id);

ALTER TABLE ONLY public.api_metadatafile
    ADD CONSTRAINT api_metadatafile_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.api_person
    ADD CONSTRAINT api_person_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.api_photo_caption
    ADD CONSTRAINT api_photo_caption_pkey PRIMARY KEY (photo_id);

ALTER TABLE ONLY public.api_photo_duplicates
    ADD CONSTRAINT api_photo_duplicates_photo_id_duplicate_id_9dd9906e_uniq UNIQUE (photo_id, duplicate_id);

ALTER TABLE ONLY public.api_photo_duplicates
    ADD CONSTRAINT api_photo_duplicates_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.api_photo_files
    ADD CONSTRAINT api_photo_files_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.api_photo_ocr
    ADD CONSTRAINT api_photo_ocr_pkey PRIMARY KEY (photo_id);

ALTER TABLE ONLY public.api_photo
    ADD CONSTRAINT api_photo_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.api_photo_search
    ADD CONSTRAINT api_photo_search_pkey PRIMARY KEY (photo_id);

ALTER TABLE ONLY public.api_photo_shared_to
    ADD CONSTRAINT api_photo_shared_to_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.api_photo_stacks
    ADD CONSTRAINT api_photo_stacks_photo_id_photostack_id_237b9c5b_uniq UNIQUE (photo_id, photostack_id);

ALTER TABLE ONLY public.api_photo_stacks
    ADD CONSTRAINT api_photo_stacks_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.api_photometadata
    ADD CONSTRAINT api_photometadata_photo_id_key UNIQUE (photo_id);

ALTER TABLE ONLY public.api_photometadata
    ADD CONSTRAINT api_photometadata_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.api_photoshare
    ADD CONSTRAINT api_photoshare_photo_id_key UNIQUE (photo_id);

ALTER TABLE ONLY public.api_photoshare
    ADD CONSTRAINT api_photoshare_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.api_photoshare
    ADD CONSTRAINT api_photoshare_slug_key UNIQUE (slug);

ALTER TABLE ONLY public.api_photostack
    ADD CONSTRAINT api_photostack_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.api_stackreview
    ADD CONSTRAINT api_stackreview_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.api_stackreview
    ADD CONSTRAINT api_stackreview_stack_id_key UNIQUE (stack_id);

ALTER TABLE ONLY public.api_stackreview
    ADD CONSTRAINT api_stackreview_uuid_4b563f53_uniq UNIQUE (uuid);

ALTER TABLE ONLY public.api_tag_photos
    ADD CONSTRAINT api_tag_photos_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.api_tag_photos
    ADD CONSTRAINT api_tag_photos_tag_id_photo_id_cf87bcf0_uniq UNIQUE (tag_id, photo_id);

ALTER TABLE ONLY public.api_tag
    ADD CONSTRAINT api_tag_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.api_thumbnail
    ADD CONSTRAINT api_thumbnail_pkey PRIMARY KEY (photo_id);

ALTER TABLE ONLY public.api_user
    ADD CONSTRAINT api_user_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.api_user
    ADD CONSTRAINT api_user_username_key UNIQUE (username);

ALTER TABLE ONLY public.chunked_upload_chunkedupload
    ADD CONSTRAINT chunked_upload_chunkedupload_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.chunked_upload_chunkedupload
    ADD CONSTRAINT chunked_upload_chunkedupload_upload_id_key UNIQUE (upload_id);

ALTER TABLE ONLY public.api_albumthing
    ADD CONSTRAINT "unique AlbumThing" UNIQUE (title, thing_type, owner_id);

ALTER TABLE ONLY public.api_tag
    ADD CONSTRAINT "unique Tag" UNIQUE (name, owner_id);

CREATE INDEX api_albumauto_created_on_0c5c92b6 ON public.api_albumauto USING btree (created_on);

CREATE INDEX api_albumauto_favorited_68743c7f ON public.api_albumauto USING btree (favorited);

CREATE INDEX api_albumauto_last_modified_97dd0117 ON public.api_albumauto USING btree (last_modified);

CREATE INDEX api_albumauto_owner_id_e83d8f88 ON public.api_albumauto USING btree (owner_id);

CREATE INDEX api_albumauto_photos_albumauto_id_86a09378 ON public.api_albumauto_photos USING btree (albumauto_id);

CREATE UNIQUE INDEX api_albumauto_photos_albumauto_id_photo_id_uniq ON public.api_albumauto_photos USING btree (albumauto_id, photo_id);

CREATE INDEX api_albumauto_photos_photo_id_idx ON public.api_albumauto_photos USING btree (photo_id);

CREATE INDEX api_albumauto_shared_to_albumauto_id_94c13ddb ON public.api_albumauto_shared_to USING btree (albumauto_id);

CREATE INDEX api_albumauto_shared_to_user_id_cf09f962 ON public.api_albumauto_shared_to USING btree (user_id);

CREATE INDEX api_albumauto_timestamp_584f1589 ON public.api_albumauto USING btree ("timestamp");

CREATE INDEX api_albumdate_date_b825aef0 ON public.api_albumdate USING btree (date);

CREATE INDEX api_albumdate_favorited_9f3d4007 ON public.api_albumdate USING btree (favorited);

CREATE INDEX api_albumdate_location_dbba885f ON public.api_albumdate USING btree (location);

CREATE INDEX api_albumdate_owner_id_2745f84a ON public.api_albumdate USING btree (owner_id);

CREATE INDEX api_albumdate_photos_albumdate_id_cd458c5d ON public.api_albumdate_photos USING btree (albumdate_id);

CREATE UNIQUE INDEX api_albumdate_photos_albumdate_id_photo_id_uniq ON public.api_albumdate_photos USING btree (albumdate_id, photo_id);

CREATE INDEX api_albumdate_photos_photo_id_idx ON public.api_albumdate_photos USING btree (photo_id);

CREATE INDEX api_albumdate_shared_to_albumdate_id_6d32c8dc ON public.api_albumdate_shared_to USING btree (albumdate_id);

CREATE INDEX api_albumdate_shared_to_user_id_9ccf440e ON public.api_albumdate_shared_to USING btree (user_id);

CREATE INDEX api_albumdate_title_c0a886cc ON public.api_albumdate USING btree (title);

CREATE INDEX api_albumdate_title_c0a886cc_like ON public.api_albumdate USING btree (title varchar_pattern_ops);

CREATE INDEX api_albumplace_favorited_ddb4a4c3 ON public.api_albumplace USING btree (favorited);

CREATE INDEX api_albumplace_geolocation_level_35fbd31f ON public.api_albumplace USING btree (geolocation_level);

CREATE INDEX api_albumplace_last_modified_09b846bd ON public.api_albumplace USING btree (last_modified);

CREATE INDEX api_albumplace_owner_id_6bd352e3 ON public.api_albumplace USING btree (owner_id);

CREATE INDEX api_albumplace_photos_albumplace_id_e0d81074 ON public.api_albumplace_photos USING btree (albumplace_id);

CREATE UNIQUE INDEX api_albumplace_photos_albumplace_id_photo_id_uniq ON public.api_albumplace_photos USING btree (albumplace_id, photo_id);

CREATE INDEX api_albumplace_photos_photo_id_idx ON public.api_albumplace_photos USING btree (photo_id);

CREATE INDEX api_albumplace_shared_to_albumplace_id_1c57a597 ON public.api_albumplace_shared_to USING btree (albumplace_id);

CREATE INDEX api_albumplace_shared_to_user_id_82c38c75 ON public.api_albumplace_shared_to USING btree (user_id);

CREATE INDEX api_albumplace_title_6cafeb2d ON public.api_albumplace USING btree (title);

CREATE INDEX api_albumplace_title_6cafeb2d_like ON public.api_albumplace USING btree (title varchar_pattern_ops);

CREATE INDEX api_albumthing_cover_photos_albumthing_id_aa548eb5 ON public.api_albumthing_cover_photos USING btree (albumthing_id);

CREATE UNIQUE INDEX api_albumthing_cover_photos_albumthing_id_photo_id_uniq ON public.api_albumthing_cover_photos USING btree (albumthing_id, photo_id);

CREATE INDEX api_albumthing_cover_photos_photo_id_idx ON public.api_albumthing_cover_photos USING btree (photo_id);

CREATE INDEX api_albumthing_favorited_70dc6840 ON public.api_albumthing USING btree (favorited);

CREATE INDEX api_albumthing_last_modified_6aab255b ON public.api_albumthing USING btree (last_modified);

CREATE INDEX api_albumthing_owner_id_b61d1b00 ON public.api_albumthing USING btree (owner_id);

CREATE INDEX api_albumthing_photos_albumthing_id_00fcb0f3 ON public.api_albumthing_photos USING btree (albumthing_id);

CREATE UNIQUE INDEX api_albumthing_photos_albumthing_id_photo_id_uniq ON public.api_albumthing_photos USING btree (albumthing_id, photo_id);

CREATE INDEX api_albumthing_photos_photo_id_idx ON public.api_albumthing_photos USING btree (photo_id);

CREATE INDEX api_albumthing_shared_to_albumthing_id_b81ac20a ON public.api_albumthing_shared_to USING btree (albumthing_id);

CREATE INDEX api_albumthing_shared_to_user_id_40c200a0 ON public.api_albumthing_shared_to USING btree (user_id);

CREATE INDEX api_albumthing_thing_type_924227a6 ON public.api_albumthing USING btree (thing_type);

CREATE INDEX api_albumthing_thing_type_924227a6_like ON public.api_albumthing USING btree (thing_type varchar_pattern_ops);

CREATE INDEX api_albumthing_title_e9b82e55 ON public.api_albumthing USING btree (title);

CREATE INDEX api_albumthing_title_e9b82e55_like ON public.api_albumthing USING btree (title varchar_pattern_ops);

CREATE INDEX api_albumuser_cover_photo_id_idx ON public.api_albumuser USING btree (cover_photo_id);

CREATE INDEX api_albumuser_created_on_0807bc0f ON public.api_albumuser USING btree (created_on);

CREATE INDEX api_albumuser_favorited_15de9e16 ON public.api_albumuser USING btree (favorited);

CREATE INDEX api_albumuser_last_modified_fa65eb43 ON public.api_albumuser USING btree (last_modified);

CREATE INDEX api_albumuser_owner_id_df3b5510 ON public.api_albumuser USING btree (owner_id);

CREATE INDEX api_albumuser_photos_albumuser_id_80614a80 ON public.api_albumuser_photos USING btree (albumuser_id);

CREATE UNIQUE INDEX api_albumuser_photos_albumuser_id_photo_id_uniq ON public.api_albumuser_photos USING btree (albumuser_id, photo_id);

CREATE INDEX api_albumuser_photos_photo_id_idx ON public.api_albumuser_photos USING btree (photo_id);

CREATE INDEX api_albumuser_shared_to_albumuser_id_037fbb43 ON public.api_albumuser_shared_to USING btree (albumuser_id);

CREATE INDEX api_albumuser_shared_to_user_id_60ab3643 ON public.api_albumuser_shared_to USING btree (user_id);

CREATE INDEX api_albumusershare_enabled_a7f334cf ON public.api_albumusershare USING btree (enabled);

CREATE INDEX api_albumusershare_expires_at_2a6e99b3 ON public.api_albumusershare USING btree (expires_at);

CREATE INDEX api_albumusershare_slug_4ffa81fc_like ON public.api_albumusershare USING btree (slug varchar_pattern_ops);

CREATE INDEX api_cluster_owner_id_ddf57161 ON public.api_cluster USING btree (owner_id);

CREATE INDEX api_cluster_person_id_de1e4b3c ON public.api_cluster USING btree (person_id);

CREATE INDEX api_deletionlog_deleted_at_0d4cb74b ON public.api_deletionlog USING btree (deleted_at);

CREATE INDEX api_deletionlog_entity_0bdb6728 ON public.api_deletionlog USING btree (entity);

CREATE INDEX api_deletionlog_entity_0bdb6728_like ON public.api_deletionlog USING btree (entity varchar_pattern_ops);

CREATE INDEX api_deletionlog_owner_id_fe3fb028 ON public.api_deletionlog USING btree (owner_id);

CREATE INDEX api_duplica_owner_i_039fa3_idx ON public.api_duplicate USING btree (owner_id, review_status);

CREATE INDEX api_duplica_owner_i_78a3a4_idx ON public.api_duplicate USING btree (owner_id, duplicate_type);

CREATE INDEX api_duplicate_duplicate_type_155b26e2 ON public.api_duplicate USING btree (duplicate_type);

CREATE INDEX api_duplicate_duplicate_type_155b26e2_like ON public.api_duplicate USING btree (duplicate_type varchar_pattern_ops);

CREATE INDEX api_duplicate_kept_photo_id_e0c33ed4 ON public.api_duplicate USING btree (kept_photo_id);

CREATE INDEX api_duplicate_owner_id_3d0c7327 ON public.api_duplicate USING btree (owner_id);

CREATE INDEX api_duplicate_review_status_85cc6bfd ON public.api_duplicate USING btree (review_status);

CREATE INDEX api_duplicate_review_status_85cc6bfd_like ON public.api_duplicate USING btree (review_status varchar_pattern_ops);

CREATE INDEX api_face_classification_person_id_98d44049 ON public.api_face USING btree (classification_person_id);

CREATE INDEX api_face_classification_probability_688e8040 ON public.api_face USING btree (classification_probability);

CREATE INDEX api_face_cluster_id_7cc7025a ON public.api_face USING btree (cluster_id);

CREATE INDEX api_face_cluster_person_id_0a0b4811 ON public.api_face USING btree (cluster_person_id);

CREATE INDEX api_face_cluster_probability_89b3b2e2 ON public.api_face USING btree (cluster_probability);

CREATE INDEX api_face_person_id_6a0347bd ON public.api_face USING btree (person_id);

CREATE INDEX api_face_photo_id_idx ON public.api_face USING btree (photo_id);

CREATE INDEX api_file_embedded_media_from_file_id_9cd74d0d ON public.api_file_embedded_media USING btree (from_file_id);

CREATE INDEX api_file_embedded_media_from_file_id_9cd74d0d_like ON public.api_file_embedded_media USING btree (from_file_id varchar_pattern_ops);

CREATE INDEX api_file_embedded_media_to_file_id_69f18a1c ON public.api_file_embedded_media USING btree (to_file_id);

CREATE INDEX api_file_embedded_media_to_file_id_69f18a1c_like ON public.api_file_embedded_media USING btree (to_file_id varchar_pattern_ops);

CREATE INDEX api_file_hash_4c68c93a_like ON public.api_file USING btree (hash varchar_pattern_ops);

CREATE INDEX api_file_path_5dee9904_like ON public.api_file USING btree (path text_pattern_ops);

CREATE INDEX api_longrunningjob_job_id_6b7cfb86_like ON public.api_longrunningjob USING btree (job_id varchar_pattern_ops);

CREATE INDEX api_longrunningjob_started_by_id_acef418a ON public.api_longrunningjob USING btree (started_by_id);

CREATE INDEX api_metadat_photo_i_21e478_idx ON public.api_metadataedit USING btree (photo_id, created_at DESC);

CREATE INDEX api_metadataedit_photo_id_38524cb3 ON public.api_metadataedit USING btree (photo_id);

CREATE INDEX api_metadataedit_user_id_83a820d9 ON public.api_metadataedit USING btree (user_id);

CREATE INDEX api_metadatafile_file_id_7d12cb10_like ON public.api_metadatafile USING btree (file_id varchar_pattern_ops);

CREATE INDEX api_metadatafile_photo_id_76028904 ON public.api_metadatafile USING btree (photo_id);

CREATE INDEX api_person_cluster_owner_id_90df41de ON public.api_person USING btree (cluster_owner_id);

CREATE INDEX api_person_cover_face_id_bdd48874 ON public.api_person USING btree (cover_face_id);

CREATE INDEX api_person_cover_photo_id_idx ON public.api_person USING btree (cover_photo_id);

CREATE INDEX api_person_last_modified_c4a91103 ON public.api_person USING btree (last_modified);

CREATE INDEX api_person_name_8e1ce669 ON public.api_person USING btree (name);

CREATE INDEX api_person_name_8e1ce669_like ON public.api_person USING btree (name varchar_pattern_ops);

CREATE INDEX api_photo_added_on_ababa57d ON public.api_photo USING btree (added_on);

CREATE INDEX api_photo_caption_captions_json_70c46fb8 ON public.api_photo_caption USING btree (captions_json);

CREATE INDEX api_photo_duplicates_duplicate_id_f06a9493 ON public.api_photo_duplicates USING btree (duplicate_id);

CREATE INDEX api_photo_duplicates_photo_id_e89217df ON public.api_photo_duplicates USING btree (photo_id);

CREATE INDEX api_photo_exif_timestamp_3c113e34 ON public.api_photo USING btree (exif_timestamp);

CREATE INDEX api_photo_files_file_id_b6d5e335 ON public.api_photo_files USING btree (file_id);

CREATE INDEX api_photo_files_file_id_b6d5e335_like ON public.api_photo_files USING btree (file_id varchar_pattern_ops);

CREATE INDEX api_photo_files_photo_id_idx ON public.api_photo_files USING btree (photo_id);

CREATE INDEX api_photo_geolocation_json_dc1b353e ON public.api_photo USING btree (geolocation_json);

CREATE INDEX api_photo_hidden_59a5d521 ON public.api_photo USING btree (hidden);

CREATE INDEX api_photo_image_hash_6b828f4d ON public.api_photo USING btree (image_hash);

CREATE INDEX api_photo_image_hash_6b828f4d_like ON public.api_photo USING btree (image_hash varchar_pattern_ops);

CREATE INDEX api_photo_in_trashcan_516d54a0 ON public.api_photo USING btree (in_trashcan);

CREATE INDEX api_photo_is_document_89ef7db6 ON public.api_photo USING btree (is_document);

CREATE INDEX api_photo_is_screenshot_80bd33f2 ON public.api_photo USING btree (is_screenshot);

CREATE INDEX api_photo_main_file_id_453ba4cc ON public.api_photo USING btree (main_file_id);

CREATE INDEX api_photo_main_file_id_453ba4cc_like ON public.api_photo USING btree (main_file_id varchar_pattern_ops);

CREATE INDEX api_photo_ocr_text_fts ON public.api_photo_ocr USING gin (to_tsvector('simple'::regconfig, COALESCE(text, ''::text)));

CREATE INDEX api_photo_owner_id_234b5551 ON public.api_photo USING btree (owner_id);

CREATE INDEX api_photo_perceptual_hash_1076b9f8 ON public.api_photo USING btree (perceptual_hash);

CREATE INDEX api_photo_perceptual_hash_1076b9f8_like ON public.api_photo USING btree (perceptual_hash varchar_pattern_ops);

CREATE INDEX api_photo_public_d9bcd839 ON public.api_photo USING btree (public);

CREATE INDEX api_photo_rating_53606e2c ON public.api_photo USING btree (rating);

CREATE INDEX api_photo_removed_50380583 ON public.api_photo USING btree (removed);

CREATE INDEX api_photo_search_search_captions_929fb6aa ON public.api_photo_search USING btree (search_captions);

CREATE INDEX api_photo_search_search_captions_929fb6aa_like ON public.api_photo_search USING btree (search_captions text_pattern_ops);

CREATE INDEX api_photo_search_search_location_b864ad60 ON public.api_photo_search USING btree (search_location);

CREATE INDEX api_photo_search_search_location_b864ad60_like ON public.api_photo_search USING btree (search_location text_pattern_ops);

CREATE INDEX api_photo_shared_to_photo_id_idx ON public.api_photo_shared_to USING btree (photo_id);

CREATE INDEX api_photo_shared_to_user_id_0407baf2 ON public.api_photo_shared_to USING btree (user_id);

CREATE INDEX api_photo_stacks_photo_id_db985d09 ON public.api_photo_stacks USING btree (photo_id);

CREATE INDEX api_photo_stacks_photostack_id_dd4eef21 ON public.api_photo_stacks USING btree (photostack_id);

CREATE INDEX api_photo_timestamp_92a676d4 ON public.api_photo USING btree ("timestamp");

CREATE INDEX api_photome_camera__361eac_idx ON public.api_photometadata USING btree (camera_make, camera_model);

CREATE INDEX api_photome_date_ta_35e59b_idx ON public.api_photometadata USING btree (date_taken);

CREATE INDEX api_photome_locatio_1ca8bb_idx ON public.api_photometadata USING btree (location_country, location_city);

CREATE INDEX api_photometadata_aperture_dc8a65b2 ON public.api_photometadata USING btree (aperture);

CREATE INDEX api_photometadata_camera_make_c682ef26 ON public.api_photometadata USING btree (camera_make);

CREATE INDEX api_photometadata_camera_make_c682ef26_like ON public.api_photometadata USING btree (camera_make varchar_pattern_ops);

CREATE INDEX api_photometadata_camera_model_f21bb3a4 ON public.api_photometadata USING btree (camera_model);

CREATE INDEX api_photometadata_camera_model_f21bb3a4_like ON public.api_photometadata USING btree (camera_model varchar_pattern_ops);

CREATE INDEX api_photometadata_date_taken_01f75f9f ON public.api_photometadata USING btree (date_taken);

CREATE INDEX api_photometadata_gps_latitude_208b23c0 ON public.api_photometadata USING btree (gps_latitude);

CREATE INDEX api_photometadata_gps_longitude_58c79d9d ON public.api_photometadata USING btree (gps_longitude);

CREATE INDEX api_photometadata_iso_aa268c5e ON public.api_photometadata USING btree (iso);

CREATE INDEX api_photometadata_lens_model_42c78a22 ON public.api_photometadata USING btree (lens_model);

CREATE INDEX api_photometadata_lens_model_42c78a22_like ON public.api_photometadata USING btree (lens_model varchar_pattern_ops);

CREATE INDEX api_photometadata_location_city_ef02387c ON public.api_photometadata USING btree (location_city);

CREATE INDEX api_photometadata_location_city_ef02387c_like ON public.api_photometadata USING btree (location_city varchar_pattern_ops);

CREATE INDEX api_photometadata_location_country_e2b954aa ON public.api_photometadata USING btree (location_country);

CREATE INDEX api_photometadata_location_country_e2b954aa_like ON public.api_photometadata USING btree (location_country varchar_pattern_ops);

CREATE INDEX api_photometadata_rating_4bc76fc1 ON public.api_photometadata USING btree (rating);

CREATE INDEX api_photoshare_enabled_20ebda70 ON public.api_photoshare USING btree (enabled);

CREATE INDEX api_photoshare_slug_7a28b3d7_like ON public.api_photoshare USING btree (slug varchar_pattern_ops);

CREATE INDEX api_photost_owner_i_40a369_idx ON public.api_photostack USING btree (owner_id, stack_type);

CREATE INDEX api_photostack_owner_id_56d8148c ON public.api_photostack USING btree (owner_id);

CREATE INDEX api_photostack_primary_photo_id_idx ON public.api_photostack USING btree (primary_photo_id);

CREATE INDEX api_photostack_stack_type_979b3dfd ON public.api_photostack USING btree (stack_type);

CREATE INDEX api_photostack_stack_type_979b3dfd_like ON public.api_photostack USING btree (stack_type varchar_pattern_ops);

CREATE INDEX api_stackre_reviewe_48380f_idx ON public.api_stackreview USING btree (reviewer_id, decision);

CREATE INDEX api_stackreview_decision_58df030b ON public.api_stackreview USING btree (decision);

CREATE INDEX api_stackreview_decision_58df030b_like ON public.api_stackreview USING btree (decision varchar_pattern_ops);

CREATE INDEX api_stackreview_kept_photo_id_06685c2e ON public.api_stackreview USING btree (kept_photo_id);

CREATE INDEX api_stackreview_reviewer_id_9a64c2f8 ON public.api_stackreview USING btree (reviewer_id);

CREATE INDEX api_tag_last_modified_6d2b89ff ON public.api_tag USING btree (last_modified);

CREATE INDEX api_tag_name_e0f7a95d ON public.api_tag USING btree (name);

CREATE INDEX api_tag_name_e0f7a95d_like ON public.api_tag USING btree (name varchar_pattern_ops);

CREATE INDEX api_tag_owner_id_18caa483 ON public.api_tag USING btree (owner_id);

CREATE INDEX api_tag_photos_photo_id_1a9bb7a5 ON public.api_tag_photos USING btree (photo_id);

CREATE INDEX api_tag_photos_tag_id_bca93ec5 ON public.api_tag_photos USING btree (tag_id);

CREATE INDEX api_user_confidence_4ccde6b4 ON public.api_user USING btree (confidence);

CREATE INDEX api_user_favorite_min_rating_3cb1cf14 ON public.api_user USING btree (favorite_min_rating);

CREATE INDEX api_user_last_modified_e2efd2d6 ON public.api_user USING btree (last_modified);

CREATE INDEX api_user_nextcloud_scan_directory_a85dc569 ON public.api_user USING btree (nextcloud_scan_directory);

CREATE INDEX api_user_nextcloud_scan_directory_a85dc569_like ON public.api_user USING btree (nextcloud_scan_directory varchar_pattern_ops);

CREATE INDEX api_user_scan_directory_ad54b748 ON public.api_user USING btree (scan_directory);

CREATE INDEX api_user_scan_directory_ad54b748_like ON public.api_user USING btree (scan_directory varchar_pattern_ops);

CREATE INDEX api_user_username_cf4e88d2_like ON public.api_user USING btree (username varchar_pattern_ops);

CREATE INDEX chunked_upload_chunkedupload_upload_id_23703435_like ON public.chunked_upload_chunkedupload USING btree (upload_id varchar_pattern_ops);

CREATE INDEX chunked_upload_chunkedupload_user_id_70ff6dbf ON public.chunked_upload_chunkedupload USING btree (user_id);

CREATE INDEX deletionlog_scope_idx ON public.api_deletionlog USING btree (owner_id, entity, deleted_at);

CREATE INDEX photo_sync_keyset_idx ON public.api_photo USING btree (last_modified, id);

ALTER TABLE ONLY public.api_albumauto
    ADD CONSTRAINT api_albumauto_owner_id_e83d8f88_fk_api_user_id FOREIGN KEY (owner_id) REFERENCES public.api_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_albumauto_photos
    ADD CONSTRAINT api_albumauto_photos_albumauto_id_86a09378_fk_api_albumauto_id FOREIGN KEY (albumauto_id) REFERENCES public.api_albumauto(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_albumauto_photos
    ADD CONSTRAINT api_albumauto_photos_photo_id_fk FOREIGN KEY (photo_id) REFERENCES public.api_photo(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.api_albumauto_shared_to
    ADD CONSTRAINT api_albumauto_shared_albumauto_id_94c13ddb_fk_api_album FOREIGN KEY (albumauto_id) REFERENCES public.api_albumauto(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_albumauto_shared_to
    ADD CONSTRAINT api_albumauto_shared_to_user_id_cf09f962_fk_api_user_id FOREIGN KEY (user_id) REFERENCES public.api_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_albumdate
    ADD CONSTRAINT api_albumdate_owner_id_2745f84a_fk_api_user_id FOREIGN KEY (owner_id) REFERENCES public.api_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_albumdate_photos
    ADD CONSTRAINT api_albumdate_photos_albumdate_id_cd458c5d_fk_api_albumdate_id FOREIGN KEY (albumdate_id) REFERENCES public.api_albumdate(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_albumdate_photos
    ADD CONSTRAINT api_albumdate_photos_photo_id_fk FOREIGN KEY (photo_id) REFERENCES public.api_photo(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.api_albumdate_shared_to
    ADD CONSTRAINT api_albumdate_shared_albumdate_id_6d32c8dc_fk_api_album FOREIGN KEY (albumdate_id) REFERENCES public.api_albumdate(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_albumdate_shared_to
    ADD CONSTRAINT api_albumdate_shared_to_user_id_9ccf440e_fk_api_user_id FOREIGN KEY (user_id) REFERENCES public.api_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_albumplace
    ADD CONSTRAINT api_albumplace_owner_id_6bd352e3_fk_api_user_id FOREIGN KEY (owner_id) REFERENCES public.api_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_albumplace_photos
    ADD CONSTRAINT api_albumplace_photo_albumplace_id_e0d81074_fk_api_album FOREIGN KEY (albumplace_id) REFERENCES public.api_albumplace(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_albumplace_photos
    ADD CONSTRAINT api_albumplace_photos_photo_id_fk FOREIGN KEY (photo_id) REFERENCES public.api_photo(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.api_albumplace_shared_to
    ADD CONSTRAINT api_albumplace_share_albumplace_id_1c57a597_fk_api_album FOREIGN KEY (albumplace_id) REFERENCES public.api_albumplace(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_albumplace_shared_to
    ADD CONSTRAINT api_albumplace_shared_to_user_id_82c38c75_fk_api_user_id FOREIGN KEY (user_id) REFERENCES public.api_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_albumthing_cover_photos
    ADD CONSTRAINT api_albumthing_cover_albumthing_id_aa548eb5_fk_api_album FOREIGN KEY (albumthing_id) REFERENCES public.api_albumthing(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_albumthing_cover_photos
    ADD CONSTRAINT api_albumthing_cover_photos_photo_id_fk FOREIGN KEY (photo_id) REFERENCES public.api_photo(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.api_albumthing
    ADD CONSTRAINT api_albumthing_owner_id_b61d1b00_fk_api_user_id FOREIGN KEY (owner_id) REFERENCES public.api_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_albumthing_photos
    ADD CONSTRAINT api_albumthing_photo_albumthing_id_00fcb0f3_fk_api_album FOREIGN KEY (albumthing_id) REFERENCES public.api_albumthing(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_albumthing_photos
    ADD CONSTRAINT api_albumthing_photos_photo_id_fk FOREIGN KEY (photo_id) REFERENCES public.api_photo(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.api_albumthing_shared_to
    ADD CONSTRAINT api_albumthing_share_albumthing_id_b81ac20a_fk_api_album FOREIGN KEY (albumthing_id) REFERENCES public.api_albumthing(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_albumthing_shared_to
    ADD CONSTRAINT api_albumthing_shared_to_user_id_40c200a0_fk_api_user_id FOREIGN KEY (user_id) REFERENCES public.api_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_albumuser
    ADD CONSTRAINT api_albumuser_cover_photo_id_fk FOREIGN KEY (cover_photo_id) REFERENCES public.api_photo(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.api_albumuser
    ADD CONSTRAINT api_albumuser_owner_id_df3b5510_fk_api_user_id FOREIGN KEY (owner_id) REFERENCES public.api_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_albumuser_photos
    ADD CONSTRAINT api_albumuser_photos_albumuser_id_80614a80_fk_api_albumuser_id FOREIGN KEY (albumuser_id) REFERENCES public.api_albumuser(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_albumuser_photos
    ADD CONSTRAINT api_albumuser_photos_photo_id_fk FOREIGN KEY (photo_id) REFERENCES public.api_photo(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.api_albumuser_shared_to
    ADD CONSTRAINT api_albumuser_shared_albumuser_id_037fbb43_fk_api_album FOREIGN KEY (albumuser_id) REFERENCES public.api_albumuser(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_albumuser_shared_to
    ADD CONSTRAINT api_albumuser_shared_to_user_id_60ab3643_fk_api_user_id FOREIGN KEY (user_id) REFERENCES public.api_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_albumusershare
    ADD CONSTRAINT api_albumusershare_album_id_bb25e1a8_fk_api_albumuser_id FOREIGN KEY (album_id) REFERENCES public.api_albumuser(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_cluster
    ADD CONSTRAINT api_cluster_owner_id_ddf57161_fk_api_user_id FOREIGN KEY (owner_id) REFERENCES public.api_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_cluster
    ADD CONSTRAINT api_cluster_person_id_de1e4b3c_fk_api_person_id FOREIGN KEY (person_id) REFERENCES public.api_person(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_deletionlog
    ADD CONSTRAINT api_deletionlog_owner_id_fe3fb028_fk_api_user_id FOREIGN KEY (owner_id) REFERENCES public.api_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_duplicate
    ADD CONSTRAINT api_duplicate_kept_photo_id_e0c33ed4_fk_api_photo_id FOREIGN KEY (kept_photo_id) REFERENCES public.api_photo(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_duplicate
    ADD CONSTRAINT api_duplicate_owner_id_3d0c7327_fk_api_user_id FOREIGN KEY (owner_id) REFERENCES public.api_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_face
    ADD CONSTRAINT api_face_classification_person_id_98d44049_fk_api_person_id FOREIGN KEY (classification_person_id) REFERENCES public.api_person(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_face
    ADD CONSTRAINT api_face_cluster_id_7cc7025a_fk_api_cluster_id FOREIGN KEY (cluster_id) REFERENCES public.api_cluster(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_face
    ADD CONSTRAINT api_face_cluster_person_id_0a0b4811_fk_api_person_id FOREIGN KEY (cluster_person_id) REFERENCES public.api_person(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_face
    ADD CONSTRAINT api_face_person_id_6a0347bd_fk_api_person_id FOREIGN KEY (person_id) REFERENCES public.api_person(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_face
    ADD CONSTRAINT api_face_photo_id_fk_api_photo FOREIGN KEY (photo_id) REFERENCES public.api_photo(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.api_file_embedded_media
    ADD CONSTRAINT api_file_embedded_media_from_file_id_9cd74d0d_fk_api_file_hash FOREIGN KEY (from_file_id) REFERENCES public.api_file(hash) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_file_embedded_media
    ADD CONSTRAINT api_file_embedded_media_to_file_id_69f18a1c_fk_api_file_hash FOREIGN KEY (to_file_id) REFERENCES public.api_file(hash) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_longrunningjob
    ADD CONSTRAINT api_longrunningjob_started_by_id_acef418a_fk_api_user_id FOREIGN KEY (started_by_id) REFERENCES public.api_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_metadataedit
    ADD CONSTRAINT api_metadataedit_photo_id_38524cb3_fk_api_photo_id FOREIGN KEY (photo_id) REFERENCES public.api_photo(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_metadataedit
    ADD CONSTRAINT api_metadataedit_user_id_83a820d9_fk_api_user_id FOREIGN KEY (user_id) REFERENCES public.api_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_metadatafile
    ADD CONSTRAINT api_metadatafile_file_id_7d12cb10_fk_api_file_hash FOREIGN KEY (file_id) REFERENCES public.api_file(hash) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_metadatafile
    ADD CONSTRAINT api_metadatafile_photo_id_76028904_fk_api_photo_id FOREIGN KEY (photo_id) REFERENCES public.api_photo(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_person
    ADD CONSTRAINT api_person_cluster_owner_id_90df41de_fk_api_user_id FOREIGN KEY (cluster_owner_id) REFERENCES public.api_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_person
    ADD CONSTRAINT api_person_cover_face_id_bdd48874_fk_api_face_id FOREIGN KEY (cover_face_id) REFERENCES public.api_face(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_person
    ADD CONSTRAINT api_person_cover_photo_id_fk FOREIGN KEY (cover_photo_id) REFERENCES public.api_photo(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.api_photo_caption
    ADD CONSTRAINT api_photo_caption_photo_id_fk FOREIGN KEY (photo_id) REFERENCES public.api_photo(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.api_photo_duplicates
    ADD CONSTRAINT api_photo_duplicates_duplicate_id_f06a9493_fk_api_duplicate_id FOREIGN KEY (duplicate_id) REFERENCES public.api_duplicate(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_photo_duplicates
    ADD CONSTRAINT api_photo_duplicates_photo_id_e89217df_fk_api_photo_id FOREIGN KEY (photo_id) REFERENCES public.api_photo(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_photo_files
    ADD CONSTRAINT api_photo_files_file_id_b6d5e335_fk_api_file_hash FOREIGN KEY (file_id) REFERENCES public.api_file(hash) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_photo_files
    ADD CONSTRAINT api_photo_files_photo_id_fk FOREIGN KEY (photo_id) REFERENCES public.api_photo(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.api_photo
    ADD CONSTRAINT api_photo_main_file_id_453ba4cc_fk_api_file_hash FOREIGN KEY (main_file_id) REFERENCES public.api_file(hash) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_photo_ocr
    ADD CONSTRAINT api_photo_ocr_photo_id_b60702bc_fk_api_photo_id FOREIGN KEY (photo_id) REFERENCES public.api_photo(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_photo
    ADD CONSTRAINT api_photo_owner_id_234b5551_fk_api_user_id FOREIGN KEY (owner_id) REFERENCES public.api_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_photo_search
    ADD CONSTRAINT api_photo_search_photo_id_fk FOREIGN KEY (photo_id) REFERENCES public.api_photo(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.api_photo_shared_to
    ADD CONSTRAINT api_photo_shared_to_photo_id_fk FOREIGN KEY (photo_id) REFERENCES public.api_photo(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.api_photo_shared_to
    ADD CONSTRAINT api_photo_shared_to_user_id_0407baf2_fk_api_user_id FOREIGN KEY (user_id) REFERENCES public.api_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_photo_stacks
    ADD CONSTRAINT api_photo_stacks_photo_id_db985d09_fk_api_photo_id FOREIGN KEY (photo_id) REFERENCES public.api_photo(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_photo_stacks
    ADD CONSTRAINT api_photo_stacks_photostack_id_dd4eef21_fk_api_photostack_id FOREIGN KEY (photostack_id) REFERENCES public.api_photostack(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_photometadata
    ADD CONSTRAINT api_photometadata_photo_id_ea31a586_fk_api_photo_id FOREIGN KEY (photo_id) REFERENCES public.api_photo(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_photoshare
    ADD CONSTRAINT api_photoshare_photo_id_3fce8866_fk_api_photo_id FOREIGN KEY (photo_id) REFERENCES public.api_photo(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_photostack
    ADD CONSTRAINT api_photostack_owner_id_56d8148c_fk_api_user_id FOREIGN KEY (owner_id) REFERENCES public.api_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_photostack
    ADD CONSTRAINT api_photostack_primary_photo_id_fk FOREIGN KEY (primary_photo_id) REFERENCES public.api_photo(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.api_stackreview
    ADD CONSTRAINT api_stackreview_kept_photo_id_06685c2e_fk_api_photo_id FOREIGN KEY (kept_photo_id) REFERENCES public.api_photo(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_stackreview
    ADD CONSTRAINT api_stackreview_reviewer_id_9a64c2f8_fk_api_user_id FOREIGN KEY (reviewer_id) REFERENCES public.api_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_stackreview
    ADD CONSTRAINT api_stackreview_stack_id_13409917_fk_api_photostack_id FOREIGN KEY (stack_id) REFERENCES public.api_photostack(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_tag
    ADD CONSTRAINT api_tag_owner_id_18caa483_fk_api_user_id FOREIGN KEY (owner_id) REFERENCES public.api_user(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_tag_photos
    ADD CONSTRAINT api_tag_photos_photo_id_1a9bb7a5_fk_api_photo_id FOREIGN KEY (photo_id) REFERENCES public.api_photo(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_tag_photos
    ADD CONSTRAINT api_tag_photos_tag_id_bca93ec5_fk_api_tag_id FOREIGN KEY (tag_id) REFERENCES public.api_tag(id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ONLY public.api_thumbnail
    ADD CONSTRAINT api_thumbnail_photo_id_fk FOREIGN KEY (photo_id) REFERENCES public.api_photo(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.chunked_upload_chunkedupload
    ADD CONSTRAINT chunked_upload_chunkedupload_user_id_70ff6dbf_fk_api_user_id FOREIGN KEY (user_id) REFERENCES public.api_user(id) DEFERRABLE INITIALLY DEFERRED;

