# Generated by Django 5.2.17 on 2026-09-26 19:56

import api.models.user
import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_cryptography.fields
import uuid
from django.conf import settings
from django.db import migrations, models


# ============================================================================
# Photo UUID primary key (originally 0099_photo_uuid_primary_key)
# ============================================================================
#
# Copied from the replaced migration, except that the SQLite path now writes
# uuid.hex (see _migrate_sqlite). This is the one operation of
# 0001-0100 that could not be squashed away: it changes the schema with raw
# SQL (PostgreSQL) or table recreation (SQLite) rather than through Django
# schema operations, so a fresh database still has to run it to end up with
# exactly the schema long-lived installs have. On a fresh database the tables
# are empty, so only the schema changes do anything.
#
# Every other RunPython/RunSQL of 0001-0100 only transformed existing rows and
# was marked elidable before squashing, which is a no-op on the fresh
# databases this migration is ever applied to.

# ============================================================================
# PostgreSQL raw SQL
# ============================================================================

POSTGRESQL_FORWARD_SQL = """
-- Step 1: Add UUID column to api_photo
ALTER TABLE api_photo ADD COLUMN id UUID DEFAULT gen_random_uuid();
UPDATE api_photo SET id = gen_random_uuid() WHERE id IS NULL;
ALTER TABLE api_photo ALTER COLUMN id SET NOT NULL;

-- Step 2: Create a mapping table for old hash -> new UUID
CREATE TEMP TABLE photo_id_mapping AS
SELECT image_hash, id FROM api_photo;
CREATE INDEX ON photo_id_mapping(image_hash);

-- Step 3: Add new UUID columns to all related tables

-- api_face
ALTER TABLE api_face ADD COLUMN photo_id_new UUID;
UPDATE api_face f SET photo_id_new = m.id
FROM photo_id_mapping m WHERE f.photo_id = m.image_hash;

-- api_photo_shared_to (M2M through table)
ALTER TABLE api_photo_shared_to ADD COLUMN photo_id_new UUID;
UPDATE api_photo_shared_to t SET photo_id_new = m.id
FROM photo_id_mapping m WHERE t.photo_id = m.image_hash;

-- api_photo_files (M2M through table)
ALTER TABLE api_photo_files ADD COLUMN photo_id_new UUID;
UPDATE api_photo_files t SET photo_id_new = m.id
FROM photo_id_mapping m WHERE t.photo_id = m.image_hash;

-- api_albumuser_photos (M2M through table)
ALTER TABLE api_albumuser_photos ADD COLUMN photo_id_new UUID;
UPDATE api_albumuser_photos t SET photo_id_new = m.id
FROM photo_id_mapping m WHERE t.photo_id = m.image_hash;

-- api_albumthing_photos (M2M through table)
ALTER TABLE api_albumthing_photos ADD COLUMN photo_id_new UUID;
UPDATE api_albumthing_photos t SET photo_id_new = m.id
FROM photo_id_mapping m WHERE t.photo_id = m.image_hash;

-- api_albumplace_photos (M2M through table)
ALTER TABLE api_albumplace_photos ADD COLUMN photo_id_new UUID;
UPDATE api_albumplace_photos t SET photo_id_new = m.id
FROM photo_id_mapping m WHERE t.photo_id = m.image_hash;

-- api_albumdate_photos (M2M through table)
ALTER TABLE api_albumdate_photos ADD COLUMN photo_id_new UUID;
UPDATE api_albumdate_photos t SET photo_id_new = m.id
FROM photo_id_mapping m WHERE t.photo_id = m.image_hash;

-- api_albumauto_photos (M2M through table)
ALTER TABLE api_albumauto_photos ADD COLUMN photo_id_new UUID;
UPDATE api_albumauto_photos t SET photo_id_new = m.id
FROM photo_id_mapping m WHERE t.photo_id = m.image_hash;

-- api_person (cover_photo_id)
ALTER TABLE api_person ADD COLUMN cover_photo_id_new UUID;
UPDATE api_person p SET cover_photo_id_new = m.id
FROM photo_id_mapping m WHERE p.cover_photo_id = m.image_hash;

-- api_albumuser (cover_photo_id)
ALTER TABLE api_albumuser ADD COLUMN cover_photo_id_new UUID;
UPDATE api_albumuser a SET cover_photo_id_new = m.id
FROM photo_id_mapping m WHERE a.cover_photo_id = m.image_hash;

-- api_albumthing_cover_photos (M2M through table for cover photos)
ALTER TABLE api_albumthing_cover_photos ADD COLUMN photo_id_new UUID;
UPDATE api_albumthing_cover_photos t SET photo_id_new = m.id
FROM photo_id_mapping m WHERE t.photo_id = m.image_hash;

-- api_thumbnail (OneToOne with PK)
ALTER TABLE api_thumbnail ADD COLUMN photo_id_new UUID;
UPDATE api_thumbnail t SET photo_id_new = m.id
FROM photo_id_mapping m WHERE t.photo_id = m.image_hash;

-- api_photo_caption (OneToOne with PK)
ALTER TABLE api_photo_caption ADD COLUMN photo_id_new UUID;
UPDATE api_photo_caption t SET photo_id_new = m.id
FROM photo_id_mapping m WHERE t.photo_id = m.image_hash;

-- api_photo_search (OneToOne with PK)
ALTER TABLE api_photo_search ADD COLUMN photo_id_new UUID;
UPDATE api_photo_search t SET photo_id_new = m.id
FROM photo_id_mapping m WHERE t.photo_id = m.image_hash;

-- api_photostack (primary_photo_id)
ALTER TABLE api_photostack ADD COLUMN primary_photo_id_new UUID;
UPDATE api_photostack s SET primary_photo_id_new = m.id
FROM photo_id_mapping m WHERE s.primary_photo_id = m.image_hash;

-- Step 4: Drop all FK constraints
ALTER TABLE api_face DROP CONSTRAINT IF EXISTS api_face_photo_id_6f997226_fk_api_photo_image_hash;
ALTER TABLE api_photo_shared_to DROP CONSTRAINT IF EXISTS api_photo_shared_to_photo_id_852923c7_fk_api_photo_image_hash;
ALTER TABLE api_photo_files DROP CONSTRAINT IF EXISTS api_photo_files_photo_id_f4365127_fk_api_photo_image_hash;
ALTER TABLE api_albumuser_photos DROP CONSTRAINT IF EXISTS api_albumuser_photos_photo_id_b9df1b14_fk_api_photo_image_hash;
ALTER TABLE api_albumthing_photos DROP CONSTRAINT IF EXISTS api_albumthing_photos_photo_id_d0832fc3_fk_api_photo_image_hash;
ALTER TABLE api_albumplace_photos DROP CONSTRAINT IF EXISTS api_albumplace_photos_photo_id_8fd88190_fk_api_photo_image_hash;
ALTER TABLE api_albumdate_photos DROP CONSTRAINT IF EXISTS api_albumdate_photos_photo_id_26095959_fk_api_photo_image_hash;
ALTER TABLE api_albumauto_photos DROP CONSTRAINT IF EXISTS api_albumauto_photos_photo_id_3320c2f0_fk_api_photo_image_hash;
ALTER TABLE api_person DROP CONSTRAINT IF EXISTS api_person_cover_photo_id_e0d8a6ab_fk_api_photo_image_hash;
ALTER TABLE api_albumuser DROP CONSTRAINT IF EXISTS api_albumuser_cover_photo_id_69b304ac_fk_api_photo_image_hash;
ALTER TABLE api_albumthing_cover_photos DROP CONSTRAINT IF EXISTS api_albumthing_cover_photo_id_ae113997_fk_api_photo;
ALTER TABLE api_thumbnail DROP CONSTRAINT IF EXISTS api_thumbnail_photo_id_484afcd0_fk_api_photo_image_hash;
ALTER TABLE api_photo_caption DROP CONSTRAINT IF EXISTS api_photo_caption_photo_id_363f8856_fk_api_photo_image_hash;
ALTER TABLE api_photo_search DROP CONSTRAINT IF EXISTS api_photo_search_photo_id_b4055a77_fk_api_photo_image_hash;
ALTER TABLE api_photostack DROP CONSTRAINT IF EXISTS api_photostack_primary_photo_id_a2e9fc96_fk_api_photo;

-- Step 5: Drop PKs on related tables that use photo as PK
ALTER TABLE api_thumbnail DROP CONSTRAINT IF EXISTS api_thumbnail_pkey;
ALTER TABLE api_photo_caption DROP CONSTRAINT IF EXISTS api_photo_caption_pkey;
ALTER TABLE api_photo_search DROP CONSTRAINT IF EXISTS api_photo_search_pkey;

-- Step 6: Drop old PK on api_photo, add new one
ALTER TABLE api_photo DROP CONSTRAINT api_photo_pkey;
ALTER TABLE api_photo ADD PRIMARY KEY (id);

-- Step 7: Add unique constraint on image_hash (for deduplication)
CREATE UNIQUE INDEX api_photo_image_hash_unique ON api_photo(image_hash);

-- Step 8: Drop old FK columns, rename new ones

ALTER TABLE api_face DROP COLUMN photo_id;
ALTER TABLE api_face RENAME COLUMN photo_id_new TO photo_id;

ALTER TABLE api_photo_shared_to DROP COLUMN photo_id;
ALTER TABLE api_photo_shared_to RENAME COLUMN photo_id_new TO photo_id;

ALTER TABLE api_photo_files DROP COLUMN photo_id;
ALTER TABLE api_photo_files RENAME COLUMN photo_id_new TO photo_id;

ALTER TABLE api_albumuser_photos DROP COLUMN photo_id;
ALTER TABLE api_albumuser_photos RENAME COLUMN photo_id_new TO photo_id;

ALTER TABLE api_albumthing_photos DROP COLUMN photo_id;
ALTER TABLE api_albumthing_photos RENAME COLUMN photo_id_new TO photo_id;

ALTER TABLE api_albumplace_photos DROP COLUMN photo_id;
ALTER TABLE api_albumplace_photos RENAME COLUMN photo_id_new TO photo_id;

ALTER TABLE api_albumdate_photos DROP COLUMN photo_id;
ALTER TABLE api_albumdate_photos RENAME COLUMN photo_id_new TO photo_id;

ALTER TABLE api_albumauto_photos DROP COLUMN photo_id;
ALTER TABLE api_albumauto_photos RENAME COLUMN photo_id_new TO photo_id;

ALTER TABLE api_person DROP COLUMN cover_photo_id;
ALTER TABLE api_person RENAME COLUMN cover_photo_id_new TO cover_photo_id;

ALTER TABLE api_albumuser DROP COLUMN cover_photo_id;
ALTER TABLE api_albumuser RENAME COLUMN cover_photo_id_new TO cover_photo_id;

ALTER TABLE api_albumthing_cover_photos DROP COLUMN photo_id;
ALTER TABLE api_albumthing_cover_photos RENAME COLUMN photo_id_new TO photo_id;

ALTER TABLE api_thumbnail DROP COLUMN photo_id;
ALTER TABLE api_thumbnail RENAME COLUMN photo_id_new TO photo_id;
ALTER TABLE api_thumbnail ALTER COLUMN photo_id SET NOT NULL;
ALTER TABLE api_thumbnail ADD PRIMARY KEY (photo_id);

ALTER TABLE api_photo_caption DROP COLUMN photo_id;
ALTER TABLE api_photo_caption RENAME COLUMN photo_id_new TO photo_id;
ALTER TABLE api_photo_caption ALTER COLUMN photo_id SET NOT NULL;
ALTER TABLE api_photo_caption ADD PRIMARY KEY (photo_id);

ALTER TABLE api_photo_search DROP COLUMN photo_id;
ALTER TABLE api_photo_search RENAME COLUMN photo_id_new TO photo_id;
ALTER TABLE api_photo_search ALTER COLUMN photo_id SET NOT NULL;
ALTER TABLE api_photo_search ADD PRIMARY KEY (photo_id);

ALTER TABLE api_photostack DROP COLUMN primary_photo_id;
ALTER TABLE api_photostack RENAME COLUMN primary_photo_id_new TO primary_photo_id;

-- Step 9: Recreate all FK constraints with new UUID type
ALTER TABLE api_face ADD CONSTRAINT api_face_photo_id_fk_api_photo
    FOREIGN KEY (photo_id) REFERENCES api_photo(id) ON DELETE CASCADE;

ALTER TABLE api_photo_shared_to ADD CONSTRAINT api_photo_shared_to_photo_id_fk
    FOREIGN KEY (photo_id) REFERENCES api_photo(id) ON DELETE CASCADE;

ALTER TABLE api_photo_files ADD CONSTRAINT api_photo_files_photo_id_fk
    FOREIGN KEY (photo_id) REFERENCES api_photo(id) ON DELETE CASCADE;

ALTER TABLE api_albumuser_photos ADD CONSTRAINT api_albumuser_photos_photo_id_fk
    FOREIGN KEY (photo_id) REFERENCES api_photo(id) ON DELETE CASCADE;

ALTER TABLE api_albumthing_photos ADD CONSTRAINT api_albumthing_photos_photo_id_fk
    FOREIGN KEY (photo_id) REFERENCES api_photo(id) ON DELETE CASCADE;

ALTER TABLE api_albumplace_photos ADD CONSTRAINT api_albumplace_photos_photo_id_fk
    FOREIGN KEY (photo_id) REFERENCES api_photo(id) ON DELETE CASCADE;

ALTER TABLE api_albumdate_photos ADD CONSTRAINT api_albumdate_photos_photo_id_fk
    FOREIGN KEY (photo_id) REFERENCES api_photo(id) ON DELETE CASCADE;

ALTER TABLE api_albumauto_photos ADD CONSTRAINT api_albumauto_photos_photo_id_fk
    FOREIGN KEY (photo_id) REFERENCES api_photo(id) ON DELETE CASCADE;

ALTER TABLE api_person ADD CONSTRAINT api_person_cover_photo_id_fk
    FOREIGN KEY (cover_photo_id) REFERENCES api_photo(id) ON DELETE SET NULL;

ALTER TABLE api_albumuser ADD CONSTRAINT api_albumuser_cover_photo_id_fk
    FOREIGN KEY (cover_photo_id) REFERENCES api_photo(id) ON DELETE SET NULL;

ALTER TABLE api_albumthing_cover_photos ADD CONSTRAINT api_albumthing_cover_photos_photo_id_fk
    FOREIGN KEY (photo_id) REFERENCES api_photo(id) ON DELETE CASCADE;

ALTER TABLE api_thumbnail ADD CONSTRAINT api_thumbnail_photo_id_fk
    FOREIGN KEY (photo_id) REFERENCES api_photo(id) ON DELETE CASCADE;

ALTER TABLE api_photo_caption ADD CONSTRAINT api_photo_caption_photo_id_fk
    FOREIGN KEY (photo_id) REFERENCES api_photo(id) ON DELETE CASCADE;

ALTER TABLE api_photo_search ADD CONSTRAINT api_photo_search_photo_id_fk
    FOREIGN KEY (photo_id) REFERENCES api_photo(id) ON DELETE CASCADE;

ALTER TABLE api_photostack ADD CONSTRAINT api_photostack_primary_photo_id_fk
    FOREIGN KEY (primary_photo_id) REFERENCES api_photo(id) ON DELETE SET NULL;

-- Step 10: Create indexes for performance
CREATE INDEX api_face_photo_id_idx ON api_face(photo_id);
CREATE INDEX api_photo_shared_to_photo_id_idx ON api_photo_shared_to(photo_id);
CREATE INDEX api_photo_files_photo_id_idx ON api_photo_files(photo_id);
CREATE INDEX api_person_cover_photo_id_idx ON api_person(cover_photo_id);
CREATE INDEX api_albumuser_cover_photo_id_idx ON api_albumuser(cover_photo_id);
CREATE INDEX api_photostack_primary_photo_id_idx ON api_photostack(primary_photo_id);

-- Clean up temp table
DROP TABLE photo_id_mapping;
"""


# ============================================================================
# Squash-specific: flush deferred schema SQL before the raw SQL runs
# ============================================================================

def flush_deferred_schema_sql(apps, schema_editor):
    """Run the index and foreign-key SQL Django has deferred so far.

    Django runs a migration's operations inside one schema editor and only
    executes the deferred SQL (indexes, and on PostgreSQL the foreign-key
    constraints) when that editor closes. In the original chain that happened
    at the end of 0098, so everything 0099's raw SQL drops, renames or copies
    already existed when it ran. In the squash, 0001-0098 share the editor
    with it, so flush here to hand migrate_forward the same schema.
    """
    for statement in schema_editor.deferred_sql:
        schema_editor.execute(statement)
    schema_editor.deferred_sql = []


# ============================================================================
# Forward / reverse Python entry points
# ============================================================================

def migrate_forward(apps, schema_editor):
    """Forward migration - dispatches to PostgreSQL or SQLite implementation."""
    vendor = schema_editor.connection.vendor
    if vendor == "postgresql":
        _migrate_postgresql(schema_editor)
    elif vendor == "sqlite":
        _migrate_sqlite(schema_editor)
    else:
        raise ValueError(
            f"Unsupported database backend: {vendor}. "
            f"This migration supports PostgreSQL and SQLite only."
        )


def migrate_reverse(apps, schema_editor):
    """Reverse migration - not supported for any backend."""
    raise RuntimeError(
        "The Photo UUID primary key change (originally migration "
        "0099_photo_uuid_primary_key) cannot be reversed. Restore a database "
        "backup instead."
    )


# ============================================================================
# PostgreSQL implementation
# ============================================================================

def _migrate_postgresql(schema_editor):
    """Execute the PostgreSQL-specific migration using raw SQL."""
    statements = schema_editor.connection.ops.prepare_sql_script(
        POSTGRESQL_FORWARD_SQL
    )
    for statement in statements:
        schema_editor.execute(statement)


# ============================================================================
# SQLite implementation  (table-recreation pattern)
# ============================================================================
#
# SQLite does not support most ALTER TABLE operations required by the
# PostgreSQL path (DROP/ADD CONSTRAINT, ADD PRIMARY KEY, ALTER COLUMN,
# UPDATE … FROM, gen_random_uuid(), etc.).
#
# Instead we use the standard SQLite table-recreation pattern:
#   1. CREATE TABLE …__new  (with the desired schema)
#   2. INSERT INTO …__new SELECT … FROM …  (copy data, translating FKs)
#   3. DROP TABLE …
#   4. ALTER TABLE …__new RENAME TO …
#   5. Re-create indexes
# ============================================================================

# (table, column) of every photo reference the rebuild translates. The rebuilt
# tables keep no REFERENCES clause, so foreign-key introspection cannot find
# these columns afterwards; the tests of 0143_sqlite_photo_ids_hex check that
# it still covers every one of them.
SQLITE_FK_COLUMNS = [
    ("api_face", "photo_id"),
    ("api_photo_shared_to", "photo_id"),
    ("api_photo_files", "photo_id"),
    ("api_albumuser_photos", "photo_id"),
    ("api_albumthing_photos", "photo_id"),
    ("api_albumplace_photos", "photo_id"),
    ("api_albumdate_photos", "photo_id"),
    ("api_albumauto_photos", "photo_id"),
    ("api_albumthing_cover_photos", "photo_id"),
    ("api_person", "cover_photo_id"),
    ("api_albumuser", "cover_photo_id"),
    ("api_photostack", "primary_photo_id"),
    ("api_thumbnail", "photo_id"),
    ("api_photo_caption", "photo_id"),
    ("api_photo_search", "photo_id"),
]


def _migrate_sqlite(schema_editor):
    """Execute the SQLite-compatible migration via table recreation."""
    cursor = schema_editor.connection.cursor()

    # Disable FK enforcement while we recreate tables
    cursor.execute("PRAGMA foreign_keys = OFF")

    try:
        # -- Step 1: Build image_hash → UUID mapping --------------------------
        # UUIDField stores uuid.hex on SQLite and looks rows up by it. The
        # original 0099 wrote str(uuid4()) here, with dashes, which Django
        # never matches; 0143_sqlite_photo_ids_hex repairs databases that
        # already ran it.
        cursor.execute('SELECT "image_hash" FROM "api_photo"')
        mapping = {row[0]: uuid.uuid4().hex for row in cursor.fetchall()}

        # -- Step 2: Add id column to api_photo and populate UUIDs ------------
        cursor.execute('ALTER TABLE "api_photo" ADD COLUMN "id" TEXT')
        for image_hash, new_id in mapping.items():
            cursor.execute(
                'UPDATE "api_photo" SET "id" = ? WHERE "image_hash" = ?',
                [new_id, image_hash],
            )

        # -- Step 3: Recreate api_photo with id as PK ------------------------
        _sqlite_recreate_table(
            cursor,
            "api_photo",
            pk_column="id",
            column_overrides={
                "id": '"id" TEXT NOT NULL',
                "image_hash": '"image_hash" varchar(64) NOT NULL UNIQUE',
            },
        )

        # -- Step 4: Update FK references in every related table --------------
        for table_name, fk_column in SQLITE_FK_COLUMNS:
            _sqlite_update_fk_table(cursor, table_name, fk_column, mapping)

        # -- Step 5: Create performance indexes -------------------------------
        _sqlite_create_indexes(cursor)

    finally:
        cursor.execute("PRAGMA foreign_keys = ON")


# -- SQLite helpers -----------------------------------------------------------

def _sqlite_recreate_table(cursor, table_name, pk_column, column_overrides):
    """
    Recreate *api_photo* with a new primary-key column.

    * ``pk_column``        – name of the column that becomes PRIMARY KEY
    * ``column_overrides`` – dict  column_name → SQL column-definition fragment
                             (without PRIMARY KEY – that is appended automatically
                              for *pk_column*)
    """
    columns = _sqlite_column_info(cursor, table_name)
    indexes = _sqlite_index_info(cursor, table_name)

    col_defs = []
    col_names = []
    for _cid, name, type_, notnull, dflt_value, _pk in columns:
        col_names.append(name)
        if name in column_overrides:
            defn = column_overrides[name]
            if name == pk_column:
                defn += " PRIMARY KEY"
            col_defs.append(defn)
        else:
            parts = [f'"{name}"', type_ or "TEXT"]
            if name == pk_column:
                parts.append("NOT NULL PRIMARY KEY")
            elif notnull:
                parts.append("NOT NULL")
            if dflt_value is not None and name != pk_column:
                parts.append(f"DEFAULT {dflt_value}")
            col_defs.append(" ".join(parts))

    cols_quoted = ", ".join(f'"{c}"' for c in col_names)
    new_table = f"{table_name}__new"

    cursor.execute(f'CREATE TABLE "{new_table}" ({", ".join(col_defs)})')
    cursor.execute(
        f'INSERT INTO "{new_table}" ({cols_quoted}) '
        f'SELECT {cols_quoted} FROM "{table_name}"'
    )
    cursor.execute(f'DROP TABLE "{table_name}"')
    cursor.execute(f'ALTER TABLE "{new_table}" RENAME TO "{table_name}"')

    # Re-create any existing indexes
    for _idx_name, idx_sql in indexes:
        try:
            cursor.execute(idx_sql)
        except Exception:
            pass  # index may conflict with new UNIQUE constraint


def _sqlite_update_fk_table(cursor, table_name, fk_column, mapping):
    """
    Recreate *table_name* so that every value in *fk_column* is translated
    from the old image_hash to the new UUID via *mapping*.
    """
    # Guard: skip if the table or column doesn't exist
    cursor.execute(
        "SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name=?",
        [table_name],
    )
    if cursor.fetchone()[0] == 0:
        return

    columns = _sqlite_column_info(cursor, table_name)
    col_names_list = [col[1] for col in columns]
    if fk_column not in col_names_list:
        return

    indexes = _sqlite_index_info(cursor, table_name)

    # Build column definitions – change the FK column type to TEXT
    col_defs = []
    col_names = []
    fk_col_idx = None

    for _cid, name, type_, notnull, dflt_value, pk in columns:
        col_names.append(name)
        if name == fk_column:
            fk_col_idx = len(col_names) - 1
            parts = [f'"{name}" TEXT']
            if pk:
                parts.append("NOT NULL PRIMARY KEY")
            col_defs.append(" ".join(parts))
        else:
            parts = [f'"{name}"', type_ or "TEXT"]
            if pk:
                parts.append("PRIMARY KEY")
            if notnull and not pk:
                parts.append("NOT NULL")
            if dflt_value is not None:
                parts.append(f"DEFAULT {dflt_value}")
            col_defs.append(" ".join(parts))

    cols_quoted = ", ".join(f'"{c}"' for c in col_names)
    new_table = f"{table_name}__new"

    # Create new table and bulk-copy data
    cursor.execute(f'CREATE TABLE "{new_table}" ({", ".join(col_defs)})')
    cursor.execute(
        f'INSERT INTO "{new_table}" ({cols_quoted}) '
        f'SELECT {cols_quoted} FROM "{table_name}"'
    )

    # Translate FK values in the new table
    for old_hash, new_uuid in mapping.items():
        cursor.execute(
            f'UPDATE "{new_table}" SET "{fk_column}" = ? '
            f'WHERE "{fk_column}" = ?',
            [new_uuid, old_hash],
        )

    # Swap tables
    cursor.execute(f'DROP TABLE "{table_name}"')
    cursor.execute(f'ALTER TABLE "{new_table}" RENAME TO "{table_name}"')

    # Re-create indexes
    for _idx_name, idx_sql in indexes:
        try:
            cursor.execute(idx_sql)
        except Exception:
            pass


def _sqlite_create_indexes(cursor):
    """Create the same performance indexes as the PostgreSQL path."""
    index_defs = [
        (True, "api_photo_image_hash_unique", "api_photo", "image_hash"),
        (False, "api_face_photo_id_idx", "api_face", "photo_id"),
        (False, "api_photo_shared_to_photo_id_idx", "api_photo_shared_to", "photo_id"),
        (False, "api_photo_files_photo_id_idx", "api_photo_files", "photo_id"),
        (False, "api_person_cover_photo_id_idx", "api_person", "cover_photo_id"),
        (False, "api_albumuser_cover_photo_id_idx", "api_albumuser", "cover_photo_id"),
        (False, "api_photostack_primary_photo_id_idx", "api_photostack", "primary_photo_id"),
    ]
    for unique, idx_name, table, column in index_defs:
        unique_kw = "UNIQUE " if unique else ""
        try:
            cursor.execute(
                f'CREATE {unique_kw}INDEX IF NOT EXISTS '
                f'"{idx_name}" ON "{table}"("{column}")'
            )
        except Exception:
            pass


def _sqlite_column_info(cursor, table_name):
    """Return PRAGMA table_info rows for *table_name*."""
    cursor.execute(f'PRAGMA table_info("{table_name}")')
    return cursor.fetchall()


def _sqlite_index_info(cursor, table_name):
    """Return (name, sql) for every explicit index on *table_name*."""
    cursor.execute(
        "SELECT name, sql FROM sqlite_master "
        "WHERE type='index' AND tbl_name=? AND sql IS NOT NULL",
        [table_name],
    )
    return cursor.fetchall()


class Migration(migrations.Migration):
    """api migrations 0001-0100, squashed.

    ``replaces`` must stay: a database that already has 0001-0100 recorded in
    django_migrations treats this migration as applied because of it. A
    database with only some of them applied (an install older than release
    2026w10) cannot use it; api.checks.check_squashed_migration_history stops
    ``migrate`` with upgrade instructions in that case.
    """

    replaces = [
        ("api", "0001_initial"),
        ("api", "0002_add_confidence"),
        ("api", "0003_remove_unused_thumbs"),
        ("api", "0004_fix_album_thing_constraint"),
        ("api", "0005_add_video_to_photo"),
        ("api", "0006_migrate_to_boolean_field"),
        ("api", "0007_migrate_to_json_field"),
        ("api", "0008_remove_image_path"),
        ("api", "0009_add_clip_embedding_field"),
        ("api", "0009_add_aspect_ratio"),
        ("api", "0010_merge_20210725_1547"),
        ("api", "0011_a_add_rating"),
        ("api", "0011_b_migrate_favorited_to_rating"),
        ("api", "0011_c_remove_favorited"),
        ("api", "0012_add_favorite_min_rating"),
        ("api", "0013_add_image_scale_and_misc"),
        ("api", "0014_add_save_metadata_to_disk"),
        ("api", "0015_add_dominant_color"),
        ("api", "0016_add_transcode_videos"),
        ("api", "0017_add_cover_photo"),
        ("api", "0018_user_config_datetime_rules"),
        ("api", "0019_change_config_datetime_rules"),
        ("api", "0020_add_default_timezone"),
        ("api", "0021_remove_photo_image"),
        ("api", "0022_photo_video_length"),
        ("api", "0023_photo_deleted"),
        ("api", "0024_photo_timestamp"),
        ("api", "0025_add_cover_photo"),
        ("api", "0026_add_cluster_info"),
        ("api", "0027_rename_unknown_person"),
        ("api", "0028_add_metadata_fields"),
        ("api", "0029_change_to_text_field"),
        ("api", "0030_user_confidence_person"),
        ("api", "0031_remove_account"),
        ("api", "0032_always_have_owner"),
        ("api", "0033_add_post_delete_person"),
        ("api", "0034_allow_deleting_person"),
        ("api", "0035_add_files_model"),
        ("api", "0036_handle_missing_files"),
        ("api", "0037_migrate_to_files"),
        ("api", "0038_add_main_file"),
        ("api", "0039_remove_photo_image_paths"),
        ("api", "0040_add_user_public_sharing_flag"),
        ("api", "0041_apply_user_enum_for_person"),
        ("api", "0042_alter_albumuser_cover_photo_alter_photo_main_file"),
        ("api", "0043_alter_photo_size"),
        ("api", "0044_alter_cluster_person_alter_person_cluster_owner"),
        ("api", "0045_alter_face_cluster"),
        ("api", "0046_add_embedded_media"),
        ("api", "0047_alter_file_embedded_media"),
        ("api", "0048_fix_null_height"),
        ("api", "0049_fix_metadata_files_as_main_files"),
        ("api", "0050_person_face_count"),
        ("api", "0051_set_person_defaults"),
        ("api", "0052_alter_person_name"),
        ("api", "0053_user_confidence_unknown_face_and_more"),
        ("api", "0054_user_cluster_selection_epsilon_user_min_samples"),
        ("api", "0055_alter_longrunningjob_job_type"),
        ("api", "0056_user_llm_settings_alter_longrunningjob_job_type"),
        ("api", "0057_remove_face_image_path_and_more"),
        ("api", "0058_alter_user_avatar_alter_user_nextcloud_app_password_and_more"),
        ("api", "0059_person_cover_face"),
        ("api", "0060_apply_default_face_cover"),
        ("api", "0061_alter_person_name"),
        ("api", "0062_albumthing_cover_photos"),
        ("api", "0063_apply_default_album_things_cover"),
        ("api", "0064_albumthing_photo_count"),
        ("api", "0065_apply_default_photo_count"),
        ("api", "0066_photo_last_modified_alter_longrunningjob_job_type"),
        ("api", "0067_alter_longrunningjob_job_type"),
        ("api", "0068_remove_longrunningjob_result_and_more"),
        ("api", "0069_rename_to_in_trashcan"),
        ("api", "0070_photo_removed"),
        ("api", "0071_rename_person_label_probability_face_cluster_probability_and_more"),
        ("api", "0072_alter_face_person"),
        ("api", "0073_remove_unknown_person"),
        ("api", "0074_migrate_cluster_person"),
        ("api", "0075_alter_face_cluster_person"),
        ("api", "0076_alter_file_path_alter_longrunningjob_job_type_and_more"),
        ("api", "0077_alter_albumdate_title"),
        ("api", "0078_create_photo_thumbnail"),
        ("api", "0079_alter_albumauto_title"),
        ("api", "0080_create_photo_caption"),
        ("api", "0081_remove_caption_fields_from_photo"),
        ("api", "0082_create_photo_search"),
        ("api", "0083_remove_search_fields"),
        ("api", "0084_convert_arrayfield_to_json"),
        ("api", "0085_albumuser_public_expires_at_albumuser_public_slug"),
        ("api", "0086_remove_albumuser_public_and_more"),
        ("api", "0087_add_folder_album"),
        ("api", "0088_remove_folder_album"),
        ("api", "0089_add_text_alignment"),
        ("api", "0090_add_header_size"),
        ("api", "0091_alter_user_scan_directory"),
        ("api", "0092_add_skip_raw_files_field"),
        ("api", "0093_migrate_photon_to_nominatim"),
        ("api", "0094_add_slideshow_interval"),
        ("api", "0095_photo_perceptual_hash_alter_longrunningjob_job_type_and_more"),
        ("api", "0096_add_progress_step_and_result_to_longrunningjob"),
        ("api", "0097_add_duplicate_detection_settings_to_user"),
        ("api", "0098_add_photo_stack"),
        ("api", "0099_photo_uuid_primary_key"),
        ("api", "0100_metadataedit_metadatafile_photometadata_stackreview_and_more"),
    ]

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('scan_directory', models.CharField(blank=True, db_index=True, default='', max_length=512)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars')),
                ('nextcloud_server_address', models.CharField(blank=True, default='', max_length=200)),
                ('nextcloud_username', models.CharField(blank=True, default='', max_length=64)),
                ('nextcloud_app_password', django_cryptography.fields.encrypt(models.CharField(blank=True, default='', max_length=64))),
                ('nextcloud_scan_directory', models.CharField(blank=True, db_index=True, default='', max_length=512)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('confidence', models.FloatField(db_index=True, default=0.1)),
                ('semantic_search_topk', models.IntegerField(default=0)),
                ('favorite_min_rating', models.IntegerField(db_index=True, default=4)),
                ('image_scale', models.FloatField(default=1)),
                ('save_metadata_to_disk', models.TextField(choices=[('OFF', 'Off'), ('MEDIA_FILE', 'Media File'), ('SIDECAR_FILE', 'Sidecar File')], default='OFF')),
                ('transcode_videos', models.BooleanField(default=False)),
                ('datetime_rules', models.JSONField(default=api.models.user.get_default_config_datetime_rules)),
                ('default_timezone', models.TextField(choices=[('Africa/Abidjan', 'Africa/Abidjan'), ('Africa/Accra', 'Africa/Accra'), ('Africa/Addis_Ababa', 'Africa/Addis_Ababa'), ('Africa/Algiers', 'Africa/Algiers'), ('Africa/Asmara', 'Africa/Asmara'), ('Africa/Asmera', 'Africa/Asmera'), ('Africa/Bamako', 'Africa/Bamako'), ('Africa/Bangui', 'Africa/Bangui'), ('Africa/Banjul', 'Africa/Banjul'), ('Africa/Bissau', 'Africa/Bissau'), ('Africa/Blantyre', 'Africa/Blantyre'), ('Africa/Brazzaville', 'Africa/Brazzaville'), ('Africa/Bujumbura', 'Africa/Bujumbura'), ('Africa/Cairo', 'Africa/Cairo'), ('Africa/Casablanca', 'Africa/Casablanca'), ('Africa/Ceuta', 'Africa/Ceuta'), ('Africa/Conakry', 'Africa/Conakry'), ('Africa/Dakar', 'Africa/Dakar'), ('Africa/Dar_es_Salaam', 'Africa/Dar_es_Salaam'), ('Africa/Djibouti', 'Africa/Djibouti'), ('Africa/Douala', 'Africa/Douala'), ('Africa/El_Aaiun', 'Africa/El_Aaiun'), ('Africa/Freetown', 'Africa/Freetown'), ('Africa/Gaborone', 'Africa/Gaborone'), ('Africa/Harare', 'Africa/Harare'), ('Africa/Johannesburg', 'Africa/Johannesburg'), ('Africa/Juba', 'Africa/Juba'), ('Africa/Kampala', 'Africa/Kampala'), ('Africa/Khartoum', 'Africa/Khartoum'), ('Africa/Kigali', 'Africa/Kigali'), ('Africa/Kinshasa', 'Africa/Kinshasa'), ('Africa/Lagos', 'Africa/Lagos'), ('Africa/Libreville', 'Africa/Libreville'), ('Africa/Lome', 'Africa/Lome'), ('Africa/Luanda', 'Africa/Luanda'), ('Africa/Lubumbashi', 'Africa/Lubumbashi'), ('Africa/Lusaka', 'Africa/Lusaka'), ('Africa/Malabo', 'Africa/Malabo'), ('Africa/Maputo', 'Africa/Maputo'), ('Africa/Maseru', 'Africa/Maseru'), ('Africa/Mbabane', 'Africa/Mbabane'), ('Africa/Mogadishu', 'Africa/Mogadishu'), ('Africa/Monrovia', 'Africa/Monrovia'), ('Africa/Nairobi', 'Africa/Nairobi'), ('Africa/Ndjamena', 'Africa/Ndjamena'), ('Africa/Niamey', 'Africa/Niamey'), ('Africa/Nouakchott', 'Africa/Nouakchott'), ('Africa/Ouagadougou', 'Africa/Ouagadougou'), ('Africa/Porto-Novo', 'Africa/Porto-Novo'), ('Africa/Sao_Tome', 'Africa/Sao_Tome'), ('Africa/Timbuktu', 'Africa/Timbuktu'), ('Africa/Tripoli', 'Africa/Tripoli'), ('Africa/Tunis', 'Africa/Tunis'), ('Africa/Windhoek', 'Africa/Windhoek'), ('America/Adak', 'America/Adak'), ('America/Anchorage', 'America/Anchorage'), ('America/Anguilla', 'America/Anguilla'), ('America/Antigua', 'America/Antigua'), ('America/Araguaina', 'America/Araguaina'), ('America/Argentina/Buenos_Aires', 'America/Argentina/Buenos_Aires'), ('America/Argentina/Catamarca', 'America/Argentina/Catamarca'), ('America/Argentina/ComodRivadavia', 'America/Argentina/ComodRivadavia'), ('America/Argentina/Cordoba', 'America/Argentina/Cordoba'), ('America/Argentina/Jujuy', 'America/Argentina/Jujuy'), ('America/Argentina/La_Rioja', 'America/Argentina/La_Rioja'), ('America/Argentina/Mendoza', 'America/Argentina/Mendoza'), ('America/Argentina/Rio_Gallegos', 'America/Argentina/Rio_Gallegos'), ('America/Argentina/Salta', 'America/Argentina/Salta'), ('America/Argentina/San_Juan', 'America/Argentina/San_Juan'), ('America/Argentina/San_Luis', 'America/Argentina/San_Luis'), ('America/Argentina/Tucuman', 'America/Argentina/Tucuman'), ('America/Argentina/Ushuaia', 'America/Argentina/Ushuaia'), ('America/Aruba', 'America/Aruba'), ('America/Asuncion', 'America/Asuncion'), ('America/Atikokan', 'America/Atikokan'), ('America/Atka', 'America/Atka'), ('America/Bahia', 'America/Bahia'), ('America/Bahia_Banderas', 'America/Bahia_Banderas'), ('America/Barbados', 'America/Barbados'), ('America/Belem', 'America/Belem'), ('America/Belize', 'America/Belize'), ('America/Blanc-Sablon', 'America/Blanc-Sablon'), ('America/Boa_Vista', 'America/Boa_Vista'), ('America/Bogota', 'America/Bogota'), ('America/Boise', 'America/Boise'), ('America/Buenos_Aires', 'America/Buenos_Aires'), ('America/Cambridge_Bay', 'America/Cambridge_Bay'), ('America/Campo_Grande', 'America/Campo_Grande'), ('America/Cancun', 'America/Cancun'), ('America/Caracas', 'America/Caracas'), ('America/Catamarca', 'America/Catamarca'), ('America/Cayenne', 'America/Cayenne'), ('America/Cayman', 'America/Cayman'), ('America/Chicago', 'America/Chicago'), ('America/Chihuahua', 'America/Chihuahua'), ('America/Ciudad_Juarez', 'America/Ciudad_Juarez'), ('America/Coral_Harbour', 'America/Coral_Harbour'), ('America/Cordoba', 'America/Cordoba'), ('America/Costa_Rica', 'America/Costa_Rica'), ('America/Coyhaique', 'America/Coyhaique'), ('America/Creston', 'America/Creston'), ('America/Cuiaba', 'America/Cuiaba'), ('America/Curacao', 'America/Curacao'), ('America/Danmarkshavn', 'America/Danmarkshavn'), ('America/Dawson', 'America/Dawson'), ('America/Dawson_Creek', 'America/Dawson_Creek'), ('America/Denver', 'America/Denver'), ('America/Detroit', 'America/Detroit'), ('America/Dominica', 'America/Dominica'), ('America/Edmonton', 'America/Edmonton'), ('America/Eirunepe', 'America/Eirunepe'), ('America/El_Salvador', 'America/El_Salvador'), ('America/Ensenada', 'America/Ensenada'), ('America/Fort_Nelson', 'America/Fort_Nelson'), ('America/Fort_Wayne', 'America/Fort_Wayne'), ('America/Fortaleza', 'America/Fortaleza'), ('America/Glace_Bay', 'America/Glace_Bay'), ('America/Godthab', 'America/Godthab'), ('America/Goose_Bay', 'America/Goose_Bay'), ('America/Grand_Turk', 'America/Grand_Turk'), ('America/Grenada', 'America/Grenada'), ('America/Guadeloupe', 'America/Guadeloupe'), ('America/Guatemala', 'America/Guatemala'), ('America/Guayaquil', 'America/Guayaquil'), ('America/Guyana', 'America/Guyana'), ('America/Halifax', 'America/Halifax'), ('America/Havana', 'America/Havana'), ('America/Hermosillo', 'America/Hermosillo'), ('America/Indiana/Indianapolis', 'America/Indiana/Indianapolis'), ('America/Indiana/Knox', 'America/Indiana/Knox'), ('America/Indiana/Marengo', 'America/Indiana/Marengo'), ('America/Indiana/Petersburg', 'America/Indiana/Petersburg'), ('America/Indiana/Tell_City', 'America/Indiana/Tell_City'), ('America/Indiana/Vevay', 'America/Indiana/Vevay'), ('America/Indiana/Vincennes', 'America/Indiana/Vincennes'), ('America/Indiana/Winamac', 'America/Indiana/Winamac'), ('America/Indianapolis', 'America/Indianapolis'), ('America/Inuvik', 'America/Inuvik'), ('America/Iqaluit', 'America/Iqaluit'), ('America/Jamaica', 'America/Jamaica'), ('America/Jujuy', 'America/Jujuy'), ('America/Juneau', 'America/Juneau'), ('America/Kentucky/Louisville', 'America/Kentucky/Louisville'), ('America/Kentucky/Monticello', 'America/Kentucky/Monticello'), ('America/Knox_IN', 'America/Knox_IN'), ('America/Kralendijk', 'America/Kralendijk'), ('America/La_Paz', 'America/La_Paz'), ('America/Lima', 'America/Lima'), ('America/Los_Angeles', 'America/Los_Angeles'), ('America/Louisville', 'America/Louisville'), ('America/Lower_Princes', 'America/Lower_Princes'), ('America/Maceio', 'America/Maceio'), ('America/Managua', 'America/Managua'), ('America/Manaus', 'America/Manaus'), ('America/Marigot', 'America/Marigot'), ('America/Martinique', 'America/Martinique'), ('America/Matamoros', 'America/Matamoros'), ('America/Mazatlan', 'America/Mazatlan'), ('America/Mendoza', 'America/Mendoza'), ('America/Menominee', 'America/Menominee'), ('America/Merida', 'America/Merida'), ('America/Metlakatla', 'America/Metlakatla'), ('America/Mexico_City', 'America/Mexico_City'), ('America/Miquelon', 'America/Miquelon'), ('America/Moncton', 'America/Moncton'), ('America/Monterrey', 'America/Monterrey'), ('America/Montevideo', 'America/Montevideo'), ('America/Montreal', 'America/Montreal'), ('America/Montserrat', 'America/Montserrat'), ('America/Nassau', 'America/Nassau'), ('America/New_York', 'America/New_York'), ('America/Nipigon', 'America/Nipigon'), ('America/Nome', 'America/Nome'), ('America/Noronha', 'America/Noronha'), ('America/North_Dakota/Beulah', 'America/North_Dakota/Beulah'), ('America/North_Dakota/Center', 'America/North_Dakota/Center'), ('America/North_Dakota/New_Salem', 'America/North_Dakota/New_Salem'), ('America/Nuuk', 'America/Nuuk'), ('America/Ojinaga', 'America/Ojinaga'), ('America/Panama', 'America/Panama'), ('America/Pangnirtung', 'America/Pangnirtung'), ('America/Paramaribo', 'America/Paramaribo'), ('America/Phoenix', 'America/Phoenix'), ('America/Port-au-Prince', 'America/Port-au-Prince'), ('America/Port_of_Spain', 'America/Port_of_Spain'), ('America/Porto_Acre', 'America/Porto_Acre'), ('America/Porto_Velho', 'America/Porto_Velho'), ('America/Puerto_Rico', 'America/Puerto_Rico'), ('America/Punta_Arenas', 'America/Punta_Arenas'), ('America/Rainy_River', 'America/Rainy_River'), ('America/Rankin_Inlet', 'America/Rankin_Inlet'), ('America/Recife', 'America/Recife'), ('America/Regina', 'America/Regina'), ('America/Resolute', 'America/Resolute'), ('America/Rio_Branco', 'America/Rio_Branco'), ('America/Rosario', 'America/Rosario'), ('America/Santa_Isabel', 'America/Santa_Isabel'), ('America/Santarem', 'America/Santarem'), ('America/Santiago', 'America/Santiago'), ('America/Santo_Domingo', 'America/Santo_Domingo'), ('America/Sao_Paulo', 'America/Sao_Paulo'), ('America/Scoresbysund', 'America/Scoresbysund'), ('America/Shiprock', 'America/Shiprock'), ('America/Sitka', 'America/Sitka'), ('America/St_Barthelemy', 'America/St_Barthelemy'), ('America/St_Johns', 'America/St_Johns'), ('America/St_Kitts', 'America/St_Kitts'), ('America/St_Lucia', 'America/St_Lucia'), ('America/St_Thomas', 'America/St_Thomas'), ('America/St_Vincent', 'America/St_Vincent'), ('America/Swift_Current', 'America/Swift_Current'), ('America/Tegucigalpa', 'America/Tegucigalpa'), ('America/Thule', 'America/Thule'), ('America/Thunder_Bay', 'America/Thunder_Bay'), ('America/Tijuana', 'America/Tijuana'), ('America/Toronto', 'America/Toronto'), ('America/Tortola', 'America/Tortola'), ('America/Vancouver', 'America/Vancouver'), ('America/Virgin', 'America/Virgin'), ('America/Whitehorse', 'America/Whitehorse'), ('America/Winnipeg', 'America/Winnipeg'), ('America/Yakutat', 'America/Yakutat'), ('America/Yellowknife', 'America/Yellowknife'), ('Antarctica/Casey', 'Antarctica/Casey'), ('Antarctica/Davis', 'Antarctica/Davis'), ('Antarctica/DumontDUrville', 'Antarctica/DumontDUrville'), ('Antarctica/Macquarie', 'Antarctica/Macquarie'), ('Antarctica/Mawson', 'Antarctica/Mawson'), ('Antarctica/McMurdo', 'Antarctica/McMurdo'), ('Antarctica/Palmer', 'Antarctica/Palmer'), ('Antarctica/Rothera', 'Antarctica/Rothera'), ('Antarctica/South_Pole', 'Antarctica/South_Pole'), ('Antarctica/Syowa', 'Antarctica/Syowa'), ('Antarctica/Troll', 'Antarctica/Troll'), ('Antarctica/Vostok', 'Antarctica/Vostok'), ('Arctic/Longyearbyen', 'Arctic/Longyearbyen'), ('Asia/Aden', 'Asia/Aden'), ('Asia/Almaty', 'Asia/Almaty'), ('Asia/Amman', 'Asia/Amman'), ('Asia/Anadyr', 'Asia/Anadyr'), ('Asia/Aqtau', 'Asia/Aqtau'), ('Asia/Aqtobe', 'Asia/Aqtobe'), ('Asia/Ashgabat', 'Asia/Ashgabat'), ('Asia/Ashkhabad', 'Asia/Ashkhabad'), ('Asia/Atyrau', 'Asia/Atyrau'), ('Asia/Baghdad', 'Asia/Baghdad'), ('Asia/Bahrain', 'Asia/Bahrain'), ('Asia/Baku', 'Asia/Baku'), ('Asia/Bangkok', 'Asia/Bangkok'), ('Asia/Barnaul', 'Asia/Barnaul'), ('Asia/Beirut', 'Asia/Beirut'), ('Asia/Bishkek', 'Asia/Bishkek'), ('Asia/Brunei', 'Asia/Brunei'), ('Asia/Calcutta', 'Asia/Calcutta'), ('Asia/Chita', 'Asia/Chita'), ('Asia/Choibalsan', 'Asia/Choibalsan'), ('Asia/Chongqing', 'Asia/Chongqing'), ('Asia/Chungking', 'Asia/Chungking'), ('Asia/Colombo', 'Asia/Colombo'), ('Asia/Dacca', 'Asia/Dacca'), ('Asia/Damascus', 'Asia/Damascus'), ('Asia/Dhaka', 'Asia/Dhaka'), ('Asia/Dili', 'Asia/Dili'), ('Asia/Dubai', 'Asia/Dubai'), ('Asia/Dushanbe', 'Asia/Dushanbe'), ('Asia/Famagusta', 'Asia/Famagusta'), ('Asia/Gaza', 'Asia/Gaza'), ('Asia/Harbin', 'Asia/Harbin'), ('Asia/Hebron', 'Asia/Hebron'), ('Asia/Ho_Chi_Minh', 'Asia/Ho_Chi_Minh'), ('Asia/Hong_Kong', 'Asia/Hong_Kong'), ('Asia/Hovd', 'Asia/Hovd'), ('Asia/Irkutsk', 'Asia/Irkutsk'), ('Asia/Istanbul', 'Asia/Istanbul'), ('Asia/Jakarta', 'Asia/Jakarta'), ('Asia/Jayapura', 'Asia/Jayapura'), ('Asia/Jerusalem', 'Asia/Jerusalem'), ('Asia/Kabul', 'Asia/Kabul'), ('Asia/Kamchatka', 'Asia/Kamchatka'), ('Asia/Karachi', 'Asia/Karachi'), ('Asia/Kashgar', 'Asia/Kashgar'), ('Asia/Kathmandu', 'Asia/Kathmandu'), ('Asia/Katmandu', 'Asia/Katmandu'), ('Asia/Khandyga', 'Asia/Khandyga'), ('Asia/Kolkata', 'Asia/Kolkata'), ('Asia/Krasnoyarsk', 'Asia/Krasnoyarsk'), ('Asia/Kuala_Lumpur', 'Asia/Kuala_Lumpur'), ('Asia/Kuching', 'Asia/Kuching'), ('Asia/Kuwait', 'Asia/Kuwait'), ('Asia/Macao', 'Asia/Macao'), ('Asia/Macau', 'Asia/Macau'), ('Asia/Magadan', 'Asia/Magadan'), ('Asia/Makassar', 'Asia/Makassar'), ('Asia/Manila', 'Asia/Manila'), ('Asia/Muscat', 'Asia/Muscat'), ('Asia/Nicosia', 'Asia/Nicosia'), ('Asia/Novokuznetsk', 'Asia/Novokuznetsk'), ('Asia/Novosibirsk', 'Asia/Novosibirsk'), ('Asia/Omsk', 'Asia/Omsk'), ('Asia/Oral', 'Asia/Oral'), ('Asia/Phnom_Penh', 'Asia/Phnom_Penh'), ('Asia/Pontianak', 'Asia/Pontianak'), ('Asia/Pyongyang', 'Asia/Pyongyang'), ('Asia/Qatar', 'Asia/Qatar'), ('Asia/Qostanay', 'Asia/Qostanay'), ('Asia/Qyzylorda', 'Asia/Qyzylorda'), ('Asia/Rangoon', 'Asia/Rangoon'), ('Asia/Riyadh', 'Asia/Riyadh'), ('Asia/Saigon', 'Asia/Saigon'), ('Asia/Sakhalin', 'Asia/Sakhalin'), ('Asia/Samarkand', 'Asia/Samarkand'), ('Asia/Seoul', 'Asia/Seoul'), ('Asia/Shanghai', 'Asia/Shanghai'), ('Asia/Singapore', 'Asia/Singapore'), ('Asia/Srednekolymsk', 'Asia/Srednekolymsk'), ('Asia/Taipei', 'Asia/Taipei'), ('Asia/Tashkent', 'Asia/Tashkent'), ('Asia/Tbilisi', 'Asia/Tbilisi'), ('Asia/Tehran', 'Asia/Tehran'), ('Asia/Tel_Aviv', 'Asia/Tel_Aviv'), ('Asia/Thimbu', 'Asia/Thimbu'), ('Asia/Thimphu', 'Asia/Thimphu'), ('Asia/Tokyo', 'Asia/Tokyo'), ('Asia/Tomsk', 'Asia/Tomsk'), ('Asia/Ujung_Pandang', 'Asia/Ujung_Pandang'), ('Asia/Ulaanbaatar', 'Asia/Ulaanbaatar'), ('Asia/Ulan_Bator', 'Asia/Ulan_Bator'), ('Asia/Urumqi', 'Asia/Urumqi'), ('Asia/Ust-Nera', 'Asia/Ust-Nera'), ('Asia/Vientiane', 'Asia/Vientiane'), ('Asia/Vladivostok', 'Asia/Vladivostok'), ('Asia/Yakutsk', 'Asia/Yakutsk'), ('Asia/Yangon', 'Asia/Yangon'), ('Asia/Yekaterinburg', 'Asia/Yekaterinburg'), ('Asia/Yerevan', 'Asia/Yerevan'), ('Atlantic/Azores', 'Atlantic/Azores'), ('Atlantic/Bermuda', 'Atlantic/Bermuda'), ('Atlantic/Canary', 'Atlantic/Canary'), ('Atlantic/Cape_Verde', 'Atlantic/Cape_Verde'), ('Atlantic/Faeroe', 'Atlantic/Faeroe'), ('Atlantic/Faroe', 'Atlantic/Faroe'), ('Atlantic/Jan_Mayen', 'Atlantic/Jan_Mayen'), ('Atlantic/Madeira', 'Atlantic/Madeira'), ('Atlantic/Reykjavik', 'Atlantic/Reykjavik'), ('Atlantic/South_Georgia', 'Atlantic/South_Georgia'), ('Atlantic/St_Helena', 'Atlantic/St_Helena'), ('Atlantic/Stanley', 'Atlantic/Stanley'), ('Australia/ACT', 'Australia/ACT'), ('Australia/Adelaide', 'Australia/Adelaide'), ('Australia/Brisbane', 'Australia/Brisbane'), ('Australia/Broken_Hill', 'Australia/Broken_Hill'), ('Australia/Canberra', 'Australia/Canberra'), ('Australia/Currie', 'Australia/Currie'), ('Australia/Darwin', 'Australia/Darwin'), ('Australia/Eucla', 'Australia/Eucla'), ('Australia/Hobart', 'Australia/Hobart'), ('Australia/LHI', 'Australia/LHI'), ('Australia/Lindeman', 'Australia/Lindeman'), ('Australia/Lord_Howe', 'Australia/Lord_Howe'), ('Australia/Melbourne', 'Australia/Melbourne'), ('Australia/NSW', 'Australia/NSW'), ('Australia/North', 'Australia/North'), ('Australia/Perth', 'Australia/Perth'), ('Australia/Queensland', 'Australia/Queensland'), ('Australia/South', 'Australia/South'), ('Australia/Sydney', 'Australia/Sydney'), ('Australia/Tasmania', 'Australia/Tasmania'), ('Australia/Victoria', 'Australia/Victoria'), ('Australia/West', 'Australia/West'), ('Australia/Yancowinna', 'Australia/Yancowinna'), ('Brazil/Acre', 'Brazil/Acre'), ('Brazil/DeNoronha', 'Brazil/DeNoronha'), ('Brazil/East', 'Brazil/East'), ('Brazil/West', 'Brazil/West'), ('CET', 'CET'), ('CST6CDT', 'CST6CDT'), ('Canada/Atlantic', 'Canada/Atlantic'), ('Canada/Central', 'Canada/Central'), ('Canada/Eastern', 'Canada/Eastern'), ('Canada/Mountain', 'Canada/Mountain'), ('Canada/Newfoundland', 'Canada/Newfoundland'), ('Canada/Pacific', 'Canada/Pacific'), ('Canada/Saskatchewan', 'Canada/Saskatchewan'), ('Canada/Yukon', 'Canada/Yukon'), ('Chile/Continental', 'Chile/Continental'), ('Chile/EasterIsland', 'Chile/EasterIsland'), ('Cuba', 'Cuba'), ('EET', 'EET'), ('EST', 'EST'), ('EST5EDT', 'EST5EDT'), ('Egypt', 'Egypt'), ('Eire', 'Eire'), ('Etc/GMT', 'Etc/GMT'), ('Etc/GMT+0', 'Etc/GMT+0'), ('Etc/GMT+1', 'Etc/GMT+1'), ('Etc/GMT+10', 'Etc/GMT+10'), ('Etc/GMT+11', 'Etc/GMT+11'), ('Etc/GMT+12', 'Etc/GMT+12'), ('Etc/GMT+2', 'Etc/GMT+2'), ('Etc/GMT+3', 'Etc/GMT+3'), ('Etc/GMT+4', 'Etc/GMT+4'), ('Etc/GMT+5', 'Etc/GMT+5'), ('Etc/GMT+6', 'Etc/GMT+6'), ('Etc/GMT+7', 'Etc/GMT+7'), ('Etc/GMT+8', 'Etc/GMT+8'), ('Etc/GMT+9', 'Etc/GMT+9'), ('Etc/GMT-0', 'Etc/GMT-0'), ('Etc/GMT-1', 'Etc/GMT-1'), ('Etc/GMT-10', 'Etc/GMT-10'), ('Etc/GMT-11', 'Etc/GMT-11'), ('Etc/GMT-12', 'Etc/GMT-12'), ('Etc/GMT-13', 'Etc/GMT-13'), ('Etc/GMT-14', 'Etc/GMT-14'), ('Etc/GMT-2', 'Etc/GMT-2'), ('Etc/GMT-3', 'Etc/GMT-3'), ('Etc/GMT-4', 'Etc/GMT-4'), ('Etc/GMT-5', 'Etc/GMT-5'), ('Etc/GMT-6', 'Etc/GMT-6'), ('Etc/GMT-7', 'Etc/GMT-7'), ('Etc/GMT-8', 'Etc/GMT-8'), ('Etc/GMT-9', 'Etc/GMT-9'), ('Etc/GMT0', 'Etc/GMT0'), ('Etc/Greenwich', 'Etc/Greenwich'), ('Etc/UCT', 'Etc/UCT'), ('Etc/UTC', 'Etc/UTC'), ('Etc/Universal', 'Etc/Universal'), ('Etc/Zulu', 'Etc/Zulu'), ('Europe/Amsterdam', 'Europe/Amsterdam'), ('Europe/Andorra', 'Europe/Andorra'), ('Europe/Astrakhan', 'Europe/Astrakhan'), ('Europe/Athens', 'Europe/Athens'), ('Europe/Belfast', 'Europe/Belfast'), ('Europe/Belgrade', 'Europe/Belgrade'), ('Europe/Berlin', 'Europe/Berlin'), ('Europe/Bratislava', 'Europe/Bratislava'), ('Europe/Brussels', 'Europe/Brussels'), ('Europe/Bucharest', 'Europe/Bucharest'), ('Europe/Budapest', 'Europe/Budapest'), ('Europe/Busingen', 'Europe/Busingen'), ('Europe/Chisinau', 'Europe/Chisinau'), ('Europe/Copenhagen', 'Europe/Copenhagen'), ('Europe/Dublin', 'Europe/Dublin'), ('Europe/Gibraltar', 'Europe/Gibraltar'), ('Europe/Guernsey', 'Europe/Guernsey'), ('Europe/Helsinki', 'Europe/Helsinki'), ('Europe/Isle_of_Man', 'Europe/Isle_of_Man'), ('Europe/Istanbul', 'Europe/Istanbul'), ('Europe/Jersey', 'Europe/Jersey'), ('Europe/Kaliningrad', 'Europe/Kaliningrad'), ('Europe/Kiev', 'Europe/Kiev'), ('Europe/Kirov', 'Europe/Kirov'), ('Europe/Kyiv', 'Europe/Kyiv'), ('Europe/Lisbon', 'Europe/Lisbon'), ('Europe/Ljubljana', 'Europe/Ljubljana'), ('Europe/London', 'Europe/London'), ('Europe/Luxembourg', 'Europe/Luxembourg'), ('Europe/Madrid', 'Europe/Madrid'), ('Europe/Malta', 'Europe/Malta'), ('Europe/Mariehamn', 'Europe/Mariehamn'), ('Europe/Minsk', 'Europe/Minsk'), ('Europe/Monaco', 'Europe/Monaco'), ('Europe/Moscow', 'Europe/Moscow'), ('Europe/Nicosia', 'Europe/Nicosia'), ('Europe/Oslo', 'Europe/Oslo'), ('Europe/Paris', 'Europe/Paris'), ('Europe/Podgorica', 'Europe/Podgorica'), ('Europe/Prague', 'Europe/Prague'), ('Europe/Riga', 'Europe/Riga'), ('Europe/Rome', 'Europe/Rome'), ('Europe/Samara', 'Europe/Samara'), ('Europe/San_Marino', 'Europe/San_Marino'), ('Europe/Sarajevo', 'Europe/Sarajevo'), ('Europe/Saratov', 'Europe/Saratov'), ('Europe/Simferopol', 'Europe/Simferopol'), ('Europe/Skopje', 'Europe/Skopje'), ('Europe/Sofia', 'Europe/Sofia'), ('Europe/Stockholm', 'Europe/Stockholm'), ('Europe/Tallinn', 'Europe/Tallinn'), ('Europe/Tirane', 'Europe/Tirane'), ('Europe/Tiraspol', 'Europe/Tiraspol'), ('Europe/Ulyanovsk', 'Europe/Ulyanovsk'), ('Europe/Uzhgorod', 'Europe/Uzhgorod'), ('Europe/Vaduz', 'Europe/Vaduz'), ('Europe/Vatican', 'Europe/Vatican'), ('Europe/Vienna', 'Europe/Vienna'), ('Europe/Vilnius', 'Europe/Vilnius'), ('Europe/Volgograd', 'Europe/Volgograd'), ('Europe/Warsaw', 'Europe/Warsaw'), ('Europe/Zagreb', 'Europe/Zagreb'), ('Europe/Zaporozhye', 'Europe/Zaporozhye'), ('Europe/Zurich', 'Europe/Zurich'), ('GB', 'GB'), ('GB-Eire', 'GB-Eire'), ('GMT', 'GMT'), ('GMT+0', 'GMT+0'), ('GMT-0', 'GMT-0'), ('GMT0', 'GMT0'), ('Greenwich', 'Greenwich'), ('HST', 'HST'), ('Hongkong', 'Hongkong'), ('Iceland', 'Iceland'), ('Indian/Antananarivo', 'Indian/Antananarivo'), ('Indian/Chagos', 'Indian/Chagos'), ('Indian/Christmas', 'Indian/Christmas'), ('Indian/Cocos', 'Indian/Cocos'), ('Indian/Comoro', 'Indian/Comoro'), ('Indian/Kerguelen', 'Indian/Kerguelen'), ('Indian/Mahe', 'Indian/Mahe'), ('Indian/Maldives', 'Indian/Maldives'), ('Indian/Mauritius', 'Indian/Mauritius'), ('Indian/Mayotte', 'Indian/Mayotte'), ('Indian/Reunion', 'Indian/Reunion'), ('Iran', 'Iran'), ('Israel', 'Israel'), ('Jamaica', 'Jamaica'), ('Japan', 'Japan'), ('Kwajalein', 'Kwajalein'), ('Libya', 'Libya'), ('MET', 'MET'), ('MST', 'MST'), ('MST7MDT', 'MST7MDT'), ('Mexico/BajaNorte', 'Mexico/BajaNorte'), ('Mexico/BajaSur', 'Mexico/BajaSur'), ('Mexico/General', 'Mexico/General'), ('NZ', 'NZ'), ('NZ-CHAT', 'NZ-CHAT'), ('Navajo', 'Navajo'), ('PRC', 'PRC'), ('PST8PDT', 'PST8PDT'), ('Pacific/Apia', 'Pacific/Apia'), ('Pacific/Auckland', 'Pacific/Auckland'), ('Pacific/Bougainville', 'Pacific/Bougainville'), ('Pacific/Chatham', 'Pacific/Chatham'), ('Pacific/Chuuk', 'Pacific/Chuuk'), ('Pacific/Easter', 'Pacific/Easter'), ('Pacific/Efate', 'Pacific/Efate'), ('Pacific/Enderbury', 'Pacific/Enderbury'), ('Pacific/Fakaofo', 'Pacific/Fakaofo'), ('Pacific/Fiji', 'Pacific/Fiji'), ('Pacific/Funafuti', 'Pacific/Funafuti'), ('Pacific/Galapagos', 'Pacific/Galapagos'), ('Pacific/Gambier', 'Pacific/Gambier'), ('Pacific/Guadalcanal', 'Pacific/Guadalcanal'), ('Pacific/Guam', 'Pacific/Guam'), ('Pacific/Honolulu', 'Pacific/Honolulu'), ('Pacific/Johnston', 'Pacific/Johnston'), ('Pacific/Kanton', 'Pacific/Kanton'), ('Pacific/Kiritimati', 'Pacific/Kiritimati'), ('Pacific/Kosrae', 'Pacific/Kosrae'), ('Pacific/Kwajalein', 'Pacific/Kwajalein'), ('Pacific/Majuro', 'Pacific/Majuro'), ('Pacific/Marquesas', 'Pacific/Marquesas'), ('Pacific/Midway', 'Pacific/Midway'), ('Pacific/Nauru', 'Pacific/Nauru'), ('Pacific/Niue', 'Pacific/Niue'), ('Pacific/Norfolk', 'Pacific/Norfolk'), ('Pacific/Noumea', 'Pacific/Noumea'), ('Pacific/Pago_Pago', 'Pacific/Pago_Pago'), ('Pacific/Palau', 'Pacific/Palau'), ('Pacific/Pitcairn', 'Pacific/Pitcairn'), ('Pacific/Pohnpei', 'Pacific/Pohnpei'), ('Pacific/Ponape', 'Pacific/Ponape'), ('Pacific/Port_Moresby', 'Pacific/Port_Moresby'), ('Pacific/Rarotonga', 'Pacific/Rarotonga'), ('Pacific/Saipan', 'Pacific/Saipan'), ('Pacific/Samoa', 'Pacific/Samoa'), ('Pacific/Tahiti', 'Pacific/Tahiti'), ('Pacific/Tarawa', 'Pacific/Tarawa'), ('Pacific/Tongatapu', 'Pacific/Tongatapu'), ('Pacific/Truk', 'Pacific/Truk'), ('Pacific/Wake', 'Pacific/Wake'), ('Pacific/Wallis', 'Pacific/Wallis'), ('Pacific/Yap', 'Pacific/Yap'), ('Poland', 'Poland'), ('Portugal', 'Portugal'), ('ROC', 'ROC'), ('ROK', 'ROK'), ('Singapore', 'Singapore'), ('Turkey', 'Turkey'), ('UCT', 'UCT'), ('US/Alaska', 'US/Alaska'), ('US/Aleutian', 'US/Aleutian'), ('US/Arizona', 'US/Arizona'), ('US/Central', 'US/Central'), ('US/East-Indiana', 'US/East-Indiana'), ('US/Eastern', 'US/Eastern'), ('US/Hawaii', 'US/Hawaii'), ('US/Indiana-Starke', 'US/Indiana-Starke'), ('US/Michigan', 'US/Michigan'), ('US/Mountain', 'US/Mountain'), ('US/Pacific', 'US/Pacific'), ('US/Samoa', 'US/Samoa'), ('UTC', 'UTC'), ('Universal', 'Universal'), ('W-SU', 'W-SU'), ('WET', 'WET'), ('Zulu', 'Zulu')], default='UTC')),
                ('confidence_person', models.FloatField(default=0.9)),
                ('public_sharing', models.BooleanField(default=False)),
                ('confidence_unknown_face', models.FloatField(default=0.5)),
                ('face_recognition_model', models.TextField(choices=[('HOG', 'Hog'), ('CNN', 'Cnn')], default='HOG')),
                ('min_cluster_size', models.IntegerField(default=0)),
                ('cluster_selection_epsilon', models.FloatField(default=0.05)),
                ('min_samples', models.IntegerField(default=1)),
                ('llm_settings', models.JSONField(default=api.models.user.get_default_llm_settings)),
                ('text_alignment', models.TextField(choices=[('left', 'Left'), ('right', 'Right')], default='right')),
                ('header_size', models.TextField(choices=[('large', 'Large'), ('normal', 'Normal'), ('small', 'Small')], default='large')),
                ('skip_raw_files', models.BooleanField(default=False)),
                ('slideshow_interval', models.IntegerField(default=5)),
                ('duplicate_clear_existing', models.BooleanField(default=False)),
                ('duplicate_sensitivity', models.TextField(choices=[('strict', 'Strict'), ('normal', 'Normal'), ('loose', 'Loose')], default='normal')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('image_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('thumbnail_big', models.ImageField(upload_to='thumbnails_big')),
                ('square_thumbnail', models.ImageField(upload_to='square_thumbnails')),
                ('square_thumbnail_small', models.ImageField(upload_to='square_thumbnails_small')),
                ('added_on', models.DateTimeField(db_index=True)),
                ('exif_gps_lat', models.FloatField(blank=True, null=True)),
                ('exif_gps_lon', models.FloatField(blank=True, null=True)),
                ('exif_timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('exif_json', models.JSONField(blank=True, null=True)),
                ('geolocation_json', models.JSONField(blank=True, db_index=True, null=True)),
                ('captions_json', models.JSONField(blank=True, db_index=True, null=True)),
                ('search_captions', models.TextField(blank=True, db_index=True, null=True)),
                ('search_location', models.TextField(blank=True, db_index=True, null=True)),
                ('hidden', models.BooleanField(db_index=True, default=False)),
                ('public', models.BooleanField(db_index=True, default=False)),
                ('owner', models.ForeignKey(default=None, on_delete=models.SET(api.models.user.get_deleted_user), to=settings.AUTH_USER_MODEL)),
                ('shared_to', models.ManyToManyField(related_name='photo_shared_to', to=settings.AUTH_USER_MODEL)),
                ('video', models.BooleanField(default=False)),
                ('image_paths', models.JSONField(default=list)),
                ('clip_embeddings', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), null=True, size=512)),
                ('clip_embeddings_magnitude', models.FloatField(blank=True, null=True)),
                ('aspect_ratio', models.FloatField(blank=True, null=True)),
                ('rating', models.IntegerField(db_index=True, default=0)),
                ('dominant_color', models.TextField(blank=True, null=True)),
                ('video_length', models.TextField(blank=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('camera', models.TextField(blank=True, null=True)),
                ('digitalZoomRatio', models.FloatField(blank=True, null=True)),
                ('focalLength35Equivalent', models.IntegerField(blank=True, null=True)),
                ('focal_length', models.FloatField(blank=True, null=True)),
                ('fstop', models.FloatField(blank=True, null=True)),
                ('height', models.IntegerField(default=0)),
                ('iso', models.IntegerField(blank=True, null=True)),
                ('lens', models.TextField(blank=True, null=True)),
                ('shutter_speed', models.TextField(blank=True, null=True)),
                ('size', models.IntegerField(default=0)),
                ('subjectDistance', models.FloatField(blank=True, null=True)),
                ('width', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(1)])),
                ('kind', models.CharField(choices=[('USER', 'User Labelled'), ('CLUSTER', 'Cluster ID'), ('UNKNOWN', 'Unknown Person')], max_length=10)),
                ('cover_photo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to='api.photo')),
                ('cluster_owner', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('face_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mean_face_encoding', models.TextField()),
                ('cluster_id', models.IntegerField(null=True)),
                ('name', models.TextField(null=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clusters', to='api.person')),
                ('owner', models.ForeignKey(default=None, null=True, on_delete=models.SET(api.models.user.get_deleted_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('path', models.TextField(blank=True, default='')),
                ('type', models.PositiveIntegerField(blank=True, choices=[(1, 'Image'), (2, 'Video'), (3, 'Metadata File e.g. XMP'), (4, 'Raw File'), (5, 'Unknown')])),
                ('missing', models.BooleanField(default=False)),
                ('embedded_media', models.ManyToManyField(to='api.file')),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='files',
            field=models.ManyToManyField(to='api.file'),
        ),
        migrations.AddField(
            model_name='photo',
            name='main_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_photo', to='api.file'),
        ),
        migrations.RemoveField(
            model_name='photo',
            name='image_paths',
        ),
        migrations.AlterField(
            model_name='photo',
            name='size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='faces')),
                ('cluster_probability', models.FloatField(db_index=True, default=0.0)),
                ('location_top', models.IntegerField()),
                ('location_bottom', models.IntegerField()),
                ('location_left', models.IntegerField()),
                ('location_right', models.IntegerField()),
                ('encoding', models.TextField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='faces', to='api.person')),
                ('photo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='api.photo')),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faces', to='api.cluster')),
                ('classification_probability', models.FloatField(db_index=True, default=0.0)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='cover_face',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face', to='api.face'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(db_index=True, max_length=128, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AddField(
            model_name='photo',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='deleted',
            new_name='in_trashcan',
        ),
        migrations.AddField(
            model_name='photo',
            name='removed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='AlbumDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, db_index=True, default='', max_length=512)),
                ('date', models.DateField(db_index=True, null=True)),
                ('favorited', models.BooleanField(db_index=True, default=False)),
                ('location', models.JSONField(blank=True, db_index=True, null=True)),
                ('owner', models.ForeignKey(default=None, on_delete=models.SET(api.models.user.get_deleted_user), to=settings.AUTH_USER_MODEL)),
                ('photos', models.ManyToManyField(to='api.photo')),
                ('shared_to', models.ManyToManyField(related_name='album_date_shared_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('date', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='thumbnail', serialize=False, to='api.photo')),
                ('thumbnail_big', models.ImageField(upload_to='thumbnails_big')),
                ('square_thumbnail', models.ImageField(upload_to='square_thumbnails')),
                ('square_thumbnail_small', models.ImageField(upload_to='square_thumbnails_small')),
                ('aspect_ratio', models.FloatField(blank=True, null=True)),
                ('dominant_color', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlbumThing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=512)),
                ('thing_type', models.CharField(db_index=True, max_length=512, null=True)),
                ('favorited', models.BooleanField(db_index=True, default=False)),
                ('owner', models.ForeignKey(default=None, on_delete=models.SET(api.models.user.get_deleted_user), to=settings.AUTH_USER_MODEL)),
                ('photos', models.ManyToManyField(to='api.photo')),
                ('shared_to', models.ManyToManyField(related_name='album_thing_shared_to', to=settings.AUTH_USER_MODEL)),
                ('cover_photos', models.ManyToManyField(related_name='album_thing_cover_photos', to='api.photo')),
                ('photo_count', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': set(),
                'constraints': [models.UniqueConstraint(fields=('title', 'thing_type', 'owner'), name='unique AlbumThing')],
            },
        ),
        migrations.RemoveField(
            model_name='photo',
            name='aspect_ratio',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='dominant_color',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='square_thumbnail',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='square_thumbnail_small',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='thumbnail_big',
        ),
        migrations.CreateModel(
            name='AlbumAuto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled Album', max_length=512)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('created_on', models.DateTimeField(db_index=True)),
                ('gps_lat', models.FloatField(blank=True, null=True)),
                ('gps_lon', models.FloatField(blank=True, null=True)),
                ('favorited', models.BooleanField(db_index=True, default=False)),
                ('owner', models.ForeignKey(default=None, on_delete=models.SET(api.models.user.get_deleted_user), to=settings.AUTH_USER_MODEL)),
                ('photos', models.ManyToManyField(to='api.photo')),
                ('shared_to', models.ManyToManyField(related_name='album_auto_shared_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('timestamp', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='AlbumPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=512)),
                ('geolocation_level', models.IntegerField(db_index=True, null=True)),
                ('favorited', models.BooleanField(db_index=True, default=False)),
                ('owner', models.ForeignKey(default=None, on_delete=models.SET(api.models.user.get_deleted_user), to=settings.AUTH_USER_MODEL)),
                ('photos', models.ManyToManyField(to='api.photo')),
                ('shared_to', models.ManyToManyField(related_name='album_place_shared_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('title', 'owner')},
            },
        ),
        migrations.RemoveField(
            model_name='photo',
            name='captions_json',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='search_captions',
        ),
        migrations.CreateModel(
            name='PhotoSearch',
            fields=[
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='search_instance', serialize=False, to='api.photo')),
                ('search_captions', models.TextField(blank=True, db_index=True, null=True)),
                ('search_location', models.TextField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'api_photo_search',
            },
        ),
        migrations.AddField(
            model_name='face',
            name='classification_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classification_faces', to='api.person'),
        ),
        migrations.RemoveField(
            model_name='photo',
            name='search_location',
        ),
        migrations.CreateModel(
            name='PhotoCaption',
            fields=[
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='caption_instance', serialize=False, to='api.photo')),
                ('captions_json', models.JSONField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'api_photo_caption',
            },
        ),
        migrations.AlterField(
            model_name='face',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='faces', to='api.person'),
        ),
        migrations.RemoveField(
            model_name='Photo',
            name='clip_embeddings',
        ),
        migrations.AddField(
            model_name='Photo',
            name='clip_embeddings',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AlbumUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('created_on', models.DateTimeField(auto_now=True, db_index=True)),
                ('favorited', models.BooleanField(db_index=True, default=False)),
                ('owner', models.ForeignKey(default=None, on_delete=models.SET(api.models.user.get_deleted_user), to=settings.AUTH_USER_MODEL)),
                ('photos', models.ManyToManyField(to='api.photo')),
                ('shared_to', models.ManyToManyField(related_name='album_user_shared_to', to=settings.AUTH_USER_MODEL)),
                ('cover_photo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='album_user', to='api.photo')),
            ],
            options={
                'unique_together': {('title', 'owner')},
            },
        ),
        migrations.CreateModel(
            name='AlbumUserShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(db_index=True, default=False)),
                ('slug', models.SlugField(blank=True, max_length=64, null=True, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('album', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='share', to='api.albumuser')),
            ],
        ),
        migrations.AddField(
            model_name='face',
            name='cluster_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cluster_faces', to='api.person'),
        ),
        migrations.AddField(
            model_name='photo',
            name='perceptual_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='LongRunningJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.PositiveIntegerField(choices=[(1, 'Scan Photos'), (2, 'Generate Event Albums'), (3, 'Regenerate Event Titles'), (4, 'Train Faces'), (5, 'Delete Missing Photos'), (7, 'Scan Faces'), (6, 'Calculate Clip Embeddings'), (8, 'Find Similar Faces'), (9, 'Download Selected Photos'), (10, 'Download Models'), (11, 'Add Geolocation'), (12, 'Generate Tags'), (13, 'Generate Face Embeddings'), (14, 'Scan Missing Photos'), (15, 'Detect Duplicate Photos')])),
                ('finished', models.BooleanField(default=False)),
                ('failed', models.BooleanField(default=False)),
                ('job_id', models.CharField(db_index=True, max_length=36, unique=True)),
                ('queued_at', models.DateTimeField(default=datetime.datetime.now)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('started_by', models.ForeignKey(default=None, on_delete=models.SET(api.models.user.get_deleted_user), to=settings.AUTH_USER_MODEL)),
                ('progress_current', models.PositiveIntegerField(default=0)),
                ('progress_target', models.PositiveIntegerField(default=0)),
                ('progress_step', models.CharField(blank=True, max_length=100, null=True)),
                ('result', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoStack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stack_type', models.CharField(choices=[('exact_copy', 'Exact Copies'), ('visual_duplicate', 'Visual Duplicates'), ('raw_jpeg', 'RAW + JPEG Pair'), ('burst', 'Burst Sequence'), ('bracket', 'Exposure Bracket'), ('live_photo', 'Live Photo'), ('manual', 'Manual Stack')], db_index=True, default='visual_duplicate', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('dismissed', 'Dismissed')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('sequence_start', models.DateTimeField(blank=True, null=True)),
                ('sequence_end', models.DateTimeField(blank=True, null=True)),
                ('potential_savings', models.BigIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=models.SET(api.models.user.get_deleted_user), related_name='photo_stacks', to=settings.AUTH_USER_MODEL)),
                ('primary_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_in_stack', to='api.photo')),
            ],
            options={
                'verbose_name': 'Photo Stack',
                'verbose_name_plural': 'Photo Stacks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'stack_type', 'status'], name='api_photost_owner_i_abc123_idx'), models.Index(fields=['owner', 'status'], name='api_photost_owner_i_def456_idx')],
            },
        ),
        migrations.AddField(
            model_name='photo',
            name='stack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='api.photostack'),
        ),
        migrations.AddField(
            model_name='photo',
            name='exif_timestamp_subsec',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='image_sequence_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    code=flush_deferred_schema_sql,
                    reverse_code=migrations.RunPython.noop,
                ),
                migrations.RunPython(
                    code=migrate_forward,
                    reverse_code=migrate_reverse,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='photo',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                migrations.AlterField(
                    model_name='photo',
                    name='image_hash',
                    field=models.CharField(db_index=True, max_length=64, unique=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name='MetadataEdit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('synced_to_file', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Metadata Edit',
                'verbose_name_plural': 'Metadata Edits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetadataFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_type', models.CharField(choices=[('xmp', 'XMP Sidecar'), ('json', 'JSON Metadata'), ('exif', 'EXIF Extract'), ('other', 'Other')], default='xmp', max_length=10)),
                ('source', models.CharField(choices=[('original', 'Original Sidecar'), ('software', 'Software Generated'), ('librephotos', 'LibrePhotos Generated'), ('user', 'User Created')], default='original', max_length=20)),
                ('priority', models.IntegerField(default=0)),
                ('creator_software', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Metadata File',
                'verbose_name_plural': 'Metadata Files',
                'ordering': ['-priority', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PhotoMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aperture', models.FloatField(blank=True, db_index=True, null=True)),
                ('shutter_speed', models.CharField(blank=True, max_length=20, null=True)),
                ('shutter_speed_seconds', models.FloatField(blank=True, null=True)),
                ('iso', models.IntegerField(blank=True, db_index=True, null=True)),
                ('focal_length', models.FloatField(blank=True, null=True)),
                ('focal_length_35mm', models.IntegerField(blank=True, null=True)),
                ('exposure_compensation', models.FloatField(blank=True, null=True)),
                ('flash_fired', models.BooleanField(blank=True, null=True)),
                ('metering_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('white_balance', models.CharField(blank=True, max_length=50, null=True)),
                ('camera_make', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('camera_model', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('lens_make', models.CharField(blank=True, max_length=100, null=True)),
                ('lens_model', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('orientation', models.IntegerField(blank=True, null=True)),
                ('color_space', models.CharField(blank=True, max_length=50, null=True)),
                ('bit_depth', models.IntegerField(blank=True, null=True)),
                ('date_taken', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('date_taken_subsec', models.CharField(blank=True, max_length=10, null=True)),
                ('date_modified', models.DateTimeField(blank=True, null=True)),
                ('timezone_offset', models.CharField(blank=True, max_length=10, null=True)),
                ('gps_latitude', models.FloatField(blank=True, db_index=True, null=True)),
                ('gps_longitude', models.FloatField(blank=True, db_index=True, null=True)),
                ('gps_altitude', models.FloatField(blank=True, null=True)),
                ('location_country', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('location_state', models.CharField(blank=True, max_length=100, null=True)),
                ('location_city', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('location_address', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('keywords', models.JSONField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, db_index=True, null=True)),
                ('copyright', models.TextField(blank=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=200, null=True)),
                ('source', models.CharField(choices=[('embedded', 'Embedded in File'), ('sidecar', 'XMP Sidecar'), ('user_edit', 'User Edit'), ('computed', 'Computed')], default='embedded', max_length=20)),
                ('raw_exif', models.JSONField(blank=True, null=True)),
                ('raw_xmp', models.JSONField(blank=True, null=True)),
                ('raw_iptc', models.JSONField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Photo Metadata',
                'verbose_name_plural': 'Photo Metadata',
            },
        ),
        migrations.CreateModel(
            name='StackReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('pending', 'Pending Review'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], db_index=True, default='pending', max_length=20)),
                ('trashed_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Stack Review',
                'verbose_name_plural': 'Stack Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='photostack',
            name='api_photost_owner_i_abc123_idx',
        ),
        migrations.RemoveIndex(
            model_name='photostack',
            name='api_photost_owner_i_def456_idx',
        ),
        migrations.RemoveField(
            model_name='photostack',
            name='status',
        ),
        migrations.AlterField(
            model_name='photostack',
            name='owner',
            field=models.ForeignKey(on_delete=models.SET(api.models.user.get_deleted_user), related_name='photo_stacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='photostack',
            index=models.Index(fields=['owner', 'stack_type'], name='api_photost_owner_i_40a369_idx'),
        ),
        migrations.AddField(
            model_name='metadataedit',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_edits', to='api.photo'),
        ),
        migrations.AddField(
            model_name='metadataedit',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(api.models.user.get_deleted_user), related_name='metadata_edits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='metadatafile',
            name='file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_info', to='api.file'),
        ),
        migrations.AddField(
            model_name='metadatafile',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_files', to='api.photo'),
        ),
        migrations.AddField(
            model_name='photometadata',
            name='photo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='api.photo'),
        ),
        migrations.AddField(
            model_name='stackreview',
            name='kept_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kept_in_reviews', to='api.photo'),
        ),
        migrations.AddField(
            model_name='stackreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=models.SET(api.models.user.get_deleted_user), related_name='stack_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stackreview',
            name='stack',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='api.photostack'),
        ),
        migrations.AddIndex(
            model_name='metadataedit',
            index=models.Index(fields=['photo', '-created_at'], name='api_metadat_photo_i_21e478_idx'),
        ),
        migrations.AddIndex(
            model_name='photometadata',
            index=models.Index(fields=['camera_make', 'camera_model'], name='api_photome_camera__361eac_idx'),
        ),
        migrations.AddIndex(
            model_name='photometadata',
            index=models.Index(fields=['date_taken'], name='api_photome_date_ta_35e59b_idx'),
        ),
        migrations.AddIndex(
            model_name='photometadata',
            index=models.Index(fields=['location_country', 'location_city'], name='api_photome_locatio_1ca8bb_idx'),
        ),
        migrations.AddIndex(
            model_name='stackreview',
            index=models.Index(fields=['reviewer', 'decision'], name='api_stackre_reviewe_48380f_idx'),
        ),
    ]
