# Generated by Django 3.1.8 on 2021-07-25 21:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_add_aspect_ratio"),
        ("api", "0009_add_clip_embedding_field"),
    ]

    operations = []
