# Generated by Django 3.1.8 on 2021-08-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_merge_20210725_1547"),
    ]

    run_before = [("api", "0011_b_migrate_favorited_to_rating")]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="rating",
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
