# Generated by Django 3.1.8 on 2021-08-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_add_image_scale_and_misc"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="save_metadata_to_disk",
            field=models.TextField(
                choices=[
                    ("OFF", "Off"),
                    ("MEDIA_FILE", "Media File"),
                    ("SIDECAR_FILE", "Sidecar File"),
                ],
                default="OFF",
            ),
        ),
    ]
