# Generated by Django 3.1.14 on 2022-03-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0023_photo_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="timestamp",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
