# Generated by Django 3.1.14 on 2022-07-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_add_metadata_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="shutter_speed",
            field=models.TextField(blank=True, null=True),
        ),
    ]
