# Generated by Django 3.1.14 on 2022-09-01 16:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0030_user_confidence_person"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="albumdate",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="person",
            name="account",
        ),
    ]
