# Generated by Django 3.1.14 on 2022-09-02 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0032_always_have_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="face",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="faces",
                to="api.person",
            ),
        ),
    ]
