# Generated by Django 3.1.14 on 2022-10-08 20:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_allow_deleting_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='timestamp',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
            preserve_default=False,
        ),
        migrations.RunSQL("UPDATE api_face SET timestamp = (SELECT exif_timestamp FROM api_photo WHERE image_hash = photo_id);")
    ]
