# Generated by Django 3.1.14 on 2022-12-21 09:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0038_add_main_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="image_paths",
        ),
    ]
