# Generated by Django 4.2rc1 on 2023-04-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0042_alter_albumuser_cover_photo_alter_photo_main_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="size",
            field=models.BigIntegerField(default=0),
        ),
    ]
