# Generated by Django 4.2rc1 on 2023-04-07 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0044_alter_cluster_person_alter_person_cluster_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="face",
            name="cluster",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="faces",
                to="api.cluster",
            ),
        ),
    ]
