# Generated by Django 4.2.1 on 2023-06-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0049_fix_metadata_files_as_main_files"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="face_count",
            field=models.IntegerField(default=0),
        ),
    ]
