# Generated by Django 4.2.1 on 2023-06-26 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0051_set_person_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="name",
            field=models.CharField(
                max_length=128,
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
    ]
