# Generated by Django 4.2.9 on 2024-02-02 16:36

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0057_remove_face_image_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars"),
        ),
        migrations.AlterField(
            model_name="user",
            name="nextcloud_app_password",
            field=django_cryptography.fields.encrypt(
                models.CharField(blank=True, default=None, max_length=64, null=True)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="nextcloud_scan_directory",
            field=models.CharField(
                blank=True, db_index=True, max_length=512, null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="nextcloud_server_address",
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="nextcloud_username",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
