# Generated by Django 4.2.11 on 2024-03-29 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0058_alter_user_avatar_alter_user_nextcloud_app_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="cover_face",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="face",
                to="api.face",
            ),
        ),
    ]
