# Generated by Django 4.2.11 on 2024-03-29 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0060_apply_default_face_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="name",
            field=models.CharField(
                db_index=True,
                max_length=128,
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
    ]
