# Generated by Django 4.2.18 on 2025-03-29 12:38

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0075_alter_face_cluster_person"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="path",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="longrunningjob",
            name="job_type",
            field=models.PositiveIntegerField(
                choices=[
                    (1, "Scan Photos"),
                    (2, "Generate Event Albums"),
                    (3, "Regenerate Event Titles"),
                    (4, "Train Faces"),
                    (5, "Delete Missing Photos"),
                    (7, "Scan Faces"),
                    (6, "Calculate Clip Embeddings"),
                    (8, "Find Similar Faces"),
                    (9, "Download Selected Photos"),
                    (10, "Download Models"),
                    (11, "Add Geolocation"),
                    (12, "Generate Tags"),
                    (13, "Generate Face Embeddings"),
                    (14, "Scan Missing Photos"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="nextcloud_app_password",
            field=django_cryptography.fields.encrypt(
                models.CharField(blank=True, default="", max_length=64)
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="nextcloud_scan_directory",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=512
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="nextcloud_server_address",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="user",
            name="nextcloud_username",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
