# Generated by Django 4.2.18 on 2025-03-29 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0076_alter_file_path_alter_longrunningjob_job_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="albumdate",
            name="title",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=512
            ),
        ),
    ]
