# Generated by Django 4.2.18 on 2025-05-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0078_create_photo_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="albumauto",
            name="title",
            field=models.CharField(default="Untitled Album", max_length=512),
        ),
    ]
