# Generated by Django 5.2.4 on 2025-08-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_convert_arrayfield_to_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumuser',
            name='public_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='albumuser',
            name='public_slug',
            field=models.SlugField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
