# Generated by Django 5.2.4 on 2025-08-17 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_albumuser_public_expires_at_albumuser_public_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumuser',
            name='public',
        ),
        migrations.RemoveField(
            model_name='albumuser',
            name='public_expires_at',
        ),
        migrations.RemoveField(
            model_name='albumuser',
            name='public_slug',
        ),
        migrations.CreateModel(
            name='AlbumUserShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(db_index=True, default=False)),
                ('slug', models.SlugField(blank=True, max_length=64, null=True, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('album', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='share', to='api.albumuser')),
            ],
        ),
    ]
