# Generated by Django 5.2.4 on 2025-08-22 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_remove_albumuser_public_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('created_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('folder_path', models.TextField()),
                ('include_subdirectories', models.BooleanField(default=True)),
                ('public', models.BooleanField(db_index=True, default=False)),
                ('favorited', models.BooleanField(db_index=True, default=False)),
                ('cover_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folder_album_cover', to='api.photo')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
                'unique_together': {('folder_path', 'owner')},
            },
        ),
    ]
