# Generated by Django 5.2.4 on 2025-08-22 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_add_folder_album'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FolderAlbum',
        ),
    ]
