# Generated by Django 5.2.4 on 2025-08-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_remove_folder_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='text_alignment',
            field=models.TextField(choices=[('left', 'Left'), ('right', 'Right')], default='right'),
        ),
    ]
