# Generated by Django 5.2.4 on 2025-08-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_add_text_alignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='header_size',
            field=models.TextField(choices=[('large', 'Large'), ('normal', 'Normal'), ('small', 'Small')], default='large'),
        ),
    ]
