# Generated by Django 5.2.4 on 2025-08-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_add_header_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='scan_directory',
            field=models.CharField(blank=True, db_index=True, default='', max_length=512),
        ),
    ]
