# Generated by Django 5.2.7 on 2025-10-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_alter_user_scan_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skip_raw_files',
            field=models.BooleanField(default=False),
        ),
    ]
