# Generated by Django 5.2.9 on 2025-12-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_add_progress_step_and_result_to_longrunningjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='duplicate_clear_existing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='duplicate_sensitivity',
            field=models.TextField(choices=[('strict', 'Strict'), ('normal', 'Normal'), ('loose', 'Loose')], default='normal'),
        ),
    ]
