# Generated by Django 5.2.9 on 2025-12-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_remove_photostack_potential_savings_and_more'),
    ]

    operations = [
        # Drop the unique index created by migration 0099 (it was created as an index, not a constraint)
        migrations.RunSQL(
            sql="DROP INDEX IF EXISTS api_photo_image_hash_unique;",
            reverse_sql="CREATE UNIQUE INDEX IF NOT EXISTS api_photo_image_hash_unique ON api_photo(image_hash);",
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_hash',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
