# Generated by Django 5.2.9 on 2025-12-26 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_alter_photo_image_hash'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='longrunningjob',
            options={'ordering': ['-queued_at'], 'verbose_name': 'Long Running Job', 'verbose_name_plural': 'Long Running Jobs'},
        ),
    ]
