# Generated by Django 5.0 on 2024-12-26

from django.db import migrations, models

import api.models.user


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0106_alter_longrunningjob_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="burst_detection_rules",
            field=models.JSONField(
                default=api.models.user.get_default_config_burst_detection_rules
            ),
        ),
    ]
