# Generated by Django 5.2.9 on 2026-01-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0110_fix_file_embedded_media_self_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='embedded_media',
            field=models.ManyToManyField(to='api.file'),
        ),
    ]
