# Generated by Django 5.2.9 on 2026-01-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0112_convert_file_stacks_to_variants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photostack',
            name='stack_type',
            field=models.CharField(choices=[('burst', 'Burst Sequence'), ('bracket', 'Exposure Bracket'), ('manual', 'Manual Stack'), ('raw_jpeg', 'RAW + JPEG Pair (Deprecated)'), ('live_photo', 'Live Photo (Deprecated)')], db_index=True, default='manual', max_length=20),
        ),
    ]
