# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0121_add_default_tagging_model"),
        ("api", "0121_user_save_face_tags_to_disk"),
    ]

    operations = []
