# Generated by Django 5.2.14 on 2026-07-17 05:05

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0127_migrate_photon_provider_robustly"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("disabled", "Disabled"),
                            ("custom", "Custom SMTP server"),
                            ("sendgrid", "SendGrid"),
                            ("mailgun", "Mailgun"),
                            ("postmark", "Postmark"),
                            ("brevo", "Brevo"),
                            ("smtp2go", "SMTP2GO"),
                            ("ses", "Amazon SES"),
                        ],
                        default="disabled",
                        max_length=32,
                    ),
                ),
                (
                    "from_email",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("host", models.CharField(blank=True, default="", max_length=255)),
                ("port", models.PositiveIntegerField(default=587)),
                ("use_tls", models.BooleanField(default=True)),
                ("use_ssl", models.BooleanField(default=False)),
                ("username", models.CharField(blank=True, default="", max_length=255)),
                (
                    "secret",
                    django_cryptography.fields.encrypt(
                        models.TextField(blank=True, default="")
                    ),
                ),
            ],
            options={
                "verbose_name": "Email configuration",
                "verbose_name_plural": "Email configuration",
            },
        ),
    ]
