# Generated by Django 5.2.14 on 2026-07-22 17:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0128_emailconfig"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="metadataedit",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "Metadata Edit",
                "verbose_name_plural": "Metadata Edits",
            },
        ),
    ]
