# Generated by Django 5.2.14 on 2026-07-24 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0132_alter_longrunningjob_job_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhotoOcr",
            fields=[
                (
                    "photo",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="ocr",
                        serialize=False,
                        to="api.photo",
                    ),
                ),
                ("text", models.TextField(blank=True, null=True)),
                ("blocks", models.JSONField(blank=True, default=list)),
                ("engine", models.CharField(blank=True, default="", max_length=64)),
                ("mean_confidence", models.FloatField(blank=True, null=True)),
                ("text_area_fraction", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "api_photo_ocr",
            },
        ),
    ]
