/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as LoginImport } from './routes/login'
import { Route as PublicRouteImport } from './routes/public/route'
import { Route as ProtectedRouteImport } from './routes/_protected/route'
import { Route as ProtectedIndexImport } from './routes/_protected/index'
import { Route as PublicUsersImport } from './routes/public/$users'
import { Route as ProtectedVideosImport } from './routes/_protected/videos'
import { Route as ProtectedUsersImport } from './routes/_protected/users'
import { Route as ProtectedSettingsImport } from './routes/_protected/settings'
import { Route as ProtectedRecentImport } from './routes/_protected/recent'
import { Route as ProtectedProfileImport } from './routes/_protected/profile'
import { Route as ProtectedPhotosImport } from './routes/_protected/photos'
import { Route as ProtectedNotimestampImport } from './routes/_protected/notimestamp'
import { Route as ProtectedLibraryImport } from './routes/_protected/library'
import { Route as ProtectedHiddenImport } from './routes/_protected/hidden'
import { Route as ProtectedFavoritesImport } from './routes/_protected/favorites'
import { Route as ProtectedFacesImport } from './routes/_protected/faces'
import { Route as ProtectedDeletedImport } from './routes/_protected/deleted'
import { Route as ProtectedAdminImport } from './routes/_protected/admin'
import { Route as ProtectedSearchQueryImport } from './routes/_protected/search.$query'
import { Route as ProtectedPhotoIdImport } from './routes/_protected/photo.$id'
import { Route as ProtectedDatavizWordcloudsImport } from './routes/_protected/dataviz/wordclouds'
import { Route as ProtectedDatavizTimelineImport } from './routes/_protected/dataviz/timeline'
import { Route as ProtectedDatavizSocialgraphImport } from './routes/_protected/dataviz/socialgraph'
import { Route as ProtectedDatavizPlacetreeImport } from './routes/_protected/dataviz/placetree'
import { Route as ProtectedDatavizFacescatterImport } from './routes/_protected/dataviz/facescatter'
import { Route as ProtectedAlbumUserIndexImport } from './routes/_protected/album/user.index'
import { Route as ProtectedAlbumThingsIndexImport } from './routes/_protected/album/things.index'
import { Route as ProtectedAlbumPlacesIndexImport } from './routes/_protected/album/places.index'
import { Route as ProtectedAlbumPersonsIndexImport } from './routes/_protected/album/persons.index'
import { Route as ProtectedAlbumEventsIndexImport } from './routes/_protected/album/events.index'
import { Route as ProtectedSharedTomeTabImport } from './routes/_protected/shared/tome.$tab'
import { Route as ProtectedSharedFrommeTabImport } from './routes/_protected/shared/fromme.$tab'
import { Route as ProtectedAlbumUserIdImport } from './routes/_protected/album/user.$id'
import { Route as ProtectedAlbumThingsIdImport } from './routes/_protected/album/things.$id'
import { Route as ProtectedAlbumPlacesIdImport } from './routes/_protected/album/places.$id'
import { Route as ProtectedAlbumPersonsIdImport } from './routes/_protected/album/persons.$id'
import { Route as ProtectedAlbumEventsIdImport } from './routes/_protected/album/events.$id'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const PublicRouteRoute = PublicRouteImport.update({
  id: '/public',
  path: '/public',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedRouteRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedIndexRoute = ProtectedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const PublicUsersRoute = PublicUsersImport.update({
  id: '/$users',
  path: '/$users',
  getParentRoute: () => PublicRouteRoute,
} as any)

const ProtectedVideosRoute = ProtectedVideosImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const ProtectedUsersRoute = ProtectedUsersImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const ProtectedSettingsRoute = ProtectedSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const ProtectedRecentRoute = ProtectedRecentImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const ProtectedProfileRoute = ProtectedProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const ProtectedPhotosRoute = ProtectedPhotosImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const ProtectedNotimestampRoute = ProtectedNotimestampImport.update({
  id: '/notimestamp',
  path: '/notimestamp',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const ProtectedLibraryRoute = ProtectedLibraryImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const ProtectedHiddenRoute = ProtectedHiddenImport.update({
  id: '/hidden',
  path: '/hidden',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const ProtectedFavoritesRoute = ProtectedFavoritesImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const ProtectedFacesRoute = ProtectedFacesImport.update({
  id: '/faces',
  path: '/faces',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const ProtectedDeletedRoute = ProtectedDeletedImport.update({
  id: '/deleted',
  path: '/deleted',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const ProtectedAdminRoute = ProtectedAdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const ProtectedSearchQueryRoute = ProtectedSearchQueryImport.update({
  id: '/search/$query',
  path: '/search/$query',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const ProtectedPhotoIdRoute = ProtectedPhotoIdImport.update({
  id: '/photo/$id',
  path: '/photo/$id',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const ProtectedDatavizWordcloudsRoute = ProtectedDatavizWordcloudsImport.update(
  {
    id: '/dataviz/wordclouds',
    path: '/dataviz/wordclouds',
    getParentRoute: () => ProtectedRouteRoute,
  } as any,
)

const ProtectedDatavizTimelineRoute = ProtectedDatavizTimelineImport.update({
  id: '/dataviz/timeline',
  path: '/dataviz/timeline',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const ProtectedDatavizSocialgraphRoute =
  ProtectedDatavizSocialgraphImport.update({
    id: '/dataviz/socialgraph',
    path: '/dataviz/socialgraph',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

const ProtectedDatavizPlacetreeRoute = ProtectedDatavizPlacetreeImport.update({
  id: '/dataviz/placetree',
  path: '/dataviz/placetree',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const ProtectedDatavizFacescatterRoute =
  ProtectedDatavizFacescatterImport.update({
    id: '/dataviz/facescatter',
    path: '/dataviz/facescatter',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

const ProtectedAlbumUserIndexRoute = ProtectedAlbumUserIndexImport.update({
  id: '/album/user/',
  path: '/album/user/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const ProtectedAlbumThingsIndexRoute = ProtectedAlbumThingsIndexImport.update({
  id: '/album/things/',
  path: '/album/things/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const ProtectedAlbumPlacesIndexRoute = ProtectedAlbumPlacesIndexImport.update({
  id: '/album/places/',
  path: '/album/places/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const ProtectedAlbumPersonsIndexRoute = ProtectedAlbumPersonsIndexImport.update(
  {
    id: '/album/persons/',
    path: '/album/persons/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any,
)

const ProtectedAlbumEventsIndexRoute = ProtectedAlbumEventsIndexImport.update({
  id: '/album/events/',
  path: '/album/events/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const ProtectedSharedTomeTabRoute = ProtectedSharedTomeTabImport.update({
  id: '/shared/tome/$tab',
  path: '/shared/tome/$tab',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const ProtectedSharedFrommeTabRoute = ProtectedSharedFrommeTabImport.update({
  id: '/shared/fromme/$tab',
  path: '/shared/fromme/$tab',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const ProtectedAlbumUserIdRoute = ProtectedAlbumUserIdImport.update({
  id: '/album/user/$id',
  path: '/album/user/$id',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const ProtectedAlbumThingsIdRoute = ProtectedAlbumThingsIdImport.update({
  id: '/album/things/$id',
  path: '/album/things/$id',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const ProtectedAlbumPlacesIdRoute = ProtectedAlbumPlacesIdImport.update({
  id: '/album/places/$id',
  path: '/album/places/$id',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const ProtectedAlbumPersonsIdRoute = ProtectedAlbumPersonsIdImport.update({
  id: '/album/persons/$id',
  path: '/album/persons/$id',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const ProtectedAlbumEventsIdRoute = ProtectedAlbumEventsIdImport.update({
  id: '/album/events/$id',
  path: '/album/events/$id',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRoute
    }
    '/public': {
      id: '/public'
      path: '/public'
      fullPath: '/public'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/deleted': {
      id: '/_protected/deleted'
      path: '/deleted'
      fullPath: '/deleted'
      preLoaderRoute: typeof ProtectedDeletedImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/faces': {
      id: '/_protected/faces'
      path: '/faces'
      fullPath: '/faces'
      preLoaderRoute: typeof ProtectedFacesImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/favorites': {
      id: '/_protected/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof ProtectedFavoritesImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/hidden': {
      id: '/_protected/hidden'
      path: '/hidden'
      fullPath: '/hidden'
      preLoaderRoute: typeof ProtectedHiddenImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/library': {
      id: '/_protected/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof ProtectedLibraryImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/notimestamp': {
      id: '/_protected/notimestamp'
      path: '/notimestamp'
      fullPath: '/notimestamp'
      preLoaderRoute: typeof ProtectedNotimestampImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/photos': {
      id: '/_protected/photos'
      path: '/photos'
      fullPath: '/photos'
      preLoaderRoute: typeof ProtectedPhotosImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/profile': {
      id: '/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedProfileImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/recent': {
      id: '/_protected/recent'
      path: '/recent'
      fullPath: '/recent'
      preLoaderRoute: typeof ProtectedRecentImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/users': {
      id: '/_protected/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof ProtectedUsersImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/videos': {
      id: '/_protected/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof ProtectedVideosImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/public/$users': {
      id: '/public/$users'
      path: '/$users'
      fullPath: '/public/$users'
      preLoaderRoute: typeof PublicUsersImport
      parentRoute: typeof PublicRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/dataviz/facescatter': {
      id: '/_protected/dataviz/facescatter'
      path: '/dataviz/facescatter'
      fullPath: '/dataviz/facescatter'
      preLoaderRoute: typeof ProtectedDatavizFacescatterImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/dataviz/placetree': {
      id: '/_protected/dataviz/placetree'
      path: '/dataviz/placetree'
      fullPath: '/dataviz/placetree'
      preLoaderRoute: typeof ProtectedDatavizPlacetreeImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/dataviz/socialgraph': {
      id: '/_protected/dataviz/socialgraph'
      path: '/dataviz/socialgraph'
      fullPath: '/dataviz/socialgraph'
      preLoaderRoute: typeof ProtectedDatavizSocialgraphImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/dataviz/timeline': {
      id: '/_protected/dataviz/timeline'
      path: '/dataviz/timeline'
      fullPath: '/dataviz/timeline'
      preLoaderRoute: typeof ProtectedDatavizTimelineImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/dataviz/wordclouds': {
      id: '/_protected/dataviz/wordclouds'
      path: '/dataviz/wordclouds'
      fullPath: '/dataviz/wordclouds'
      preLoaderRoute: typeof ProtectedDatavizWordcloudsImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/photo/$id': {
      id: '/_protected/photo/$id'
      path: '/photo/$id'
      fullPath: '/photo/$id'
      preLoaderRoute: typeof ProtectedPhotoIdImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/search/$query': {
      id: '/_protected/search/$query'
      path: '/search/$query'
      fullPath: '/search/$query'
      preLoaderRoute: typeof ProtectedSearchQueryImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/album/events/$id': {
      id: '/_protected/album/events/$id'
      path: '/album/events/$id'
      fullPath: '/album/events/$id'
      preLoaderRoute: typeof ProtectedAlbumEventsIdImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/album/persons/$id': {
      id: '/_protected/album/persons/$id'
      path: '/album/persons/$id'
      fullPath: '/album/persons/$id'
      preLoaderRoute: typeof ProtectedAlbumPersonsIdImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/album/places/$id': {
      id: '/_protected/album/places/$id'
      path: '/album/places/$id'
      fullPath: '/album/places/$id'
      preLoaderRoute: typeof ProtectedAlbumPlacesIdImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/album/things/$id': {
      id: '/_protected/album/things/$id'
      path: '/album/things/$id'
      fullPath: '/album/things/$id'
      preLoaderRoute: typeof ProtectedAlbumThingsIdImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/album/user/$id': {
      id: '/_protected/album/user/$id'
      path: '/album/user/$id'
      fullPath: '/album/user/$id'
      preLoaderRoute: typeof ProtectedAlbumUserIdImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/shared/fromme/$tab': {
      id: '/_protected/shared/fromme/$tab'
      path: '/shared/fromme/$tab'
      fullPath: '/shared/fromme/$tab'
      preLoaderRoute: typeof ProtectedSharedFrommeTabImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/shared/tome/$tab': {
      id: '/_protected/shared/tome/$tab'
      path: '/shared/tome/$tab'
      fullPath: '/shared/tome/$tab'
      preLoaderRoute: typeof ProtectedSharedTomeTabImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/album/events/': {
      id: '/_protected/album/events/'
      path: '/album/events'
      fullPath: '/album/events'
      preLoaderRoute: typeof ProtectedAlbumEventsIndexImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/album/persons/': {
      id: '/_protected/album/persons/'
      path: '/album/persons'
      fullPath: '/album/persons'
      preLoaderRoute: typeof ProtectedAlbumPersonsIndexImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/album/places/': {
      id: '/_protected/album/places/'
      path: '/album/places'
      fullPath: '/album/places'
      preLoaderRoute: typeof ProtectedAlbumPlacesIndexImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/album/things/': {
      id: '/_protected/album/things/'
      path: '/album/things'
      fullPath: '/album/things'
      preLoaderRoute: typeof ProtectedAlbumThingsIndexImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/album/user/': {
      id: '/_protected/album/user/'
      path: '/album/user'
      fullPath: '/album/user'
      preLoaderRoute: typeof ProtectedAlbumUserIndexImport
      parentRoute: typeof ProtectedRouteImport
    }
  }
}

// Create and export the route tree

interface ProtectedRouteRouteChildren {
  ProtectedAdminRoute: typeof ProtectedAdminRoute
  ProtectedDeletedRoute: typeof ProtectedDeletedRoute
  ProtectedFacesRoute: typeof ProtectedFacesRoute
  ProtectedFavoritesRoute: typeof ProtectedFavoritesRoute
  ProtectedHiddenRoute: typeof ProtectedHiddenRoute
  ProtectedLibraryRoute: typeof ProtectedLibraryRoute
  ProtectedNotimestampRoute: typeof ProtectedNotimestampRoute
  ProtectedPhotosRoute: typeof ProtectedPhotosRoute
  ProtectedProfileRoute: typeof ProtectedProfileRoute
  ProtectedRecentRoute: typeof ProtectedRecentRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedUsersRoute: typeof ProtectedUsersRoute
  ProtectedVideosRoute: typeof ProtectedVideosRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedDatavizFacescatterRoute: typeof ProtectedDatavizFacescatterRoute
  ProtectedDatavizPlacetreeRoute: typeof ProtectedDatavizPlacetreeRoute
  ProtectedDatavizSocialgraphRoute: typeof ProtectedDatavizSocialgraphRoute
  ProtectedDatavizTimelineRoute: typeof ProtectedDatavizTimelineRoute
  ProtectedDatavizWordcloudsRoute: typeof ProtectedDatavizWordcloudsRoute
  ProtectedPhotoIdRoute: typeof ProtectedPhotoIdRoute
  ProtectedSearchQueryRoute: typeof ProtectedSearchQueryRoute
  ProtectedAlbumEventsIdRoute: typeof ProtectedAlbumEventsIdRoute
  ProtectedAlbumPersonsIdRoute: typeof ProtectedAlbumPersonsIdRoute
  ProtectedAlbumPlacesIdRoute: typeof ProtectedAlbumPlacesIdRoute
  ProtectedAlbumThingsIdRoute: typeof ProtectedAlbumThingsIdRoute
  ProtectedAlbumUserIdRoute: typeof ProtectedAlbumUserIdRoute
  ProtectedSharedFrommeTabRoute: typeof ProtectedSharedFrommeTabRoute
  ProtectedSharedTomeTabRoute: typeof ProtectedSharedTomeTabRoute
  ProtectedAlbumEventsIndexRoute: typeof ProtectedAlbumEventsIndexRoute
  ProtectedAlbumPersonsIndexRoute: typeof ProtectedAlbumPersonsIndexRoute
  ProtectedAlbumPlacesIndexRoute: typeof ProtectedAlbumPlacesIndexRoute
  ProtectedAlbumThingsIndexRoute: typeof ProtectedAlbumThingsIndexRoute
  ProtectedAlbumUserIndexRoute: typeof ProtectedAlbumUserIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedAdminRoute: ProtectedAdminRoute,
  ProtectedDeletedRoute: ProtectedDeletedRoute,
  ProtectedFacesRoute: ProtectedFacesRoute,
  ProtectedFavoritesRoute: ProtectedFavoritesRoute,
  ProtectedHiddenRoute: ProtectedHiddenRoute,
  ProtectedLibraryRoute: ProtectedLibraryRoute,
  ProtectedNotimestampRoute: ProtectedNotimestampRoute,
  ProtectedPhotosRoute: ProtectedPhotosRoute,
  ProtectedProfileRoute: ProtectedProfileRoute,
  ProtectedRecentRoute: ProtectedRecentRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedUsersRoute: ProtectedUsersRoute,
  ProtectedVideosRoute: ProtectedVideosRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedDatavizFacescatterRoute: ProtectedDatavizFacescatterRoute,
  ProtectedDatavizPlacetreeRoute: ProtectedDatavizPlacetreeRoute,
  ProtectedDatavizSocialgraphRoute: ProtectedDatavizSocialgraphRoute,
  ProtectedDatavizTimelineRoute: ProtectedDatavizTimelineRoute,
  ProtectedDatavizWordcloudsRoute: ProtectedDatavizWordcloudsRoute,
  ProtectedPhotoIdRoute: ProtectedPhotoIdRoute,
  ProtectedSearchQueryRoute: ProtectedSearchQueryRoute,
  ProtectedAlbumEventsIdRoute: ProtectedAlbumEventsIdRoute,
  ProtectedAlbumPersonsIdRoute: ProtectedAlbumPersonsIdRoute,
  ProtectedAlbumPlacesIdRoute: ProtectedAlbumPlacesIdRoute,
  ProtectedAlbumThingsIdRoute: ProtectedAlbumThingsIdRoute,
  ProtectedAlbumUserIdRoute: ProtectedAlbumUserIdRoute,
  ProtectedSharedFrommeTabRoute: ProtectedSharedFrommeTabRoute,
  ProtectedSharedTomeTabRoute: ProtectedSharedTomeTabRoute,
  ProtectedAlbumEventsIndexRoute: ProtectedAlbumEventsIndexRoute,
  ProtectedAlbumPersonsIndexRoute: ProtectedAlbumPersonsIndexRoute,
  ProtectedAlbumPlacesIndexRoute: ProtectedAlbumPlacesIndexRoute,
  ProtectedAlbumThingsIndexRoute: ProtectedAlbumThingsIndexRoute,
  ProtectedAlbumUserIndexRoute: ProtectedAlbumUserIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicUsersRoute: typeof PublicUsersRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicUsersRoute: PublicUsersRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof ProtectedRouteRouteWithChildren
  '/public': typeof PublicRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof ProtectedAdminRoute
  '/deleted': typeof ProtectedDeletedRoute
  '/faces': typeof ProtectedFacesRoute
  '/favorites': typeof ProtectedFavoritesRoute
  '/hidden': typeof ProtectedHiddenRoute
  '/library': typeof ProtectedLibraryRoute
  '/notimestamp': typeof ProtectedNotimestampRoute
  '/photos': typeof ProtectedPhotosRoute
  '/profile': typeof ProtectedProfileRoute
  '/recent': typeof ProtectedRecentRoute
  '/settings': typeof ProtectedSettingsRoute
  '/users': typeof ProtectedUsersRoute
  '/videos': typeof ProtectedVideosRoute
  '/public/$users': typeof PublicUsersRoute
  '/': typeof ProtectedIndexRoute
  '/dataviz/facescatter': typeof ProtectedDatavizFacescatterRoute
  '/dataviz/placetree': typeof ProtectedDatavizPlacetreeRoute
  '/dataviz/socialgraph': typeof ProtectedDatavizSocialgraphRoute
  '/dataviz/timeline': typeof ProtectedDatavizTimelineRoute
  '/dataviz/wordclouds': typeof ProtectedDatavizWordcloudsRoute
  '/photo/$id': typeof ProtectedPhotoIdRoute
  '/search/$query': typeof ProtectedSearchQueryRoute
  '/album/events/$id': typeof ProtectedAlbumEventsIdRoute
  '/album/persons/$id': typeof ProtectedAlbumPersonsIdRoute
  '/album/places/$id': typeof ProtectedAlbumPlacesIdRoute
  '/album/things/$id': typeof ProtectedAlbumThingsIdRoute
  '/album/user/$id': typeof ProtectedAlbumUserIdRoute
  '/shared/fromme/$tab': typeof ProtectedSharedFrommeTabRoute
  '/shared/tome/$tab': typeof ProtectedSharedTomeTabRoute
  '/album/events': typeof ProtectedAlbumEventsIndexRoute
  '/album/persons': typeof ProtectedAlbumPersonsIndexRoute
  '/album/places': typeof ProtectedAlbumPlacesIndexRoute
  '/album/things': typeof ProtectedAlbumThingsIndexRoute
  '/album/user': typeof ProtectedAlbumUserIndexRoute
}

export interface FileRoutesByTo {
  '/public': typeof PublicRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof ProtectedAdminRoute
  '/deleted': typeof ProtectedDeletedRoute
  '/faces': typeof ProtectedFacesRoute
  '/favorites': typeof ProtectedFavoritesRoute
  '/hidden': typeof ProtectedHiddenRoute
  '/library': typeof ProtectedLibraryRoute
  '/notimestamp': typeof ProtectedNotimestampRoute
  '/photos': typeof ProtectedPhotosRoute
  '/profile': typeof ProtectedProfileRoute
  '/recent': typeof ProtectedRecentRoute
  '/settings': typeof ProtectedSettingsRoute
  '/users': typeof ProtectedUsersRoute
  '/videos': typeof ProtectedVideosRoute
  '/public/$users': typeof PublicUsersRoute
  '/': typeof ProtectedIndexRoute
  '/dataviz/facescatter': typeof ProtectedDatavizFacescatterRoute
  '/dataviz/placetree': typeof ProtectedDatavizPlacetreeRoute
  '/dataviz/socialgraph': typeof ProtectedDatavizSocialgraphRoute
  '/dataviz/timeline': typeof ProtectedDatavizTimelineRoute
  '/dataviz/wordclouds': typeof ProtectedDatavizWordcloudsRoute
  '/photo/$id': typeof ProtectedPhotoIdRoute
  '/search/$query': typeof ProtectedSearchQueryRoute
  '/album/events/$id': typeof ProtectedAlbumEventsIdRoute
  '/album/persons/$id': typeof ProtectedAlbumPersonsIdRoute
  '/album/places/$id': typeof ProtectedAlbumPlacesIdRoute
  '/album/things/$id': typeof ProtectedAlbumThingsIdRoute
  '/album/user/$id': typeof ProtectedAlbumUserIdRoute
  '/shared/fromme/$tab': typeof ProtectedSharedFrommeTabRoute
  '/shared/tome/$tab': typeof ProtectedSharedTomeTabRoute
  '/album/events': typeof ProtectedAlbumEventsIndexRoute
  '/album/persons': typeof ProtectedAlbumPersonsIndexRoute
  '/album/places': typeof ProtectedAlbumPlacesIndexRoute
  '/album/things': typeof ProtectedAlbumThingsIndexRoute
  '/album/user': typeof ProtectedAlbumUserIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/public': typeof PublicRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_protected/admin': typeof ProtectedAdminRoute
  '/_protected/deleted': typeof ProtectedDeletedRoute
  '/_protected/faces': typeof ProtectedFacesRoute
  '/_protected/favorites': typeof ProtectedFavoritesRoute
  '/_protected/hidden': typeof ProtectedHiddenRoute
  '/_protected/library': typeof ProtectedLibraryRoute
  '/_protected/notimestamp': typeof ProtectedNotimestampRoute
  '/_protected/photos': typeof ProtectedPhotosRoute
  '/_protected/profile': typeof ProtectedProfileRoute
  '/_protected/recent': typeof ProtectedRecentRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_protected/users': typeof ProtectedUsersRoute
  '/_protected/videos': typeof ProtectedVideosRoute
  '/public/$users': typeof PublicUsersRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/dataviz/facescatter': typeof ProtectedDatavizFacescatterRoute
  '/_protected/dataviz/placetree': typeof ProtectedDatavizPlacetreeRoute
  '/_protected/dataviz/socialgraph': typeof ProtectedDatavizSocialgraphRoute
  '/_protected/dataviz/timeline': typeof ProtectedDatavizTimelineRoute
  '/_protected/dataviz/wordclouds': typeof ProtectedDatavizWordcloudsRoute
  '/_protected/photo/$id': typeof ProtectedPhotoIdRoute
  '/_protected/search/$query': typeof ProtectedSearchQueryRoute
  '/_protected/album/events/$id': typeof ProtectedAlbumEventsIdRoute
  '/_protected/album/persons/$id': typeof ProtectedAlbumPersonsIdRoute
  '/_protected/album/places/$id': typeof ProtectedAlbumPlacesIdRoute
  '/_protected/album/things/$id': typeof ProtectedAlbumThingsIdRoute
  '/_protected/album/user/$id': typeof ProtectedAlbumUserIdRoute
  '/_protected/shared/fromme/$tab': typeof ProtectedSharedFrommeTabRoute
  '/_protected/shared/tome/$tab': typeof ProtectedSharedTomeTabRoute
  '/_protected/album/events/': typeof ProtectedAlbumEventsIndexRoute
  '/_protected/album/persons/': typeof ProtectedAlbumPersonsIndexRoute
  '/_protected/album/places/': typeof ProtectedAlbumPlacesIndexRoute
  '/_protected/album/things/': typeof ProtectedAlbumThingsIndexRoute
  '/_protected/album/user/': typeof ProtectedAlbumUserIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/public'
    | '/login'
    | '/signup'
    | '/admin'
    | '/deleted'
    | '/faces'
    | '/favorites'
    | '/hidden'
    | '/library'
    | '/notimestamp'
    | '/photos'
    | '/profile'
    | '/recent'
    | '/settings'
    | '/users'
    | '/videos'
    | '/public/$users'
    | '/'
    | '/dataviz/facescatter'
    | '/dataviz/placetree'
    | '/dataviz/socialgraph'
    | '/dataviz/timeline'
    | '/dataviz/wordclouds'
    | '/photo/$id'
    | '/search/$query'
    | '/album/events/$id'
    | '/album/persons/$id'
    | '/album/places/$id'
    | '/album/things/$id'
    | '/album/user/$id'
    | '/shared/fromme/$tab'
    | '/shared/tome/$tab'
    | '/album/events'
    | '/album/persons'
    | '/album/places'
    | '/album/things'
    | '/album/user'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/public'
    | '/login'
    | '/signup'
    | '/admin'
    | '/deleted'
    | '/faces'
    | '/favorites'
    | '/hidden'
    | '/library'
    | '/notimestamp'
    | '/photos'
    | '/profile'
    | '/recent'
    | '/settings'
    | '/users'
    | '/videos'
    | '/public/$users'
    | '/'
    | '/dataviz/facescatter'
    | '/dataviz/placetree'
    | '/dataviz/socialgraph'
    | '/dataviz/timeline'
    | '/dataviz/wordclouds'
    | '/photo/$id'
    | '/search/$query'
    | '/album/events/$id'
    | '/album/persons/$id'
    | '/album/places/$id'
    | '/album/things/$id'
    | '/album/user/$id'
    | '/shared/fromme/$tab'
    | '/shared/tome/$tab'
    | '/album/events'
    | '/album/persons'
    | '/album/places'
    | '/album/things'
    | '/album/user'
  id:
    | '__root__'
    | '/_protected'
    | '/public'
    | '/login'
    | '/signup'
    | '/_protected/admin'
    | '/_protected/deleted'
    | '/_protected/faces'
    | '/_protected/favorites'
    | '/_protected/hidden'
    | '/_protected/library'
    | '/_protected/notimestamp'
    | '/_protected/photos'
    | '/_protected/profile'
    | '/_protected/recent'
    | '/_protected/settings'
    | '/_protected/users'
    | '/_protected/videos'
    | '/public/$users'
    | '/_protected/'
    | '/_protected/dataviz/facescatter'
    | '/_protected/dataviz/placetree'
    | '/_protected/dataviz/socialgraph'
    | '/_protected/dataviz/timeline'
    | '/_protected/dataviz/wordclouds'
    | '/_protected/photo/$id'
    | '/_protected/search/$query'
    | '/_protected/album/events/$id'
    | '/_protected/album/persons/$id'
    | '/_protected/album/places/$id'
    | '/_protected/album/things/$id'
    | '/_protected/album/user/$id'
    | '/_protected/shared/fromme/$tab'
    | '/_protected/shared/tome/$tab'
    | '/_protected/album/events/'
    | '/_protected/album/persons/'
    | '/_protected/album/places/'
    | '/_protected/album/things/'
    | '/_protected/album/user/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_protected",
        "/public",
        "/login",
        "/signup"
      ]
    },
    "/_protected": {
      "filePath": "_protected/route.tsx",
      "children": [
        "/_protected/admin",
        "/_protected/deleted",
        "/_protected/faces",
        "/_protected/favorites",
        "/_protected/hidden",
        "/_protected/library",
        "/_protected/notimestamp",
        "/_protected/photos",
        "/_protected/profile",
        "/_protected/recent",
        "/_protected/settings",
        "/_protected/users",
        "/_protected/videos",
        "/_protected/",
        "/_protected/dataviz/facescatter",
        "/_protected/dataviz/placetree",
        "/_protected/dataviz/socialgraph",
        "/_protected/dataviz/timeline",
        "/_protected/dataviz/wordclouds",
        "/_protected/photo/$id",
        "/_protected/search/$query",
        "/_protected/album/events/$id",
        "/_protected/album/persons/$id",
        "/_protected/album/places/$id",
        "/_protected/album/things/$id",
        "/_protected/album/user/$id",
        "/_protected/shared/fromme/$tab",
        "/_protected/shared/tome/$tab",
        "/_protected/album/events/",
        "/_protected/album/persons/",
        "/_protected/album/places/",
        "/_protected/album/things/",
        "/_protected/album/user/"
      ]
    },
    "/public": {
      "filePath": "public/route.tsx",
      "children": [
        "/public/$users"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/_protected/admin": {
      "filePath": "_protected/admin.tsx",
      "parent": "/_protected"
    },
    "/_protected/deleted": {
      "filePath": "_protected/deleted.tsx",
      "parent": "/_protected"
    },
    "/_protected/faces": {
      "filePath": "_protected/faces.tsx",
      "parent": "/_protected"
    },
    "/_protected/favorites": {
      "filePath": "_protected/favorites.tsx",
      "parent": "/_protected"
    },
    "/_protected/hidden": {
      "filePath": "_protected/hidden.tsx",
      "parent": "/_protected"
    },
    "/_protected/library": {
      "filePath": "_protected/library.tsx",
      "parent": "/_protected"
    },
    "/_protected/notimestamp": {
      "filePath": "_protected/notimestamp.tsx",
      "parent": "/_protected"
    },
    "/_protected/photos": {
      "filePath": "_protected/photos.tsx",
      "parent": "/_protected"
    },
    "/_protected/profile": {
      "filePath": "_protected/profile.tsx",
      "parent": "/_protected"
    },
    "/_protected/recent": {
      "filePath": "_protected/recent.tsx",
      "parent": "/_protected"
    },
    "/_protected/settings": {
      "filePath": "_protected/settings.tsx",
      "parent": "/_protected"
    },
    "/_protected/users": {
      "filePath": "_protected/users.tsx",
      "parent": "/_protected"
    },
    "/_protected/videos": {
      "filePath": "_protected/videos.tsx",
      "parent": "/_protected"
    },
    "/public/$users": {
      "filePath": "public/$users.tsx",
      "parent": "/public"
    },
    "/_protected/": {
      "filePath": "_protected/index.tsx",
      "parent": "/_protected"
    },
    "/_protected/dataviz/facescatter": {
      "filePath": "_protected/dataviz/facescatter.tsx",
      "parent": "/_protected"
    },
    "/_protected/dataviz/placetree": {
      "filePath": "_protected/dataviz/placetree.tsx",
      "parent": "/_protected"
    },
    "/_protected/dataviz/socialgraph": {
      "filePath": "_protected/dataviz/socialgraph.tsx",
      "parent": "/_protected"
    },
    "/_protected/dataviz/timeline": {
      "filePath": "_protected/dataviz/timeline.tsx",
      "parent": "/_protected"
    },
    "/_protected/dataviz/wordclouds": {
      "filePath": "_protected/dataviz/wordclouds.tsx",
      "parent": "/_protected"
    },
    "/_protected/photo/$id": {
      "filePath": "_protected/photo.$id.tsx",
      "parent": "/_protected"
    },
    "/_protected/search/$query": {
      "filePath": "_protected/search.$query.tsx",
      "parent": "/_protected"
    },
    "/_protected/album/events/$id": {
      "filePath": "_protected/album/events.$id.tsx",
      "parent": "/_protected"
    },
    "/_protected/album/persons/$id": {
      "filePath": "_protected/album/persons.$id.tsx",
      "parent": "/_protected"
    },
    "/_protected/album/places/$id": {
      "filePath": "_protected/album/places.$id.tsx",
      "parent": "/_protected"
    },
    "/_protected/album/things/$id": {
      "filePath": "_protected/album/things.$id.tsx",
      "parent": "/_protected"
    },
    "/_protected/album/user/$id": {
      "filePath": "_protected/album/user.$id.tsx",
      "parent": "/_protected"
    },
    "/_protected/shared/fromme/$tab": {
      "filePath": "_protected/shared/fromme.$tab.tsx",
      "parent": "/_protected"
    },
    "/_protected/shared/tome/$tab": {
      "filePath": "_protected/shared/tome.$tab.tsx",
      "parent": "/_protected"
    },
    "/_protected/album/events/": {
      "filePath": "_protected/album/events.index.tsx",
      "parent": "/_protected"
    },
    "/_protected/album/persons/": {
      "filePath": "_protected/album/persons.index.tsx",
      "parent": "/_protected"
    },
    "/_protected/album/places/": {
      "filePath": "_protected/album/places.index.tsx",
      "parent": "/_protected"
    },
    "/_protected/album/things/": {
      "filePath": "_protected/album/things.index.tsx",
      "parent": "/_protected"
    },
    "/_protected/album/user/": {
      "filePath": "_protected/album/user.index.tsx",
      "parent": "/_protected"
    }
  }
}
ROUTE_MANIFEST_END */
