/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PublicRouteRouteImport } from './routes/public/route'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as PublicUsersRouteImport } from './routes/public/$users'
import { Route as ProtectedVideosRouteImport } from './routes/_protected/videos'
import { Route as ProtectedUsersRouteImport } from './routes/_protected/users'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedRecentRouteImport } from './routes/_protected/recent'
import { Route as ProtectedProfileRouteImport } from './routes/_protected/profile'
import { Route as ProtectedPhotosRouteImport } from './routes/_protected/photos'
import { Route as ProtectedNotimestampRouteImport } from './routes/_protected/notimestamp'
import { Route as ProtectedLibraryRouteImport } from './routes/_protected/library'
import { Route as ProtectedHiddenRouteImport } from './routes/_protected/hidden'
import { Route as ProtectedFavoritesRouteImport } from './routes/_protected/favorites'
import { Route as ProtectedFacesRouteImport } from './routes/_protected/faces'
import { Route as ProtectedDeletedRouteImport } from './routes/_protected/deleted'
import { Route as ProtectedAdminRouteImport } from './routes/_protected/admin'
import { Route as PublicSSlugRouteImport } from './routes/public/s.$slug'
import { Route as ProtectedSearchQueryRouteImport } from './routes/_protected/search.$query'
import { Route as ProtectedPhotoIdRouteImport } from './routes/_protected/photo.$id'
import { Route as ProtectedDatavizWordcloudsRouteImport } from './routes/_protected/dataviz/wordclouds'
import { Route as ProtectedDatavizTimelineRouteImport } from './routes/_protected/dataviz/timeline'
import { Route as ProtectedDatavizSocialgraphRouteImport } from './routes/_protected/dataviz/socialgraph'
import { Route as ProtectedDatavizPlacetreeRouteImport } from './routes/_protected/dataviz/placetree'
import { Route as ProtectedDatavizFacescatterRouteImport } from './routes/_protected/dataviz/facescatter'
import { Route as ProtectedAlbumUserIndexRouteImport } from './routes/_protected/album/user.index'
import { Route as ProtectedAlbumThingsIndexRouteImport } from './routes/_protected/album/things.index'
import { Route as ProtectedAlbumPlacesIndexRouteImport } from './routes/_protected/album/places.index'
import { Route as ProtectedAlbumPersonsIndexRouteImport } from './routes/_protected/album/persons.index'
import { Route as ProtectedAlbumFolderIndexRouteImport } from './routes/_protected/album/folder.index'
import { Route as ProtectedAlbumEventsIndexRouteImport } from './routes/_protected/album/events.index'
import { Route as ProtectedSharedTomeTabRouteImport } from './routes/_protected/shared/tome.$tab'
import { Route as ProtectedSharedFrommeTabRouteImport } from './routes/_protected/shared/fromme.$tab'
import { Route as ProtectedAlbumUserIdRouteImport } from './routes/_protected/album/user.$id'
import { Route as ProtectedAlbumThingsIdRouteImport } from './routes/_protected/album/things.$id'
import { Route as ProtectedAlbumPlacesIdRouteImport } from './routes/_protected/album/places.$id'
import { Route as ProtectedAlbumPersonsIdRouteImport } from './routes/_protected/album/persons.$id'
import { Route as ProtectedAlbumFolderIdRouteImport } from './routes/_protected/album/folder.$id'
import { Route as ProtectedAlbumEventsIdRouteImport } from './routes/_protected/album/events.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/public',
  path: '/public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const PublicUsersRoute = PublicUsersRouteImport.update({
  id: '/$users',
  path: '/$users',
  getParentRoute: () => PublicRouteRoute,
} as any)
const ProtectedVideosRoute = ProtectedVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedUsersRoute = ProtectedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedRecentRoute = ProtectedRecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedProfileRoute = ProtectedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedPhotosRoute = ProtectedPhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedNotimestampRoute = ProtectedNotimestampRouteImport.update({
  id: '/notimestamp',
  path: '/notimestamp',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedLibraryRoute = ProtectedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedHiddenRoute = ProtectedHiddenRouteImport.update({
  id: '/hidden',
  path: '/hidden',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedFavoritesRoute = ProtectedFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedFacesRoute = ProtectedFacesRouteImport.update({
  id: '/faces',
  path: '/faces',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedDeletedRoute = ProtectedDeletedRouteImport.update({
  id: '/deleted',
  path: '/deleted',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedAdminRoute = ProtectedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const PublicSSlugRoute = PublicSSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => PublicRouteRoute,
} as any)
const ProtectedSearchQueryRoute = ProtectedSearchQueryRouteImport.update({
  id: '/search/$query',
  path: '/search/$query',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedPhotoIdRoute = ProtectedPhotoIdRouteImport.update({
  id: '/photo/$id',
  path: '/photo/$id',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedDatavizWordcloudsRoute =
  ProtectedDatavizWordcloudsRouteImport.update({
    id: '/dataviz/wordclouds',
    path: '/dataviz/wordclouds',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedDatavizTimelineRoute =
  ProtectedDatavizTimelineRouteImport.update({
    id: '/dataviz/timeline',
    path: '/dataviz/timeline',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedDatavizSocialgraphRoute =
  ProtectedDatavizSocialgraphRouteImport.update({
    id: '/dataviz/socialgraph',
    path: '/dataviz/socialgraph',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedDatavizPlacetreeRoute =
  ProtectedDatavizPlacetreeRouteImport.update({
    id: '/dataviz/placetree',
    path: '/dataviz/placetree',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedDatavizFacescatterRoute =
  ProtectedDatavizFacescatterRouteImport.update({
    id: '/dataviz/facescatter',
    path: '/dataviz/facescatter',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedAlbumUserIndexRoute = ProtectedAlbumUserIndexRouteImport.update({
  id: '/album/user/',
  path: '/album/user/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedAlbumThingsIndexRoute =
  ProtectedAlbumThingsIndexRouteImport.update({
    id: '/album/things/',
    path: '/album/things/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedAlbumPlacesIndexRoute =
  ProtectedAlbumPlacesIndexRouteImport.update({
    id: '/album/places/',
    path: '/album/places/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedAlbumPersonsIndexRoute =
  ProtectedAlbumPersonsIndexRouteImport.update({
    id: '/album/persons/',
    path: '/album/persons/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedAlbumFolderIndexRoute =
  ProtectedAlbumFolderIndexRouteImport.update({
    id: '/album/folder/',
    path: '/album/folder/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedAlbumEventsIndexRoute =
  ProtectedAlbumEventsIndexRouteImport.update({
    id: '/album/events/',
    path: '/album/events/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedSharedTomeTabRoute = ProtectedSharedTomeTabRouteImport.update({
  id: '/shared/tome/$tab',
  path: '/shared/tome/$tab',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedSharedFrommeTabRoute =
  ProtectedSharedFrommeTabRouteImport.update({
    id: '/shared/fromme/$tab',
    path: '/shared/fromme/$tab',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedAlbumUserIdRoute = ProtectedAlbumUserIdRouteImport.update({
  id: '/album/user/$id',
  path: '/album/user/$id',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedAlbumThingsIdRoute = ProtectedAlbumThingsIdRouteImport.update({
  id: '/album/things/$id',
  path: '/album/things/$id',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedAlbumPlacesIdRoute = ProtectedAlbumPlacesIdRouteImport.update({
  id: '/album/places/$id',
  path: '/album/places/$id',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedAlbumPersonsIdRoute = ProtectedAlbumPersonsIdRouteImport.update({
  id: '/album/persons/$id',
  path: '/album/persons/$id',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedAlbumFolderIdRoute = ProtectedAlbumFolderIdRouteImport.update({
  id: '/album/folder/$id',
  path: '/album/folder/$id',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedAlbumEventsIdRoute = ProtectedAlbumEventsIdRouteImport.update({
  id: '/album/events/$id',
  path: '/album/events/$id',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/public': typeof PublicRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof ProtectedAdminRoute
  '/deleted': typeof ProtectedDeletedRoute
  '/faces': typeof ProtectedFacesRoute
  '/favorites': typeof ProtectedFavoritesRoute
  '/hidden': typeof ProtectedHiddenRoute
  '/library': typeof ProtectedLibraryRoute
  '/notimestamp': typeof ProtectedNotimestampRoute
  '/photos': typeof ProtectedPhotosRoute
  '/profile': typeof ProtectedProfileRoute
  '/recent': typeof ProtectedRecentRoute
  '/settings': typeof ProtectedSettingsRoute
  '/users': typeof ProtectedUsersRoute
  '/videos': typeof ProtectedVideosRoute
  '/public/$users': typeof PublicUsersRoute
  '/': typeof ProtectedIndexRoute
  '/dataviz/facescatter': typeof ProtectedDatavizFacescatterRoute
  '/dataviz/placetree': typeof ProtectedDatavizPlacetreeRoute
  '/dataviz/socialgraph': typeof ProtectedDatavizSocialgraphRoute
  '/dataviz/timeline': typeof ProtectedDatavizTimelineRoute
  '/dataviz/wordclouds': typeof ProtectedDatavizWordcloudsRoute
  '/photo/$id': typeof ProtectedPhotoIdRoute
  '/search/$query': typeof ProtectedSearchQueryRoute
  '/public/s/$slug': typeof PublicSSlugRoute
  '/album/events/$id': typeof ProtectedAlbumEventsIdRoute
  '/album/folder/$id': typeof ProtectedAlbumFolderIdRoute
  '/album/persons/$id': typeof ProtectedAlbumPersonsIdRoute
  '/album/places/$id': typeof ProtectedAlbumPlacesIdRoute
  '/album/things/$id': typeof ProtectedAlbumThingsIdRoute
  '/album/user/$id': typeof ProtectedAlbumUserIdRoute
  '/shared/fromme/$tab': typeof ProtectedSharedFrommeTabRoute
  '/shared/tome/$tab': typeof ProtectedSharedTomeTabRoute
  '/album/events': typeof ProtectedAlbumEventsIndexRoute
  '/album/folder': typeof ProtectedAlbumFolderIndexRoute
  '/album/persons': typeof ProtectedAlbumPersonsIndexRoute
  '/album/places': typeof ProtectedAlbumPlacesIndexRoute
  '/album/things': typeof ProtectedAlbumThingsIndexRoute
  '/album/user': typeof ProtectedAlbumUserIndexRoute
}
export interface FileRoutesByTo {
  '/public': typeof PublicRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof ProtectedAdminRoute
  '/deleted': typeof ProtectedDeletedRoute
  '/faces': typeof ProtectedFacesRoute
  '/favorites': typeof ProtectedFavoritesRoute
  '/hidden': typeof ProtectedHiddenRoute
  '/library': typeof ProtectedLibraryRoute
  '/notimestamp': typeof ProtectedNotimestampRoute
  '/photos': typeof ProtectedPhotosRoute
  '/profile': typeof ProtectedProfileRoute
  '/recent': typeof ProtectedRecentRoute
  '/settings': typeof ProtectedSettingsRoute
  '/users': typeof ProtectedUsersRoute
  '/videos': typeof ProtectedVideosRoute
  '/public/$users': typeof PublicUsersRoute
  '/': typeof ProtectedIndexRoute
  '/dataviz/facescatter': typeof ProtectedDatavizFacescatterRoute
  '/dataviz/placetree': typeof ProtectedDatavizPlacetreeRoute
  '/dataviz/socialgraph': typeof ProtectedDatavizSocialgraphRoute
  '/dataviz/timeline': typeof ProtectedDatavizTimelineRoute
  '/dataviz/wordclouds': typeof ProtectedDatavizWordcloudsRoute
  '/photo/$id': typeof ProtectedPhotoIdRoute
  '/search/$query': typeof ProtectedSearchQueryRoute
  '/public/s/$slug': typeof PublicSSlugRoute
  '/album/events/$id': typeof ProtectedAlbumEventsIdRoute
  '/album/folder/$id': typeof ProtectedAlbumFolderIdRoute
  '/album/persons/$id': typeof ProtectedAlbumPersonsIdRoute
  '/album/places/$id': typeof ProtectedAlbumPlacesIdRoute
  '/album/things/$id': typeof ProtectedAlbumThingsIdRoute
  '/album/user/$id': typeof ProtectedAlbumUserIdRoute
  '/shared/fromme/$tab': typeof ProtectedSharedFrommeTabRoute
  '/shared/tome/$tab': typeof ProtectedSharedTomeTabRoute
  '/album/events': typeof ProtectedAlbumEventsIndexRoute
  '/album/folder': typeof ProtectedAlbumFolderIndexRoute
  '/album/persons': typeof ProtectedAlbumPersonsIndexRoute
  '/album/places': typeof ProtectedAlbumPlacesIndexRoute
  '/album/things': typeof ProtectedAlbumThingsIndexRoute
  '/album/user': typeof ProtectedAlbumUserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/public': typeof PublicRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_protected/admin': typeof ProtectedAdminRoute
  '/_protected/deleted': typeof ProtectedDeletedRoute
  '/_protected/faces': typeof ProtectedFacesRoute
  '/_protected/favorites': typeof ProtectedFavoritesRoute
  '/_protected/hidden': typeof ProtectedHiddenRoute
  '/_protected/library': typeof ProtectedLibraryRoute
  '/_protected/notimestamp': typeof ProtectedNotimestampRoute
  '/_protected/photos': typeof ProtectedPhotosRoute
  '/_protected/profile': typeof ProtectedProfileRoute
  '/_protected/recent': typeof ProtectedRecentRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_protected/users': typeof ProtectedUsersRoute
  '/_protected/videos': typeof ProtectedVideosRoute
  '/public/$users': typeof PublicUsersRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/dataviz/facescatter': typeof ProtectedDatavizFacescatterRoute
  '/_protected/dataviz/placetree': typeof ProtectedDatavizPlacetreeRoute
  '/_protected/dataviz/socialgraph': typeof ProtectedDatavizSocialgraphRoute
  '/_protected/dataviz/timeline': typeof ProtectedDatavizTimelineRoute
  '/_protected/dataviz/wordclouds': typeof ProtectedDatavizWordcloudsRoute
  '/_protected/photo/$id': typeof ProtectedPhotoIdRoute
  '/_protected/search/$query': typeof ProtectedSearchQueryRoute
  '/public/s/$slug': typeof PublicSSlugRoute
  '/_protected/album/events/$id': typeof ProtectedAlbumEventsIdRoute
  '/_protected/album/folder/$id': typeof ProtectedAlbumFolderIdRoute
  '/_protected/album/persons/$id': typeof ProtectedAlbumPersonsIdRoute
  '/_protected/album/places/$id': typeof ProtectedAlbumPlacesIdRoute
  '/_protected/album/things/$id': typeof ProtectedAlbumThingsIdRoute
  '/_protected/album/user/$id': typeof ProtectedAlbumUserIdRoute
  '/_protected/shared/fromme/$tab': typeof ProtectedSharedFrommeTabRoute
  '/_protected/shared/tome/$tab': typeof ProtectedSharedTomeTabRoute
  '/_protected/album/events/': typeof ProtectedAlbumEventsIndexRoute
  '/_protected/album/folder/': typeof ProtectedAlbumFolderIndexRoute
  '/_protected/album/persons/': typeof ProtectedAlbumPersonsIndexRoute
  '/_protected/album/places/': typeof ProtectedAlbumPlacesIndexRoute
  '/_protected/album/things/': typeof ProtectedAlbumThingsIndexRoute
  '/_protected/album/user/': typeof ProtectedAlbumUserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/public'
    | '/login'
    | '/signup'
    | '/admin'
    | '/deleted'
    | '/faces'
    | '/favorites'
    | '/hidden'
    | '/library'
    | '/notimestamp'
    | '/photos'
    | '/profile'
    | '/recent'
    | '/settings'
    | '/users'
    | '/videos'
    | '/public/$users'
    | '/'
    | '/dataviz/facescatter'
    | '/dataviz/placetree'
    | '/dataviz/socialgraph'
    | '/dataviz/timeline'
    | '/dataviz/wordclouds'
    | '/photo/$id'
    | '/search/$query'
    | '/public/s/$slug'
    | '/album/events/$id'
    | '/album/folder/$id'
    | '/album/persons/$id'
    | '/album/places/$id'
    | '/album/things/$id'
    | '/album/user/$id'
    | '/shared/fromme/$tab'
    | '/shared/tome/$tab'
    | '/album/events'
    | '/album/folder'
    | '/album/persons'
    | '/album/places'
    | '/album/things'
    | '/album/user'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/public'
    | '/login'
    | '/signup'
    | '/admin'
    | '/deleted'
    | '/faces'
    | '/favorites'
    | '/hidden'
    | '/library'
    | '/notimestamp'
    | '/photos'
    | '/profile'
    | '/recent'
    | '/settings'
    | '/users'
    | '/videos'
    | '/public/$users'
    | '/'
    | '/dataviz/facescatter'
    | '/dataviz/placetree'
    | '/dataviz/socialgraph'
    | '/dataviz/timeline'
    | '/dataviz/wordclouds'
    | '/photo/$id'
    | '/search/$query'
    | '/public/s/$slug'
    | '/album/events/$id'
    | '/album/folder/$id'
    | '/album/persons/$id'
    | '/album/places/$id'
    | '/album/things/$id'
    | '/album/user/$id'
    | '/shared/fromme/$tab'
    | '/shared/tome/$tab'
    | '/album/events'
    | '/album/folder'
    | '/album/persons'
    | '/album/places'
    | '/album/things'
    | '/album/user'
  id:
    | '__root__'
    | '/_protected'
    | '/public'
    | '/login'
    | '/signup'
    | '/_protected/admin'
    | '/_protected/deleted'
    | '/_protected/faces'
    | '/_protected/favorites'
    | '/_protected/hidden'
    | '/_protected/library'
    | '/_protected/notimestamp'
    | '/_protected/photos'
    | '/_protected/profile'
    | '/_protected/recent'
    | '/_protected/settings'
    | '/_protected/users'
    | '/_protected/videos'
    | '/public/$users'
    | '/_protected/'
    | '/_protected/dataviz/facescatter'
    | '/_protected/dataviz/placetree'
    | '/_protected/dataviz/socialgraph'
    | '/_protected/dataviz/timeline'
    | '/_protected/dataviz/wordclouds'
    | '/_protected/photo/$id'
    | '/_protected/search/$query'
    | '/public/s/$slug'
    | '/_protected/album/events/$id'
    | '/_protected/album/folder/$id'
    | '/_protected/album/persons/$id'
    | '/_protected/album/places/$id'
    | '/_protected/album/things/$id'
    | '/_protected/album/user/$id'
    | '/_protected/shared/fromme/$tab'
    | '/_protected/shared/tome/$tab'
    | '/_protected/album/events/'
    | '/_protected/album/folder/'
    | '/_protected/album/persons/'
    | '/_protected/album/places/'
    | '/_protected/album/things/'
    | '/_protected/album/user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public': {
      id: '/public'
      path: '/public'
      fullPath: '/public'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/public/$users': {
      id: '/public/$users'
      path: '/$users'
      fullPath: '/public/$users'
      preLoaderRoute: typeof PublicUsersRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_protected/videos': {
      id: '/_protected/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof ProtectedVideosRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/users': {
      id: '/_protected/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof ProtectedUsersRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/recent': {
      id: '/_protected/recent'
      path: '/recent'
      fullPath: '/recent'
      preLoaderRoute: typeof ProtectedRecentRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/profile': {
      id: '/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedProfileRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/photos': {
      id: '/_protected/photos'
      path: '/photos'
      fullPath: '/photos'
      preLoaderRoute: typeof ProtectedPhotosRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/notimestamp': {
      id: '/_protected/notimestamp'
      path: '/notimestamp'
      fullPath: '/notimestamp'
      preLoaderRoute: typeof ProtectedNotimestampRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/library': {
      id: '/_protected/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof ProtectedLibraryRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/hidden': {
      id: '/_protected/hidden'
      path: '/hidden'
      fullPath: '/hidden'
      preLoaderRoute: typeof ProtectedHiddenRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/favorites': {
      id: '/_protected/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof ProtectedFavoritesRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/faces': {
      id: '/_protected/faces'
      path: '/faces'
      fullPath: '/faces'
      preLoaderRoute: typeof ProtectedFacesRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/deleted': {
      id: '/_protected/deleted'
      path: '/deleted'
      fullPath: '/deleted'
      preLoaderRoute: typeof ProtectedDeletedRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/public/s/$slug': {
      id: '/public/s/$slug'
      path: '/s/$slug'
      fullPath: '/public/s/$slug'
      preLoaderRoute: typeof PublicSSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_protected/search/$query': {
      id: '/_protected/search/$query'
      path: '/search/$query'
      fullPath: '/search/$query'
      preLoaderRoute: typeof ProtectedSearchQueryRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/photo/$id': {
      id: '/_protected/photo/$id'
      path: '/photo/$id'
      fullPath: '/photo/$id'
      preLoaderRoute: typeof ProtectedPhotoIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/dataviz/wordclouds': {
      id: '/_protected/dataviz/wordclouds'
      path: '/dataviz/wordclouds'
      fullPath: '/dataviz/wordclouds'
      preLoaderRoute: typeof ProtectedDatavizWordcloudsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/dataviz/timeline': {
      id: '/_protected/dataviz/timeline'
      path: '/dataviz/timeline'
      fullPath: '/dataviz/timeline'
      preLoaderRoute: typeof ProtectedDatavizTimelineRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/dataviz/socialgraph': {
      id: '/_protected/dataviz/socialgraph'
      path: '/dataviz/socialgraph'
      fullPath: '/dataviz/socialgraph'
      preLoaderRoute: typeof ProtectedDatavizSocialgraphRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/dataviz/placetree': {
      id: '/_protected/dataviz/placetree'
      path: '/dataviz/placetree'
      fullPath: '/dataviz/placetree'
      preLoaderRoute: typeof ProtectedDatavizPlacetreeRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/dataviz/facescatter': {
      id: '/_protected/dataviz/facescatter'
      path: '/dataviz/facescatter'
      fullPath: '/dataviz/facescatter'
      preLoaderRoute: typeof ProtectedDatavizFacescatterRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/album/user/': {
      id: '/_protected/album/user/'
      path: '/album/user'
      fullPath: '/album/user'
      preLoaderRoute: typeof ProtectedAlbumUserIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/album/things/': {
      id: '/_protected/album/things/'
      path: '/album/things'
      fullPath: '/album/things'
      preLoaderRoute: typeof ProtectedAlbumThingsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/album/places/': {
      id: '/_protected/album/places/'
      path: '/album/places'
      fullPath: '/album/places'
      preLoaderRoute: typeof ProtectedAlbumPlacesIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/album/persons/': {
      id: '/_protected/album/persons/'
      path: '/album/persons'
      fullPath: '/album/persons'
      preLoaderRoute: typeof ProtectedAlbumPersonsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/album/folder/': {
      id: '/_protected/album/folder/'
      path: '/album/folder'
      fullPath: '/album/folder'
      preLoaderRoute: typeof ProtectedAlbumFolderIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/album/events/': {
      id: '/_protected/album/events/'
      path: '/album/events'
      fullPath: '/album/events'
      preLoaderRoute: typeof ProtectedAlbumEventsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/shared/tome/$tab': {
      id: '/_protected/shared/tome/$tab'
      path: '/shared/tome/$tab'
      fullPath: '/shared/tome/$tab'
      preLoaderRoute: typeof ProtectedSharedTomeTabRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/shared/fromme/$tab': {
      id: '/_protected/shared/fromme/$tab'
      path: '/shared/fromme/$tab'
      fullPath: '/shared/fromme/$tab'
      preLoaderRoute: typeof ProtectedSharedFrommeTabRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/album/user/$id': {
      id: '/_protected/album/user/$id'
      path: '/album/user/$id'
      fullPath: '/album/user/$id'
      preLoaderRoute: typeof ProtectedAlbumUserIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/album/things/$id': {
      id: '/_protected/album/things/$id'
      path: '/album/things/$id'
      fullPath: '/album/things/$id'
      preLoaderRoute: typeof ProtectedAlbumThingsIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/album/places/$id': {
      id: '/_protected/album/places/$id'
      path: '/album/places/$id'
      fullPath: '/album/places/$id'
      preLoaderRoute: typeof ProtectedAlbumPlacesIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/album/persons/$id': {
      id: '/_protected/album/persons/$id'
      path: '/album/persons/$id'
      fullPath: '/album/persons/$id'
      preLoaderRoute: typeof ProtectedAlbumPersonsIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/album/folder/$id': {
      id: '/_protected/album/folder/$id'
      path: '/album/folder/$id'
      fullPath: '/album/folder/$id'
      preLoaderRoute: typeof ProtectedAlbumFolderIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/album/events/$id': {
      id: '/_protected/album/events/$id'
      path: '/album/events/$id'
      fullPath: '/album/events/$id'
      preLoaderRoute: typeof ProtectedAlbumEventsIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedAdminRoute: typeof ProtectedAdminRoute
  ProtectedDeletedRoute: typeof ProtectedDeletedRoute
  ProtectedFacesRoute: typeof ProtectedFacesRoute
  ProtectedFavoritesRoute: typeof ProtectedFavoritesRoute
  ProtectedHiddenRoute: typeof ProtectedHiddenRoute
  ProtectedLibraryRoute: typeof ProtectedLibraryRoute
  ProtectedNotimestampRoute: typeof ProtectedNotimestampRoute
  ProtectedPhotosRoute: typeof ProtectedPhotosRoute
  ProtectedProfileRoute: typeof ProtectedProfileRoute
  ProtectedRecentRoute: typeof ProtectedRecentRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedUsersRoute: typeof ProtectedUsersRoute
  ProtectedVideosRoute: typeof ProtectedVideosRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedDatavizFacescatterRoute: typeof ProtectedDatavizFacescatterRoute
  ProtectedDatavizPlacetreeRoute: typeof ProtectedDatavizPlacetreeRoute
  ProtectedDatavizSocialgraphRoute: typeof ProtectedDatavizSocialgraphRoute
  ProtectedDatavizTimelineRoute: typeof ProtectedDatavizTimelineRoute
  ProtectedDatavizWordcloudsRoute: typeof ProtectedDatavizWordcloudsRoute
  ProtectedPhotoIdRoute: typeof ProtectedPhotoIdRoute
  ProtectedSearchQueryRoute: typeof ProtectedSearchQueryRoute
  ProtectedAlbumEventsIdRoute: typeof ProtectedAlbumEventsIdRoute
  ProtectedAlbumFolderIdRoute: typeof ProtectedAlbumFolderIdRoute
  ProtectedAlbumPersonsIdRoute: typeof ProtectedAlbumPersonsIdRoute
  ProtectedAlbumPlacesIdRoute: typeof ProtectedAlbumPlacesIdRoute
  ProtectedAlbumThingsIdRoute: typeof ProtectedAlbumThingsIdRoute
  ProtectedAlbumUserIdRoute: typeof ProtectedAlbumUserIdRoute
  ProtectedSharedFrommeTabRoute: typeof ProtectedSharedFrommeTabRoute
  ProtectedSharedTomeTabRoute: typeof ProtectedSharedTomeTabRoute
  ProtectedAlbumEventsIndexRoute: typeof ProtectedAlbumEventsIndexRoute
  ProtectedAlbumFolderIndexRoute: typeof ProtectedAlbumFolderIndexRoute
  ProtectedAlbumPersonsIndexRoute: typeof ProtectedAlbumPersonsIndexRoute
  ProtectedAlbumPlacesIndexRoute: typeof ProtectedAlbumPlacesIndexRoute
  ProtectedAlbumThingsIndexRoute: typeof ProtectedAlbumThingsIndexRoute
  ProtectedAlbumUserIndexRoute: typeof ProtectedAlbumUserIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedAdminRoute: ProtectedAdminRoute,
  ProtectedDeletedRoute: ProtectedDeletedRoute,
  ProtectedFacesRoute: ProtectedFacesRoute,
  ProtectedFavoritesRoute: ProtectedFavoritesRoute,
  ProtectedHiddenRoute: ProtectedHiddenRoute,
  ProtectedLibraryRoute: ProtectedLibraryRoute,
  ProtectedNotimestampRoute: ProtectedNotimestampRoute,
  ProtectedPhotosRoute: ProtectedPhotosRoute,
  ProtectedProfileRoute: ProtectedProfileRoute,
  ProtectedRecentRoute: ProtectedRecentRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedUsersRoute: ProtectedUsersRoute,
  ProtectedVideosRoute: ProtectedVideosRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedDatavizFacescatterRoute: ProtectedDatavizFacescatterRoute,
  ProtectedDatavizPlacetreeRoute: ProtectedDatavizPlacetreeRoute,
  ProtectedDatavizSocialgraphRoute: ProtectedDatavizSocialgraphRoute,
  ProtectedDatavizTimelineRoute: ProtectedDatavizTimelineRoute,
  ProtectedDatavizWordcloudsRoute: ProtectedDatavizWordcloudsRoute,
  ProtectedPhotoIdRoute: ProtectedPhotoIdRoute,
  ProtectedSearchQueryRoute: ProtectedSearchQueryRoute,
  ProtectedAlbumEventsIdRoute: ProtectedAlbumEventsIdRoute,
  ProtectedAlbumFolderIdRoute: ProtectedAlbumFolderIdRoute,
  ProtectedAlbumPersonsIdRoute: ProtectedAlbumPersonsIdRoute,
  ProtectedAlbumPlacesIdRoute: ProtectedAlbumPlacesIdRoute,
  ProtectedAlbumThingsIdRoute: ProtectedAlbumThingsIdRoute,
  ProtectedAlbumUserIdRoute: ProtectedAlbumUserIdRoute,
  ProtectedSharedFrommeTabRoute: ProtectedSharedFrommeTabRoute,
  ProtectedSharedTomeTabRoute: ProtectedSharedTomeTabRoute,
  ProtectedAlbumEventsIndexRoute: ProtectedAlbumEventsIndexRoute,
  ProtectedAlbumFolderIndexRoute: ProtectedAlbumFolderIndexRoute,
  ProtectedAlbumPersonsIndexRoute: ProtectedAlbumPersonsIndexRoute,
  ProtectedAlbumPlacesIndexRoute: ProtectedAlbumPlacesIndexRoute,
  ProtectedAlbumThingsIndexRoute: ProtectedAlbumThingsIndexRoute,
  ProtectedAlbumUserIndexRoute: ProtectedAlbumUserIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicUsersRoute: typeof PublicUsersRoute
  PublicSSlugRoute: typeof PublicSSlugRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicUsersRoute: PublicUsersRoute,
  PublicSSlugRoute: PublicSSlugRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
