class Tags:
    RATING = "Rating"
    IMAGE_HEIGHT = "ImageHeight"
    IMAGE_WIDTH = "ImageWidth"
    DATE_TIME_ORIGINAL = "EXIF:DateTimeOriginal"
    DATE_TIME = "EXIF:DateTime"
    QUICKTIME_CREATE_DATE = "QuickTime:CreateDate"
    QUICKTIME_DURATION = "QuickTime:Duration"
    LATITUDE = "Composite:GPSLatitude"
    LONGITUDE = "Composite:GPSLongitude"
    GPS_DATE_TIME = "Composite:GPSDateTime"
    FILE_SIZE = "File:FileSize"
    FSTOP = "EXIF:FNumber"
    EXPOSURE_TIME = "EXIF:ExposureTime"
    ISO = "EXIF:ISOSpeedRatings"
    FOCAL_LENGTH = "EXIF:FocalLength"
    FOCAL_LENGTH_35MM = "EXIF:FocalLengthIn35mmFilm"
    SHUTTER_SPEED = "EXIF:ShutterSpeedValue"
    CAMERA = "EXIF:Model"
    LENS = "EXIF:LensModel"
    SUBJECT_DISTANCE = "EXIF:SubjectDistance"
    DIGITAL_ZOOM_RATIO = "EXIF:DigitalZoomRatio"
    REGION_INFO = "XMP:RegionInfo"
    ROTATION = "QuickTime:Rotation"
    ORIENTATION = "EXIF:Orientation"

    # Burst/sequence detection tags
    SUBSEC_TIME_ORIGINAL = "EXIF:SubSecTimeOriginal"
    SUBSEC_TIME = "EXIF:SubSecTime"
    IMAGE_NUMBER = "EXIF:ImageNumber"
    IMAGE_UNIQUE_ID = "EXIF:ImageUniqueID"
    BURST_MODE = "MakerNotes:BurstMode"
    CONTINUOUS_DRIVE = "MakerNotes:ContinuousDrive"
    SEQUENCE_NUMBER = "MakerNotes:SequenceNumber"
    # Camera serial number (useful for grouping shots from same camera)
    SERIAL_NUMBER = "EXIF:SerialNumber"
    CAMERA_SERIAL = "MakerNotes:SerialNumber"

