import os
import sys

from django.core.management.base import BaseCommand, CommandError
from django.core.validators import ValidationError, validate_email
from django.utils.crypto import get_random_string

from api.models import User

# Length of an autogenerated password. Replaces the removed
# User.objects.make_random_password(), which defaulted to 10 characters.
GENERATED_PASSWORD_LENGTH = 32


class Command(BaseCommand):
    help = "Create a LibrePhotos user"

    def add_arguments(self, parser):
        parser.add_argument("username", help="Username to create")
        parser.add_argument("email", help="Email address of the new user")
        parser.add_argument(
            "--password",
            help="Password to create/update for user. (autogenerate if omitted)",
        )
        parser.add_argument(
            "--update",
            help=(
                "Update an existing user's password (ignoring the provided email) "
                "instead of reporting an error"
            ),
            action="store_true",
        )
        parser.add_argument(
            "--admin",
            help="Create user with administrative privileges",
            action="store_true",
        )
        # Done this way because command lines are visible to the whole system by
        #  default on Linux, so a password in the arguments would leak
        parser.epilog = (
            "When creating user with administrative privileges,"
            "the password is read from the ADMIN_PASSWORD"
            "environment variable or interactively if"
            "ADMIN_PASSWORD is not set"
        )

    def handle(self, *args, **options):
        self._validate_email(options["email"])

        username = options["username"].lower()
        password = self._resolve_password(options)

        if not User.objects.filter(username=username).exists():
            self._create_user(username, options["email"], password, options["admin"])
        elif options["update"]:
            self._update_password(username, options["email"], password)
        else:
            raise CommandError("Specified user already exists")

    def _validate_email(self, email):
        try:
            validate_email(email)
        except ValidationError as err:
            raise CommandError(err.message)

    def _resolve_password(self, options):
        if options["admin"] and "ADMIN_PASSWORD" in os.environ:
            options["password"] = os.environ["ADMIN_PASSWORD"]
        if not options["password"]:
            options["password"] = get_random_string(GENERATED_PASSWORD_LENGTH)
        return options["password"]

    def _create_user(self, username, email, password, admin):
        create = User.objects.create_superuser if admin else User.objects.create_user
        create(username, email, password)

    def _update_password(self, username, email, password):
        print("Warning: ignoring provided email " + email, file=sys.stderr)
        user = User.objects.get(username=username)
        user.set_password(password)
        user.save()
