class Tags:
    RATING = "Rating"
    IMAGE_HEIGHT = "ImageHeight"
    IMAGE_WIDTH = "ImageWidth"
    DATE_TIME_ORIGINAL = "EXIF:DateTimeOriginal"
    QUICKTIME_CREATE_DATE = "QuickTime:CreateDate"
    LATITUDE = "Composite:GPSLatitude"
    LONGITUDE = "Composite:GPSLongitude"
    GPS_DATE_TIME = "Composite:GPSDateTime"
    RIFF_DATE_TIME_ORIGINAL = "RIFF:DateTimeOriginal"
    MAKERNOTES_DATE_TIME_ORIGINAL = "MakerNotes:DateTimeOriginal"
    MAKERNOTES_MAKE = "MakerNotes:Make"
    EXIF_MAKE = "EXIF:Make"
    MAKERNOTES_MODEL = "MakerNotes:Model"
    EXIF_MODEL = "EXIF:Model"
    MAKERNOTES_TYPE = "MakerNotes:MakerNoteType"
    MAKERNOTES_VERSION = "MakerNotes:MakerNoteVersion"
    EXIF_ModifyDate = "EXIF:ModifyDate"
