name: image-backend-base

on:
  push:
    branches: [dev]
    paths:
      - 'deploy/docker/backend/base/**'
      - '.github/workflows/image-backend-base.yml'
      - '.github/workflows/_build-image.yml'

permissions:
  contents: read

jobs:
  dev:
    uses: ./.github/workflows/_build-image.yml
    with:
      image: reallibrephotos/librephotos-base
      context: deploy/docker/backend/base
      dockerfile: deploy/docker/backend/base/Dockerfile
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
