name: image-unified

on:
  release:
    types: [created]
  push:
    branches: [dev]
    paths:
      - 'apps/backend/**'
      - 'apps/frontend/**'
      - 'deploy/docker/unified/**'
      - '.github/workflows/image-unified.yml'
      - '.github/workflows/_build-image.yml'

jobs:
  dev:
    if: github.event_name != 'release'
    uses: ./.github/workflows/_build-image.yml
    with:
      image: reallibrephotos/librephotos-unified
      dockerfile: deploy/docker/unified/Dockerfile
      build-args: |
        IMAGE_TAG=dev
    secrets: inherit

  release:
    if: github.event_name == 'release' && github.event.action == 'created'
    uses: ./.github/workflows/_build-image.yml
    with:
      image: reallibrephotos/librephotos-unified
      dockerfile: deploy/docker/unified/Dockerfile
      release-tag: ${{ github.event.release.tag_name }}
      build-args: |
        IMAGE_TAG=${{ github.event.release.tag_name }}
    secrets: inherit
