name: image-backend

on:
  release:
    types: [created]
  push:
    branches: [dev]
    paths:
      - 'apps/backend/**'
      - 'deploy/docker/backend/Dockerfile'
      - 'deploy/docker/backend/entrypoint.sh'
      - '.github/workflows/image-backend.yml'
      - '.github/workflows/_build-image.yml'

permissions:
  contents: read

jobs:
  dev:
    if: github.event_name != 'release'
    uses: ./.github/workflows/_build-image.yml
    with:
      image: reallibrephotos/librephotos
      dockerfile: deploy/docker/backend/Dockerfile
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  release:
    if: github.event_name == 'release' && github.event.action == 'created'
    uses: ./.github/workflows/_build-image.yml
    with:
      image: reallibrephotos/librephotos
      dockerfile: deploy/docker/backend/Dockerfile
      release-tag: ${{ github.event.release.tag_name }}
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
